<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 08/01/2005 -->
<head>
	<title></title>
	<meta name="description" content="">
	<meta name="keywords" content="">
	<meta name="author" content="Chris Newey">
	<meta name="generator" content="AceHTML 5 Freeware">
	<link rel="stylesheet" type="text/css" href="css/all.css" />		
	<link rel="stylesheet" type="text/css" href="css/3cols.css" />		
</head>

<body>

<!-- START BANNER DIV -->
<DIV id=banner>

<span style="float:left;margin-top:2px; margin-left:5px;">
<img src="../cofe_logo001.gif" border="0" " alt=""> 
</span>

<span style="margin-top:2px; margin-left:10px; font-size:30px; font-weight:bold;">
Christ Church
</span>
High Street, Lye, Stourbridge, West Midlands, UK
</DIV>
<!-- END BANNER DIV -->

<br>
<h2>Website Maintenance</h2>

<ul>
<p>
	<li><a href="bregevent.php" title="bregevent">Regular Events</a></li> 
</p>
<p>
	<li><a href="bforthevent.php" title="bforthevent">Forthcoming Events</a></li> 
</p>
<p>
	<li><a href="bblog.php" title="bblog">Blog Entries</a></li> 
</p>
<p>
	<li><a href="borgs.php" title="borgs">Organisations</a></li> 
</p>
<p>
	<li><a href="bmenus.php" title="bmenus">Menu Configuration</a></li> 
</p>
</ul>

<p>
In the real world this page and all the maintenance pages would be password protected.
</p>
<p>
<a href="../index.php" title="admin">Home</a>
</p>

</body>
</html>
