<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 02/12/2004 -->
<head>
	<title></title>
	<meta name="description" content="">
	<meta name="keywords" content="">
	<meta name="author" content="newey499@hotmail.com">
	<meta name="generator" content="AceHTML 5 Freeware">
	<link rel="stylesheet" type="text/css" href="/css/server.css" />
	<link rel="stylesheet" type="text/css" href="css/site.css" />		
</head>
<body>
<!-- ------------------ HEADER --------------------------------------- -->	
<H3>Bookshop Catalogue Demo - vhosts/books</H3>
<hr />
<!-- ---------------- END HEADER ------------------------------------- -->
<?php
require_once "mysql.php";
require_once "dumpquerytotable.php";
require_once "globals.php";
?>
<p>
<H4>Demomain</H4>
</P>

<?php

$dbHandle = mysqli_connect(MYSQL_SERVER, MYSQL_USERNAME, MYSQL_PASSWORD)
	   or die("Could not connect to server: MYSQL_SERVER : " . mysqli_error());
mysqli_select_db($dbHandle,MYSQL_DATABASE) or die("Could not select database: MYSQL_DATABASE : " . msql_error());	 

$qry = "SELECT id,org_id,frequency,eventname 
        FROM regularevents";  


$obj = new dumpQryToTable($dbHandle,$qry);

//$obj->columnTitles = array("Title","Author","Published","Price","Notes");
$obj->borderSize = 1;
$obj->insertTarget = "editdeletebooks.php";
$obj->editTarget = "editdeletebooks.php";
$obj->deleteTarget = "updatewebbooks.php";

$obj->addPrimaryKeyColumn('id');

$obj->addColumn("id","Id");
$obj->addColumn("org_id","Organisation");
$obj->addColumn("eventname","Name of Event");
//$obj->addColumn("eventdesc","Description of Event");

//$obj->tableClass = "error";
//$obj->tableId = "centercontent";
//$obj->thClass = "error";
//$obj->tdClass = "error";

$obj->exec();





?>

<!-- ------------------ FOOTER --------------------------------------- -->
<HR>
<div class=rightalign>   © Chris Newey 2004: </div>
</body>
</html>
<!-- ---------------- END FOOTER ------------------------------------- -->
