<?php
	require_once "../globals.php";
	require_once("../mysql.php");
	require_once("../buildform.php");	
?>
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 02/12/2004 -->
<head>

	<title>Regular Events</title>
<?php
	include_once("../nocache.php");						// Stop clients from cacheing - hopefully
?>
	<meta name="description" content="">
	<meta name="keywords" content="">
	<meta name="author" content="Chris Newey">
	<meta name="generator" content="AceHTML 5 Freeware">
	<link rel="stylesheet" type="text/css" href="css/all.css" />
	<link rel="stylesheet" type="text/css" href="css/3cols.css" />			
</head>
<body>
<!-- ------------------ HEADER --------------------------------------- -->	


<?php
	$_GET['opcode'] = strtoupper($_GET['opcode']);
	
	switch ($_GET['opcode']) {
		case INSERT_REC:		
			print "<h3>Insert a new Regular Event</h3>\n";
			break;
		case UPDATE_REC:		
			print "<h3>Update this existing Regular Event</h3>\n";
			break;
		case DELETE_REC:		
			print "<h3>Delete this Regular Event</h3>\n";
			break;
		default: 			
			break;
	}
?>
<hr />
<!-- ---------------- END HEADER ------------------------------------- -->

	

<?php
	
	$query = "SELECT id,frequency,eventname,eventdesc 
					  FROM regularevents "; 
					  
	if ((strcmp(strtoupper($_GET['opcode']), INSERT_REC) == 0)) {
		$query = $query . " LIMIT 0 OFFSET 1";  // This is an insert so only get one row for the meta information
	}
	else {
		$query = $query . " WHERE id = " . $_GET['id'];		
	}
						
	$flds  = array('frequency' 		=> 'Frequency',
	              'eventname'			=> 'Event Name',
	              'eventdesc' 		=> 'Description',								
							  );
							  
	$pkey = array('id'	=> $_GET['opcode']);
	
	$obj = new buildForm($_GET['opcode'],$query,$pkey,$flds);
	$obj->submitTarget = "sqlregevents.php";
	$obj->pkey = array('id' => $_GET['id']); 		
	
	$obj->addLink("admin.php","Admin");	// Add a link to take us back to the Admin page
	$obj->addLink("index.php","Home");			// Add a link to take us back to the Home page	
	$obj->addLink("bregevent.php","Regular Events");			// Add a link to take us back to the Home page		
	
	
	echo "<div class=\"cdnform\">\n";
	$obj->exec($opcode);
	echo "</div>\n";
?>
</P>

<!-- ------------------ FOOTER --------------------------------------- -->
<HR>

</body>
</html>
<!-- ---------------- END FOOTER ------------------------------------- -->
