<?php
	require_once "../globals.php";
	require_once("../mysql.php");
	require_once("../buildform.php");	
	$_POST['opcode'] = strtoupper($_POST['opcode']);

	switch ($_POST['opcode']) {
		case INSERT_REC:		
			$pageTitle="Insert a new Regular Event";
			break;
		case UPDATE_REC:		
			$pageTitle="Update this existing Regular Event";
			break;
		case DELETE_REC:		
			$pageTitle="Delete this Regular Event";
			break;			
		default: 			
			$pageTitle="Unexpected opcode " . $_POST['opcode'];
			break;
	}
	
?>	
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 02/12/2004 -->
<head>
<title>Regular Events</title>
	<meta name="description" content="">
	<meta name="keywords" content="">
	<meta name="author" content="Chris Newey">
	<meta name="generator" content="AceHTML 5 Freeware">
	<link rel="stylesheet" type="text/css" href="css/all.css" />
	<link rel="stylesheet" type="text/css" href="css/3cols.css" />		
</head>
<body>
<!-- ------------------ HEADER --------------------------------------- -->	
<?php
print "<H3>$pageTitle</H3>\n";
?>
<hr />
<!-- ---------------- END HEADER ------------------------------------- -->


<?php

/*********************
 Validate fields to be written to row
 
 ****************************************/
function validate() {
	
	$result = true;

	// If we are going to delete it we don't care if its valid
	if ($_POST['opcode'] == DELETE_REC) {
		return True;
	}	
	
		
	//frequency may not be blank
	if ((!isset($_POST['frequency'])) || (!is_string($_POST['frequency'])) || (trim($_POST['frequency']) == "")) {
		dispError("Frequency may not be blank");
		$result = false;
	}
	
	//eventname may not be blank
	if ((!isset($_POST['eventname'])) || (!is_string($_POST['eventname'])) || (trim($_POST['eventname']) == "")) {
		dispError("Event Name may not be blank");		
		$result = false;	
	}
	
	//eventdesc may not be blank
	if ((!isset($_POST['eventdesc'])) || (!is_string($_POST['eventdesc'])) || (trim($_POST['eventdesc']) == "")) {
		dispWarn("Warning : Event Description is blank");		
	}	
	
	return $result;
} 
 


	
/********************
 Add/Amend/Delete SQL 
 ***********************/	
function doSQL() {

	/* Connect to a MySQL server */ 
	$dbHandle = mysql_connect(MYSQL_SERVER, MYSQL_USERNAME, MYSQL_PASSWORD)
	   or die('Could not connect: ' . mysql_error());

	mysql_select_db(MYSQL_DATABASE)  or die('Could not select database');


	switch ($_POST['opcode']) {
		case INSERT_REC:		
			$stmnt = sprintf("INSERT INTO regularevents 
											(frequency,eventname,eventdesc)
											VALUES ('%s', '%s', '%s')",
											mysql_real_escape_string($_POST['frequency']),
											mysql_real_escape_string($_POST['eventname']),
											mysql_real_escape_string($_POST['eventdesc'])
										); 
			$msg = 'Record Created OK';						
			break;
			
		case UPDATE_REC:		
			$stmnt = sprintf("UPDATE regularevents 
											 SET frequency = '%s',eventname = '%s',eventdesc='%s'
											 WHERE id=%d",
											 mysql_real_escape_string($_POST['frequency']),
											 mysql_real_escape_string($_POST['eventname']),
											 mysql_real_escape_string($_POST['eventdesc']),	
											 $_POST['id']										 											 
											 ); 
			$msg = "Record updated OK"; 			
			break;
			
		case DELETE_REC:		
			$stmnt = sprintf("DELETE FROM regularevents 
																WHERE id=%d",
											$_POST['id']					
											); 
			$msg = "Record Deleted OK"; 				
			break;
			
		default: 			
			die("Unknown opcode in sqlregevents.php");
			break;
	}



	if (mysql_query($stmnt)) {
		print("<p>" . $msg . "</p>\n"); 
	}
	else {
		print("<p>" . mysql_error() . "</p>\n");
	}



}

?>



<?php
	/*****************
	 Main Processing
	 **********************/
	
	$_POST['opcode'] = strtoupper($_POST['opcode']);
	
	if (validate())
		doSQL();
	else {
		$args = http_build_query(array('opcode' => $_POST['opcode']) + array('id' => $_POST['id']));
		print("<p>Return to Regular Event <a href=\"editregevents.php?$args\">Edit Page</a></p>\n");		
	}

		
	print("<p>" . 
	      "Return to <a href=\"bregevent.php?$args\">Regular Events</a>" . 
	      "&nbsp;&nbsp;<a href=\"admin.php?$args\">Admin</a>" . 	      
	      "</p>\n");

?>

<!-- ------------------ FOOTER --------------------------------------- -->
<HR>
<div class=rightalign>   &copy; Chris Newey 2004: </div>
</body>
</html>
<!-- ---------------- END FOOTER ------------------------------------- -->
