<?php
	/******************************
		Talk to MySQL
	**********************************/
	require_once("mysql.php");


	/******************************
		Start a session
	**********************************/
	require_once("session.php");
	$oSession = new session();
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 14/01/2005 -->
<head>
<title>Christ Church, Lye, West Midlands. UK</title>
<?php
	require_once("nocache.php");	// Stop - hopefully - this page being cached
?>

<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta name="description" content="">
<meta name="keywords" content="">
<meta name="author" content="newey499@hotmail.com">
<meta name="generator" content="AceHTML 5 Freeware">

  <!-- CSS Includes -->
  <link rel="stylesheet" type="text/css" href="css/layout.css" >
  <link rel="stylesheet" type="text/css" href="css/church.css" >
  <link rel="stylesheet" type="text/css" href="css/slideshow.css" >
  <link rel="stylesheet" type="text/css" href="css/tooltip.css" >
  <link rel="stylesheet" type="text/css" media="print" href="css/print.css" >
  <link rel="stylesheet" type="text/css" href="css/cssdropdownmenu.css" />
  <!-- End CSS Includes -->

</head>
<body>

<?php
	require_once("mysql.php");
	require_once("globals.php");
	require_once("genlib.php");
?>

<!-- ========================================================================== -->
<!--                            Start of CSS Layout                             -->
<!-- ========================================================================== -->
<div id="maincontainer">

<!-- ========================================================================== -->
<!--                             Start Top Section                              -->
<!-- ========================================================================== -->
<div id="topsection">
<div class="innertube">

<!-- Top Banner for site -->
<?php
	include_once("topbanner.php");
?>

</div>  <!-- End <div class="innertube"> -->
</div>  <!-- End <div id="topsection"> -->

<!-- This extra pointless div is needed to get IE out of the crap -->
<!-- Without it the top banner is not displayed                   -->
<!--[if IE ]>
	<div>
	</div>
<![endif]-->


<!-- ========================================================================== -->
<!--                               End Top Section                              -->
<!-- ========================================================================== -->



<!-- ========================================================================== -->
<!--                              Start Text Section                            -->
<!-- ========================================================================== -->
<div style="margin-left:2em; margin-right:2em;">


<!-- Top Banner for site -->
<?php
	include_once("topbanner.php");
?>

<br />


<p>
<?php
	backToSermonsTalksPage();
?>
</p>




<h4>
﻿Doom is no Joke
<br />
Ezekiel 7 - 8
</h4>


<p>
<h4>
Introduction
</h4>
</p>

<p>
Doom is a sober word but one which in English language has lost its real meaning. I am sure all recall the very dour Scottish private Fraser from Dads Army who as soon as anything went wrong would start wailing "Doomed doomed, we are all doomed".  We laughed;   and yet surely you would also agree there is nothing funny about a real warning about something very serious being ignored. That is an awful tragedy.
</p>

<p>
Unfortunately people today - even in the church sometimes do not take the judgement of God seriously. That is a slur on his holy character.  God cannot ignore sin. Here in front of us we have two chapters that are very clear on the reality and reasons for Gods judgement and punishment of sin.
</p>

<p>
So as shown in chapter 7 the reality.  And in chapter 8 the reasons.
</p>

<p>
<h4>
The Reality of Judgement Chapter 7
</h4>
</p>

<p>
The judgement of God on the sin of mankind is certain. Ezekiel in his prophecy repeatedly spells out this fact for the city of Jerusalem.
</p>

<p>
In case you’re not sure let me just run through the passage for a minute. In v 2 we read the end has come, v5 Disaster, and in v 7 Doom has come.  In v10 again here words the day is here.  Judgement is on everyone in v12 both the buyer and the seller. Money is useless, so as in v 15 wherever you are,  judgement will come, whether in the city or outside.  And so on.
</p>

<p>
On thing very clear from this passage - Gods judgement on Jerusalem is inevitable and inescapable.
</p>

<p>
How do you react to that?  Maybe it seems like one long screed of unremitting darkness. Perhaps reading this passage makes you think well whatever I'm going to read in the Bible I'm not going to read Ezekiel. Or maybe you think well that was the God of the Old Testament and that was the way that Ezekiel saw God - but today we know different. Were things really so bad then and are they so bad now?
</p>

<p>
But perhaps that is why Ezekiel is so insistent. Why he repeatedly presses the point home, because then and now the message of Gods holiness and the consequences of ignoring it is unpopular.  Jump ahead to Ch 13:10 and read of the prophets of the day who were leading Gods people astray by saying "Peace where there is no peace"  ie everything is fine don't worry it doesn't really matter.
</p>

<p>
To fail to warn people when a disaster is coming is a terrible thing. I come from Sheffield.  There are lots of deep valleys and up in these valleys above the city on the edge of the Pennines are reservoirs. In 1864 one of these reservoirs Dale Dyke collapsed and flooded the valley below killing 270 people.  Now suppose you knew the dam was unsafe and yet failed to warn people? That would be a terrible thing, or even worse - suppose you knew that the dam was unsafe and then someone asked you is it safe and you joked about it or even lied and said “of course it’s safe”. And then it failed, that would be an even more terrible thing. The judgement of God on sin is no joke.
</p>

<p>
So Ezekiel is not a gloomy depressive - he is man who knows and sees what is going to happen. So he warns the people. We need to be doing this too.  In Lye there are 9500 people.  At the most 500 of those go to church and probably have a real faith in God. That leaves 9000 who as far as I can see face the day of judgement without a saviour.
</p>

<p>
But is it really necessary? God is reasonable and so shows Ezekiel what is happening that makes his punishment of sin so necessary.
<p>

<p>
<h4>
Who Why Where?  Chapter  8
</h4>
</p>

<p>
In chapter 8 we see Ezekiel has another vision. See verse 3 in it he is taken to Jerusalem and given a guided tour of the temple.  Now a few months ago some PCC members went on a guided tour of the Cathedral at Worcester. I think one thing it said before hand was that we would see bits not normally seen by the public.  Whatever they saw I doubt they saw anything as sensational or shocking as Ezekiel saw here.
</p>

<p>
<b>
1)
</b>
Blatant idol worship, verse 5 right at the very front door is a statue of another God.  Described as the idol of Jealousy, ie it provokes jealousy. Jealousy is usually a bad thing - but there is in some circumstances there is  a right jealousy.  The most common human’s e.g is in marriage. There is something about a man and woman’s relationship in marriage that is rightly exclusive, and if that boundary is crossed then jealousy is right.
</p>

<p>
God calls his people to an exclusive spiritual relationship, and he is rightly angry and jealous if he finds us worshipping other gods.
</p>

<p>
Human jealousy sometimes comes with bitterness and unforgiveness. But God is jealous so that we might come to repentance and know forgiveness.  Human jealousy often wants to control and only thinks of itself.  Gods jealousy is his passionate desire to preserve something supremely precious - our relationship with him.
</p>

<p>
This Idol provokes jealousy. Now idolatry is subtle. These people probably hadn't thrown God out, no they were still using his temple and invoking his name in prayer and probably making sacrifices.  But they introduced something else alongside God. Today the people doing this would present themselves as at the cutting edge of theology, as being tolerant of other faiths, and anyone one who opposed as narrow minded bigoted and dangerous.
</p>

<p>
But no one is on a par with God. No one is his equal. By God I mean God who has revealed himself through Jesus Christ, who is Father Son and Holy Spirit.  That is logical, If God is almighty and all powerful and is the only real God then it would be grossly dishonouring to put something else alongside him. God would be right to be angry.
</p>

<p>
Sometime in the next 5-10 yrs we will probably have coronation.  It very likely that it will involve the worship and prayers and scriptures of other gods. If that happens it is a breaking of the very first commandment because it would be in danger of equating the true God with other deities.
</p>

<p>
<b>
2)
</b>
Secret Idol worship. In verse 8 Ezekiel in his vision digs a hole in the wall of the temple, and inside he finds walls covered with all kinds of animals that the Israelites regarded as unclean. Ezekiel’s entrance is through the wall rather than the door because what is happening is in secret. In secret implies it is deeper and a much more serious departure from the true God.  Here we have not just a statue that you can choose to bow to as you come into the temple but rather active worship. And even worse as we see verse 11 it’s the leaders of Israel who are worshipping these idols.
</p>

<p>
Perhaps in public they have commitment to God in some form, but in private they are far from him. They are adding hypocrisy to the sin of idolatry. Their religion is a sham. We see in v11 Jaazaniah son of Shaphan came from a very respectable family. If you look in 2 Kings 22-23 and see his father was the secretary to King Josiah. He had taken a leading role in the reformation and return to God that happened in Josiah’s reign. But despite that spiritual heritage Shaphan son of Jaazaniah was far far from God.
</p>

<p>
With God as with shares in the stock market past performance is no guarantee of future growth. Having a Christian heritage individually or nationally is no guarantee that a particular person will follow God.  No one becomes a Christian by birth alone. No one is Christian because they are British. Every generation needs to hear the gospel afresh.  Every individual needs to personally respond Gods truth at some point in their life.
</p>

<p>
The elders of Israel here worship in darkness v 12.  They imagine that God doesn't know and that he is no longer bothered, the idea that God doesn't know is a great lie that leads to so many sins.  We live every moment in the presence of God.
<p>

<p>
<b>
3)
</b>
Then in v 14 there are the women of Israel.  They are mourning for Tammuz.  Tammuz was probably a God of the near east. A fertility god who was believed to die every spring. People would mourn the god’s death and by doing so and offering sacrifices the god would come back to life - and in doing so come back to life to bring life to the crops etc. Ie they are worshipping a dead god but our God is alive.
</p>

<p>
God in the Old Testament is often referred to as the living God - because he does things - eg rescuing the Israelites from slavery in Egypt. The worship involved in is a complete negation of all that God is.
</p>

<p>
<b>
4)
</b>
Finally we come to the inner court verse 16 ie the innermost courtyard of the temple.   Here are 25 men engaged in worship. Not bowing down towards God but looking away from the temple towards the rising Sun. How foolish - worshipping the Sun when you could worship the one who made the Sun. I ask you which is the greater?
</p>

<p>
Conclusion
</p>

<p>
To end with two things to think about.
</p>

<p>
<b>
1)
</b>
For us think about for ourselves.  God has no rivals. He will not share his throne with anyone else. All the idols in this vision have statues, and are specific gods. Maybe because of that we fail to see idols nearer to home.
</p>

<p>
A Greek philosopher called Xenophanes writing in the 5th century said of the contemporary Greek Gods that they were all man made and that people worshipped themselves.
</p>

<p>
He wrote this:
</p>

<p>
The Ethiopians say that their gods are flat-nosed and black.
<br />
While the Thracians say that theirs have blue eyes and red hair.
<br />
If cattle or horses or lions had hands and could draw,
<br />
And could sculpt like men, then the horses would draw their gods
<br />
Like horses, and cattle like cattle; and each they would shape
<br />
Bodies of gods in the likeness, each kind, of their own.
</p>
</p>

<p>
In the heart of all of us there is a tendency to self worship. In our age of great physical comfort one god we have is that of individual personal peace and comfort.   But the Christian symbol is that of the cross and so we are called to service, suffering and sacrifice, for the sake of the Gospel we must be ready to be inconvenienced, frustrated and overlooked.
</p>

<p>
<b>
2)
</b>
Application to others.  When we hear of people worshipping idols we must remember  some idols are very concrete. At this hour 100's of people in Lye are offering sacrifices of water and soap to metal gods with 4 wheels, or to their garden or golf course or fishing lake. When we hear of peoples lives revolving around these things then we think well that’s inappropriate or sad or foolish. True.
</p>

<p>
But why are they that way? Why are they ignorant? 50% are ignorant because they have chosen to be. They have shut their minds to God. But 50% are ignorant because they have never had the chance to decide for themselves.  There is a generation who has grown up in this country who have never heard the Gospel and whose parents never heard it either.  We are made to worship, and if people do not know about the true God they will find something to fill the space.
</p>

<p>
I have been recently going around Rufford Estate.  We have done a little bit of evangelism here but have only scratched the surface. Stambermill church has been closed for 20 years. There is no other church there and never has been. In this area there is a surprisingly large number of people involved in alternative religious cults. If people give up on God and they don't believe in nothing, they believe in anything.
</p>

<p>
How can it change? It can only change if someone tells them. That applies everywhere.  If we believe this passage and take it seriously one thing it should make us do above all is to share the Gospel. To tell people there is a problem, that God hates sin and face his judgement. God called Ezekiel to be a watchman. And he has called us too.  Will you do that?
</p>

<p>
Simon Falshaw Christ Church Lye June 2009
</p>





<p>
<?php
	backToSermonsTalksPage();
?>
</p>


<!-- ========================================================================== -->
<!--                              End Text Section                              -->
<!-- ========================================================================== -->
</div>


<!-- ========================================================================== -->
<!--                          Start Footer Content Section                      -->
<!-- ========================================================================== -->
<?php
	include('footer.php');
?>
<!-- ========================================================================== -->
<!--                            End Footer Content Section                      -->
<!-- ========================================================================== -->


<!-- ========================================================================== -->
<!--                            End of CSS Layout                               -->
<!-- ========================================================================== -->
</div>  <!-- END <div id="maincontainer"> -->


</body>
</html>

