<?php
	/******************************
		Talk to MySQL
	**********************************/
	require_once("mysql.php");


	/******************************
		Start a session
	**********************************/
	require_once("session.php");
	$oSession = new session();
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 14/01/2005 -->
<head>
<title></title>
<?php
	require_once("nocache.php");	// Stop - hopefully - this page being cached
?>

<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta name="description" content="">
<meta name="keywords" content="">
<meta name="author" content="newey499@hotmail.com">
<meta name="generator" content="AceHTML 5 Freeware">


  <!-- CSS Includes -->
  <link rel="stylesheet" type="text/css" href="css/layout.css" >
  <link rel="stylesheet" type="text/css" href="css/church.css" >
  <link rel="stylesheet" type="text/css" href="css/slideshow.css" >
  <link rel="stylesheet" type="text/css" href="css/tooltip.css" >
  <link rel="stylesheet" type="text/css" media="print" href="css/print.css" >
  <link rel="stylesheet" type="text/css" href="css/cssdropdownmenu.css" />
  <!-- End CSS Includes -->

</head>
<body>

<?php
	require_once("mysql.php");
	require_once("globals.php");
	require_once("genlib.php");
?>

<!-- ========================================================================== -->
<!--                            Start of CSS Layout                             -->
<!-- ========================================================================== -->
<div id="maincontainer">

<!-- ========================================================================== -->
<!--                             Start Top Section                              -->
<!-- ========================================================================== -->
<div id="topsection">
<div class="innertube">

<!-- Top Banner for site -->
<?php
	include_once("topbanner.php");
?>

</div>  <!-- End <div class="innertube"> -->
</div>  <!-- End <div id="topsection"> -->

<!-- This extra pointless div is needed to get IE out of the crap -->
<!-- Without it the top banner is not displayed                   -->
<!--[if IE ]>
	<div>
	</div>
<![endif]-->


<!-- ========================================================================== -->
<!--                               End Top Section                              -->
<!-- ========================================================================== -->



<!-- ========================================================================== -->
<!--                              Start Text Section                            -->
<!-- ========================================================================== -->
<div style="margin-left:2em; margin-right:2em;">

<p>
<?php
	backToSermonsTalksPage();
?>
</p>





<br />


<h4>Why Bother Thinking? I Just Believe</h4>

<p>
"And why not! No one can give 100% proof of  the existence of God or any other item of Christain faith. Isn't it therefore enough just to believe? "
</p>

<p>
It may be that you think this way.  However if you do it is not a Christain way of thinking, nor an effective way of passing on your faith to others, nor is away to help you grow in faith. As with many statemnets the above is a half truth. There is no 100% proof for faith - but then neither is there for anything that we believe and act on in faith.
</p>

<p>
When I get on a bus or train or plane I trust that the driver or pilot knows how to drive and will do so well. I trust that the science that makes these thngs work will continue to work. I trust ut even when I don't understand it.  I trust that the engineers who have serviced the machines will have done so properly.
</p>

<p>
All knowledge in every area of existence is based on faith - though some might use the less religious term,  "trust"/   However Christian faith is not blind faith.  It is not a leap into the dark.  We believe because people, the Apostles,   have seen and pased on what they saw and heard about Jesus.  (Look at 1 Cor 15:3-8).  Our faith is about God doing things in human history and as such it is open to debate and reasoned argument.  As such it can also be defended this way.   There are increasing media attacks on the Christain faith  and rarely any clear Christain response at the same public level.    I  think these have along term affect at discrediting the truth of the Gospel.
</p>

<p>
However such a situation is nothing new. the early church lived in a confusing multireligious age full of rumour - and yet it thrived and grew. Peter wrote to the Christains living in the pagan culture of modern day Turkey with this advice "allways be prepared to give an answer to everybody who asks you to give  the reason for the hope that you have" 1 Peter 3:15.
</p>

<p>
Over the next year I want to use the monthly notice sheet to look at some of historical and factual basis for what we read in the Bible, particularly in the New Testament.
</p.




<p>
<?php
	backToSermonsTalksPage();
?>
</p>


<!-- ========================================================================== -->
<!--                              End Text Section                              -->
<!-- ========================================================================== -->
</div>


<!-- ========================================================================== -->
<!--                          Start Footer Content Section                      -->
<!-- ========================================================================== -->
<?php
	include('footer.php');
?>
<!-- ========================================================================== -->
<!--                            End Footer Content Section                      -->
<!-- ========================================================================== -->


<!-- ========================================================================== -->
<!--                            End of CSS Layout                               -->
<!-- ========================================================================== -->
</div>  <!-- END <div id="maincontainer"> -->


</body>
</html>

