<?php
	/******************************
		Talk to MySQL
	**********************************/
	require_once("mysql.php");


	/******************************
		Start a session
	**********************************/
	require_once("session.php");
	$oSession = new session();
?>
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 14/01/2005 -->
<head>
<title></title>
<?php
	require_once("nocache.php");	// Stop - hopefully - this page being cached
?>

<meta name="description" content="">
<meta name="keywords" content="">
<meta name="author" content="newey499@hotmail.com">
<meta name="generator" content="AceHTML 5 Freeware">

  <!-- CSS Includes -->
  <link rel="stylesheet" type="text/css" href="css/layout.css" >
  <link rel="stylesheet" type="text/css" href="css/church.css" >
  <link rel="stylesheet" type="text/css" href="css/slideshow.css" >
  <link rel="stylesheet" type="text/css" href="css/tooltip.css" >
  <link rel="stylesheet" type="text/css" media="print" href="css/print.css" >
  <link rel="stylesheet" type="text/css" href="css/cssdropdownmenu.css" />
  <!-- End CSS Includes -->


</head>
<body>

<?php
	require_once("mysql.php");
	require_once("globals.php");
	require_once("genlib.php");
?>

<!-- ========================================================================== -->
<!--                            Start of CSS Layout                             -->
<!-- ========================================================================== -->
<div id="maincontainer">


<!-- Top Banner for site -->
<?php
	include_once("topbanner.php");
?>



<p>
<?php
	backToSermonsTalksPage();
?>
</p>

<p>
<h4>
What would Jesus say to a Vicar?
</h4>
<br />
<b>
John 3: 1-21
<br />
A Sermon preached by Rev Simon Falshaw
at Christ Church Lye, June 2003
</b>
</p>


<p>
<b>
Introduction
</b>
</br />
It is 10 yrs since I was ordained this summer.  Lots of things have happened. In those times I have seen and heard some most unusual things.  Did you know Vicars have a legal right to park on double yellow lines? Not sure if that's true and I have never tested it but I was once told it by someone who was convinced it was true.  Misunderstandings can be funny. Let me tell you a story. A man called at the back door of a large house, and asked "Can I do any odd jobs for you?" . The house owner replied "Well yes actually. You can paint the  paint the porch at the front of the house" . The odd job man came back a bit later to be paid and said "By the way it wasn't a Porsche it was a Mercedes". Mistakes funny mistakes are also very costly.  Look at tonight a religious man came to Jesus, he made a major and very serious mistake about who himself and God.
</p>

<p>
In John chapter 3 we have a record of an encounter between Jesus and a man called Nicodemus.He was a religious leader, a member of the Jewish Ruling Council, the Sanhedrin. He was a sort of first century equivalent of Vicar or a Bishop.   What does Jesus say to him? What might he say today to a vicar?
<br />
Three things from that story that stand out
</p>

<p>
<b>
1)  You must be Born Again verse 3
</b>
<br />
Nicodemus has come to Jesus at night, perhaps he is frightened of being publicly  committed to him and is worried - "What will my Rabbi friends say if they know that I have been to see Jesus?  Will mock me , laugh at me or maybe will i loose my job?".
</p>

<p>
When people are frightened they often resort to flattery, afraid to speak the truth or of being themselves,  for fear of rejection.  Nicodemas  says to Jesus "Rabbi we know you are a teacher who has come from God."
</p>

<p>
But Jesus sees through this, and doesn't let it go to his head, and speaks straight to him. He is blunt because he loves him. And he says "I tell you the truth no one can see the kingdom of God unless he is born again".
</p>

<p>
What is it to be born again? First let me says what it is not.  Someone asked a vicar "Are you one of those born again Christians?"  Implying Born Again = a certain sort of Christian. Sometimes people misunderstand what a born again Christian is and associate it with a certain type of conversion, particularly a dramatic sort. It is the sort thing that happens to people who go foward at a large meeting like a Billy Graham rally. It is for  some people but definitely not for me. Speaking personally that is not the way I became a Christian. But I would call myself a born again Christian. As far as I can see from the Bible only sort of Christian is a born again Christian. For if what Jesus says here is true - only those who have been born again will see the Kingdom of Heaven.
</p>

<p>
Look at what it actually is. The kingdom of God is Gods rule. It is saying in our hearts that Jesus is in charge. It is a  change of ownership, a change of who is the boss.  That can happen to anyone it all sorts of ways. It begins in our lives when we are converted.  His rule is not complete  now but reaches fulfilment in heaven.
</p>

<p>
But how did that rule happen. It happens when we are born again. It seems a strange experience and Nicodemus doesn't understand it. For once you are born  you can't go into a mothers womb and come out again.  It's absurd.
</p>

<p>
The new birth Jesus talking about is not physical but spiritual. God does it through the Holy Spirit and gives us new spiritual life.
</p>

<p>
Being born again is not turning over a new leaf.  It is not just what happens when  someone realises their depth of Sin, and feels themself to have failed in some way and resolves to start again. Ie. when you draw a line in the sand and step over it and resolve never to go back into drugs, drink, pornography, gambling, addictive shopping or something that's been controlling them ever again.  That is part of what being born again means but it is much more radica  than that.  The word born again can also be translated as born from above (see footnotes in NIV). It happens above all from God. We can never make ourselves right with God.
</p>

<p>
As teenager that's what I understood Christianity to be. I thought it was just a choice to live a good life, to live the right way. But I came to realise, and not at one point in time but over a period of several years, that it was not by my efforts but by Gods gift that I had been born again.
</p>

<p>
For some being born again might be a distinct one off event. For others (and in my case) it happened over a period of time. Could I put it this way, you don't need to remember the day of your birth to know that you are alive.
</p>

<p>
And everyone needs this. Yes even vicars. For the story of Nicodemus reminds us there is sad possibility that there are people who are sometimes in positions of leadership in church who have not actually been converted.
</p>

<p>
<b>
2) You Know Less than you Think  verse 10
</b>
<br />
Nicodemus is still no clearer and so he says to Jesus "How can this be?"  verse 9  And Jesus replies - "You are Israel's  teacher and you still do not understand these things?"  Ie. How can you teach others anything about God if you don't even understand the basics. It is humbling to realise how little we know sometimes. One thing I have found by studying is that the more I study more unanswered questions that I have. The more I know the less I know.
</p>

<p>
Probably Nicodemus doesn't understand who Jesus is and why he came. Jesus  uses an Old Testament story (verse 14) to  explain why. Jesus gives explanations that Nicodemus as a Pharisee should grasp based on an Old Testament incident Numbers 21:1-4. The Israelites are being bitten by plague of snakes, as a result of a deliberate and purposeful rejection of God. They deserved what they were getting. Paralysed by snake bites and dying there was nothing they could do. But God in his kindness provided a way out. That was simply look at something God had provided, a bronze snake on a pole. They just looked.
</p>

<p>
That is a picture of faith. One of first thing a child learns is simply to look, to turn eyes and head and focus. And one of first things they are able to recognise is a face especially that of the parent. They look at what they trust.
</p>

<p>
The spiritual state of someone w/o God is like those who are dying of snake bite so paralysed that all they could do is simply turn their eyes and look and trust. Saying Nicodemus all you need to do to be born again is to look to God and say God I can't save myself but you can.
</p>

<p>
Religious people live in a dangerous situation. We are so surrounded by religious trappings, services robes, special customs, special language, titles like Reverend, Venerable, Bishop etc, that we can fool ourselves into thinking that just having the human signs themselves make us Christians.  It is possible to know a lot and do a great deal and yet totally miss out on eternal life.
</p>

<p>
And what is the central point they miss out on? The cross saves. I was once told by another vicar "you speak about the cross too much". But this is the centre of Christainity. One can not be a faithful minister of Jesus and not talk about it a great deal.
</p>

<p>
The cross is Gods greatest revelation to us. It is Gods final word to us. And people sometimes don't like it because it undermines and humbles all human forms of religion. It says they are useless and no good. You cannot save yourself. You must be born again. The temptation of a vicar is the temptation to think it means being nice to people and never offend anyone. In another parish once had a funeral. It turned out man they were burying had been a member of a syncretistic quasi-religious organisation. The organisers desired me to pray certain prayers as part of the service.  I read the prayers and in one way they were OK, but something was missing. There was no mention whatsoever of Jesus. He said I am a Christian. If Christians pray through Jesus these aren't Christian prayers. That set the cat among the pigeons. Because I was saying this is a man made faith it attempts to reach God by our own means.
</p>

<p>
Now we mustn't give unecessary offence or be rude or offensive. But the Gospel will offend. We are saying Jesus is the only Saviour, for we are all sinners and have failed God. It undermines all human pride and self confidence. What would Jesus say a Vicar? If the cross is not central in your ministry you have understood nothing.
</p>

<p>
<b>
3) Have an Eternal Perspective verse 16
</b>
<br />
Why did Jesus come? To give us eternal life.  God sent him on a rescue mission verse 17 "He did not send his Son into the world to condemn the world but to save the world through him". Jesus takes Nicodemus out of his narrow view and says to him "think eternal".  "Here you are visiting me at night, stop thinking about what the other Jews will say. Stop  worrying about your status and self importance.  God has come to save you from bondage to these silly things."   How often religious people, especially clergy get bogged down in unimportant things. Eg. last year I sat in a long discussion on what sort of robes you wear when different lay people take services. What really matters is not what we wear but who we are and what we preach. Are we preaching a message that will enbale people to be born again. Let's think eternal
</p>

<p>
This is something not just for the vicar but all Christians. When you see your friends, people we work with, people in your family who don't know Jesus, what do you think? Oh what a pity? Or do we get on our knees and say Lord save them? For without Christ they have no future. Of course we think in human terms, well they have a job, a good job, they are happy, they have somewhere to live etc, they have a future.  No we must think beyond that.  God sent his son into the world to save the world, not just now but for eternity. In the Bible there are only two destinations for people, eternal life with Christ or eternal separation from God, and all that is good ie Hell. Do we believe it? Do we think eternally? If so we will think, pray, be encouraged to speak and to point people to Jesus with all that we are.  Think eternally.
</p>

<p>
For Jesus came on a rescue mission - and he gives a warning to those who reject his call, verse 18 "Whoever does not believe stands condemned already because he has not believed in the name of Gods only Son."  If you reject Gods offer of being born again you must face the consequences- eternal separation from God forever. And that applies to everyone - yes even those who humanely might seem to have a hotline to God, those who humanely might seem to know best. They need to be born again.
</p>

<p>
What would Jesus say to a vicar? You must be born again. If you don't put the cross at the centre of your life you understand nothing, and finally have an eternal perspective.
</p>


<p>
<?php
	backToSermonsTalksPage();
?>
</p>


</div> <!-- End div  id="maincontainer"> -->
<!-- ========================================================================== -->
<!--                            End of CSS Layout                               -->
<!-- ========================================================================== -->


</body>
</html>
