<?php
	/******************************
		Talk to MySQL
	**********************************/
	require_once("mysql.php");


	/******************************
		Start a session
	**********************************/
	require_once("session.php");
	$oSession = new session();
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 14/01/2005 -->
<head>
<title></title>
<?php
	require_once("nocache.php");	// Stop - hopefully - this page being cached
?>

<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta name="description" content="">
<meta name="keywords" content="">
<meta name="author" content="newey499@hotmail.com">
<meta name="generator" content="AceHTML 5 Freeware">


  <!-- CSS Includes -->
  <link rel="stylesheet" type="text/css" href="css/layout.css" >
  <link rel="stylesheet" type="text/css" href="css/church.css" >
  <link rel="stylesheet" type="text/css" href="css/slideshow.css" >
  <link rel="stylesheet" type="text/css" href="css/tooltip.css" >
  <link rel="stylesheet" type="text/css" media="print" href="css/print.css" >
  <link rel="stylesheet" type="text/css" href="css/cssdropdownmenu.css" />
  <!-- End CSS Includes -->

</head>
<body>

<?php
	require_once("mysql.php");
	require_once("globals.php");
	require_once("genlib.php");
?>

<!-- ========================================================================== -->
<!--                            Start of CSS Layout                             -->
<!-- ========================================================================== -->
<div id="maincontainer">

<!-- ========================================================================== -->
<!--                             Start Top Section                              -->
<!-- ========================================================================== -->
<div id="topsection">
<div class="innertube">

<!-- Top Banner for site -->
<?php
	include_once("topbanner.php");
?>

</div>  <!-- End <div class="innertube"> -->
</div>  <!-- End <div id="topsection"> -->

<!-- This extra pointless div is needed to get IE out of the crap -->
<!-- Without it the top banner is not displayed                   -->
<!--[if IE ]>
	<div>
	</div>
<![endif]-->


<!-- ========================================================================== -->
<!--                               End Top Section                              -->
<!-- ========================================================================== -->



<!-- ========================================================================== -->
<!--                              Start Text Section                            -->
<!-- ========================================================================== -->
<div style="margin-left:2em; margin-right:2em;">

<p>
<?php
	backToSermonsTalksPage();
?>
</p>





<p>
  <b>The Da Vinci Code - The Real Jesus</b>
</p>


<p>
 <b>Who is Jesus?</b>
</p>

<p>
The issue of who Jesus really is  perhaps the most
contentious of many ideas raised in the book The Da
Vinci Code. According to Dan Brown Jesus was just
another man and happy to remain that way. He remained
so until  the Roman Emperor Constantine looking for a
political force to unite the Empire,  saw that
Christianity was on the rise and  decided to back it
as a uniting force. It suited his purpose to endorse
Jesus as the Son of God and so at the Council  Nicea
in 325 AD Jesus was proclaimed to be the Son of God.
</p>

<p>
Actually Christians believed that Jesus was God for
long before that,  from the earliest stages of the
Church. The reason being  simply that Jesus had shown
himself to be the Son of God.. It certainly wasn't
politically expedient because the fact caused the
early Church a lot of trouble. The early Christians by
claiming that Jesus was Lord, were implying that
Caesar did not deserve their ultimate loyalty, and
came under suspicion of treason.
</p>

<p>
The reasons the early Christians had come to this
conclusion was because it reflected what they had
experienced themselves, and later had seen and read of
Jesus in the Gospels. The Council of Nicea was useful
and important since it put into a concise form what
the people already believed about Jesus. The evidence
of the council was so clear that only about two
Bishops out of three hundred voted against this
decision
</p>

<p>
The view that Jesus is not God is not new. You may or
may not be going to see the film about the book but
Jehovah's Witnesses, Mormons, Muslims, and
Christadelphians are all united in believing that
Jesus was not divine.
</p>

<p>
Dan Brown in the Da Vinci Code also has an alternative
view of Jesus.  He was not divine, he married Mary
Magdalene, she had children and his bloodline
continues to this to this day.   The original goddess
worship which Jesus pursued with Mary Magdalene has
been surpressed and is only known by the faithful few.
</p>

<p>
 <b>Mary Magdalene</b>
</p>

<p>
In Dan Browns theory the identity of Mary is very much
tied in with the real identity of Jesus.  However
although much has been written about Mary we actually
know very little about her. Luke 8:2 records here as
one of the female followers of Jesus, out of whom he
had cast seven evil spirits.  She appears gain at the
crucifixion and resurrection.  She was clearly a close
and devoted follower of Jesus. After the resurrection
she disapears from the Gospel accounts.  This is not
surprising.  Many characters in the Gospels narrative
(e.g Nicodemas, Thomas, Jesus Mother,  Bartholomew,
Joseph of Arimathea)  are never heard of again after
the resurrection or Pentecost.  The writers focus is
Jesus.
</p>

<p>
Sometimes people have assumed that the sinful woman
who anoints Jesus in the previous passage  (Lk7)  is
Mary.  However this is unlikely. If it was Mary why
doesn't Jesus introduce her as such?  In addition why
is she introduced in the next chapter (Lk 8:2) as if
we have never met her?  The confusion of these two
women dates from the mistake of a 7th century Pope.
dan Brown rightly corrects it.
</p>

<p>
 <b>Did Jesus Get Married?</b>
</p>

<p>
There is no mention, not hint of Jesus getting married
in the Gospels. If it had happened it would have been
a significant event and would have been recorded.
</p>

<p>
Practically and morally it is very unlikely that Jesus
would have married.  He knew that his work would lead
him to an early death. It would hardly have been right
to have married knowing that he would soon  leave
behind a widow and children.  Whilst it was the norm
in Judaism to marry, it was not unknown for Jewish
leaders to be unmarried.  Examples include the
Jeremiah in the Old Testament and Paul in the New
Testament. Both had very dangerous and unsettled
callings that might have precluded marriage.
</p>

<p>
In addition if we look in the writings of the early
church, no one in the first four centuries suggests
Jesus marrying Mary Magdalene.
</p>

<p>
Dan Brown quotes two late non canonical Gospels as
supporting  The idea of Jesus marriage.  The Gospel of
Philip    The Gospel of Mary Magdalene
</p>

<p>
This is not surprising since the sort of world view of
the Gnostics (probable authors of many alternative
Gospels was extremely anti-women  and anti-sex.  They
tended to believe that the physical world was a
hindrance to true spiritual enlightenment.
</p>

<p>
Here is the view from one alternative Gospel, the
Gospel of Thomas  "Simon Peter said to them, "Let Mary
leave us for women are not worthy of life". Jesus said
"I myself will lead her in order to make her a male,
so that she too may become a living spirit resembling
you males. For every woman who will make herself male
will enter the kingdom of God." .  To be radical means
to go back to the roots. I suppose that this is then a
sort of stone age radicalism.
</p>

<p>
Jesus lived in an age that was sexist and
discriminatory, but in contrast to the spirit of his
age he treated women with respect and dignity.
</p>

<p>
The place to find out about the real Jesus is from the
four Gospels.  These are reliable historical documents
and give us the best picture available of Jesus of
Nazareth.
</p>

<p>
Jesus encountered a wide variety of people. In Luke
7:36-50  we read of a dinner party encounter with
religious leaders and an outcast woman. Through the
lens of this short encounter we can gain some insight
into the sort of man he was.
</p>

<p>
 <b>Jesus - the man who mixes with everyone</b>
</p>

<p>
Jesus is eating with a  Pharisee. These were keen
religious lay people. They knew the scriptures well
and were keen to live according to what they believed
they taught.  They had strong convictions about what
was right and wrong,  and as a consequence their own
righteousness.  Suddenly in the midst of this very
upright gathering appears a very different sort of
person. a woman who Luke describes as having led a
sinful life.  This phrase together with the fact that
her hair is loose strongly suggests that she was a
prostitute.  Without  has led a sinful life.  guests
look on and in their hearts condemn the woman.
</p>

<p>
Perhaps she feels a sense of self condemnation and
disgust about herself.  Maybe she feels trapped by her
past. Everyone looks down on her, gossips about her
and abuses her. And yet in Jesus she has seen someone
who is different He treats her with dignity and as a
fellow human being.
</p>

<p>
So in a combination of desperation and gratitude she
starts weeping, so much that the warm salty drops
splash on Jesus feet. She then falls down and begins
wiping his feet with her hair. To clean the feet of a
guest was an a normal act of hospitality.  she goes
further than this pouring perfume on his fee to
complete the job.   Perfume is rarely cheap. It is
possible that this perfume was a tool of her trade or
bought with the proceeds of her work.
</p>

<p>
Early in his ministry Jesus had been accused of mixing
with the wrong sort of people.  His reply was "It is
not the healthy who need a doctor, but the sick...I
have not come to call the righteous but sinners." (Mk
2:17).  That includes both Pharisees and prostitutes.
He was man who mixed with everyone.
</p>

<p>
 <b>Jesus  the Man who breaks down religious barriers.</b>
</p>

<p>
See how the Pharisee reacts to Jesus. He thinks here
is a notorious prostitute draping herself all over his
feet and so he concludes in "if this man were a
prophet he would know kind of woman was touching him
what kind of woman she is - that she is a sinner". He
is wrong on two counts. Firstly Jesus knows exactly
who this woman is. He knows all the wrong that she has
done and yet he still loves her. Secondly what counts
is not whether she touches him or not but whether he
cares for her or not. Holiness is not a matter of
outward forms but of the heart. Jesus breaks down the
accepted idea of what is to be religious. It is not
about ceremonies, or ritual washings, nor keeping
lots of difficult rules or doing the right things in
religious services. Jesus knows that what God looks at
is the heart.
</p>

<p>
Jesus is a wise teacher to you, we might think it was
the prostitute that had the problem but actually it
was as much  Simon the Pharisee, if not more.
</p>

<p>
Jesus could have just rebuked him but perhaps because
he was to proud or self righteous  he disarms his
defences by telling  a story. Two men owe some money.
One a few hundred pounds an overdraft at the Bank, the
other massive debts amounting to tens of thousands of
pounds. Incredibly the Bank writes off both debts. Who
would you expect to be more excited?  Simon answers v
43 "I suppose the one who had the bigger debt
cancelled". He had far more to be grateful.
</p>

<p>
Jesus' answer to Simon goes something like this -  you
wonder why this woman acts likes this? I tell you it
is because her sins have been forgiven. Where does all
this weeping, kissing my feet and all this expensive
perfume come from? Did you not just say when a debtor
has been forgiven a huge debt he feels great loving
gratitude to the one who has released the debt? This
women had a huge debt of sins. Look at her gratitude
towards me? "You said I suppose the one who had the
bigger debt cancelled". Isn't it by your own omission
evidence that she has indeed been forgiven! You see
the wisdom in Jesus teaching? He cuts through empty
religion. This story gets to the heart of the problem
between man and God, forgiveness and our response.
</p>

<p>
 <b>Jesus the one who forgives</b>
</p>

<p>
So here we have Jesus the one who accepts all who come
to him, who breaks through the sham of false religion
and was a wise teacher. He was one who had a radical
acceptance of women and including a women who had
broken all the taboos, went far beyond what anyone
else did in his day.
</p>

<p>
That's very good but if so why is there all this fuss
about the Da Vinci Code and it's view of Jesus? This
is exactly the view that the Da Vinci Code has of him.
One character in the book describes Jesus this way
"Jesus Christ was a historical figure of staggering
influence, perhaps the most enigmatic and
inspirational leader the world has ever known" (The Da
Vinci Code page 313)
</p>

<p>
I can think of other and inspiring people.  For
instance Mahatma Ghandi was a wise teacher accepted
all and in one sense he was a spiritual man deeply
concerned with seeking the sham of false religion. In
some ways someone like Nelson Mandela we see someone
passionately concerned for the truth. He is a wise man
whose concern to make his nation a place where
everyone, whatever the race had a place. And so we
might wonder is Jesus any different?
</p>

<p>
Look at the end of his encounter he turns to the women
he turns to the women who feels so deeply guilty and
says to her "your sins are forgiven". Note he does not
says your sins can be forgiven, or your sins might be
forgiven but they have been forgiven. Perhaps he is
referring back to a previous encounter she had with
Jesus. As he says this an absolute gasp of amazement
runs round the table as people realise the
implications of what he is claming. People say "who is
this who even forgives sins?" v 49.
</p>

<p>
We can only forgive a wrong if it has been against
ourselves. If I reverse my car into your car in a
parking space there is no point in me apologizing to a
passerby. Or if a Policeman was passing and he saw it
he could not say "Oh its only a little bit of paint it
doesn't matter I will let you off" he could not do
that because it was not his car that had been damaged
it had not been done to him. We can only forgive what
has been done to us. So how can Jesus forgive this
women her sin. He can only do that if it has done
against him implying that he is God.
</p>

<p>
 <b>Jesus and us</b>
</p>

<p>
When we encounter the person of Jesus in the New
Testament he is clearly a most remarkable person. He
makes the most astounding claims about himself such as
that he is the way to God, that a persons eternal
destiny depends on following him or not, but his
followers must love him more that anything else. And
when he makes claims like that the Jewish leaders
attempt to stone him because he blaspheming.
</p>

<p>
His followers make similar claims about  him. His
miracles support it and yet his care and concern for
all around make it clear that he is not mentally ill
nor an egomaniac. He works miracles and even rises
from the dead. Who then is this man? If Jesus was a
great religious leader as Dan Brown claims and perhaps
we could say that this may be a truth that works for
you but not for me and leave it at that. However if he
is God then he is Lord of all. For the sinful women it
meant sacrificing a bottle of expensive perfume and
for us it means laying our lives before him and saying
Jesus you are Lord.
</p>








<p>
<?php
	backToSermonsTalksPage();
?>
</p>


<!-- ========================================================================== -->
<!--                              End Text Section                              -->
<!-- ========================================================================== -->
</div>


<!-- ========================================================================== -->
<!--                          Start Footer Content Section                      -->
<!-- ========================================================================== -->
<?php
	include('footer.php');
?>
<!-- ========================================================================== -->
<!--                            End Footer Content Section                      -->
<!-- ========================================================================== -->


<!-- ========================================================================== -->
<!--                            End of CSS Layout                               -->
<!-- ========================================================================== -->
</div>  <!-- END <div id="maincontainer"> -->


</body>
</html>

