<?php
	/******************************
		Talk to MySQL
	**********************************/
	require_once("mysql.php");


	/******************************
		Start a session
	**********************************/
	require_once("session.php");
	$oSession = new session();
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 14/01/2005 -->
<head>
<title></title>
<?php
	require_once("nocache.php");	// Stop - hopefully - this page being cached
?>

<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta name="description" content="">
<meta name="keywords" content="">
<meta name="author" content="newey499@hotmail.com">
<meta name="generator" content="AceHTML 5 Freeware">

  <!-- CSS Includes -->
  <link rel="stylesheet" type="text/css" href="css/layout.css" >
  <link rel="stylesheet" type="text/css" href="css/church.css" >
  <link rel="stylesheet" type="text/css" href="css/slideshow.css" >
  <link rel="stylesheet" type="text/css" href="css/tooltip.css" >
  <link rel="stylesheet" type="text/css" media="print" href="css/print.css" >
  <link rel="stylesheet" type="text/css" href="css/cssdropdownmenu.css" />
  <!-- End CSS Includes -->

</head>
<body>

<?php
	require_once("mysql.php");
	require_once("globals.php");
	require_once("genlib.php");
?>

<!-- ========================================================================== -->
<!--                            Start of CSS Layout                             -->
<!-- ========================================================================== -->
<div id="maincontainer">

<!-- ========================================================================== -->
<!--                             Start Top Section                              -->
<!-- ========================================================================== -->
<div id="topsection">
<div class="innertube">

<!-- Top Banner for site -->
<?php
	include_once("topbanner.php");
?>

</div>  <!-- End <div class="innertube"> -->
</div>  <!-- End <div id="topsection"> -->

<!-- This extra pointless div is needed to get IE out of the crap -->
<!-- Without it the top banner is not displayed                   -->
<!--[if IE ]>
	<div>
	</div>
<![endif]-->


<!-- ========================================================================== -->
<!--                               End Top Section                              -->
<!-- ========================================================================== -->



<!-- ========================================================================== -->
<!--                              Start Text Section                            -->
<!-- ========================================================================== -->
<div style="margin-left:2em; margin-right:2em;">

<p>
<?php
	backToSermonsTalksPage();
?>
</p>






<h4>
What Would Jesus Say To A JEDI Knight?
</h4>
<b>
Matthew 16: 21-28
</b>
<br />
<b>
Sermon preached at Christ Church Lye - June 2003     by Reverend Simon Falshaw
</b>

<p>
The Star Wars series of films have been consistently popular. I can remember as a student going to see The Empire Strikes Back when it was first released. Myself and my friends thought it was so brilliant and because it was after exams and we had nothing else to do we all went back a  the following day seeing it a second time. The film has really captured people's imagination in a remarkably deep way. In 1999 when the first of the prequel cycle of films was released I read of people who had been waiting with religious intensity for the last twenty years for this film to be released. For them as a major religious experience.
</p>

<p>
In 2001 the UK Census had for the first time a question about religion. In response to this,  a campaign began on the internet for people to indicate their religion was Jedi. Jedi Knights are of course the religious/military order to which the main characters in the Star Wars series, such as Darth Vader, Luke Skywalker, and Obi wan Kenobi all belong. I don't know how seriously people really took this campaign but about 170,000 people signed up to say that they were Jedi.  Similar campaigns ran in Australia and New Zealand . For many people claiming to be Jedi was probably a way of saying "I couldn't care less about religion. It's all a load of nonsense". But there are some people who take Jedism really seriously. There is a core group of people to whom the idea of a impersonal force lying behind everything is used as a basis of reality in their lives. One may disagree with their beliefs but they are serious and should not be laughed at.
What I am saying tonight is not so much to them but generally to people who have watched and enjoyed Star Wars films over the years.
</p>

<p>
The question I want to ask tonight is what would Jesus say to a Jedi Knight? Or to put it another way what does the Bible say to the world view of Star Wars? Of course there are no Jedi's in the Bible but Jesus did call us to be seriously committed to an ideal. We can read about that in Matthews Gospel Chapter 16: 21 - 28. He  calls people to follow him and to actually lay down their lives to follow him. I want to look at the Star War stores through the lens of that passage. There is a great deal that one could say in response to 15 hours of films and so what I say here is limited to my personal reflections. No doubt there is a lot you could add to the discussion. So what would Jesus say to a Jedi Knight.?

</p>

<p>
<b>
Things Are Not What They Seem
</b>
<br />
A great theme of the second half of the Star War series is probably that of discovery. The original episode begins on an isolated desert planet with a young boy who discovers that his father was  a very great man,  a Jedi Knight with great skill and power. As the episodes develop he finds out the truth and that  things are not what they seem. The woman he has fallen in love with is his sister and  his great enemy Darth Vader is in fact his father. The three prequel episodes then piece together what happened before it all began.
</p>

<p>
In Stars Wars episode four there is a scene where the Empire is proudly discussing its latest weapons, a massive planet destroyer Death Star.  Darth Vader rebukes them "don't overestimate the power of this technology of terror. The power to destroy a Planet is insignificant to the power of "'the force'.".  However one of the generals is very sceptical and he comments "don't try to frighten us with your sorcerers ways Lord Vader. Your commitment and ancient religion has not helped us". However he does not get any further.   Darth Vader using "the force" looks at him and he starts choking and then the poor General collapses dead on the table. The question they are discussing is the one that we discuss  today. Is all that we can see and hear and touch with our fine senses all that there is? Or is there more? Is there some great unseen power in the Universe that dwarfs everything else.
</p>

<p>
So what would Jesus say to a Star Wars fan. If you have dismissed Christianity how well do you really know what you have decided to throw away? Have you looked at the original text yourself as a thinking adult?
The story of Jesus is a revelation. It is a story of things that are not clear that become clear. In the Gospels Jesus steps on the scene and gathers followers. Eventually he asks them "who do you think I am? Peter replies "you are the Christ Son of the Living God". It is an incredible revelation. He is saying that God's plans are summed up in me as a rescuer for the human race. As such he calls people to lay down their lives in unconditional commitment to him.
GOD IS MORE THAN A FORCE.
</p>

<p>
This is something else that Jesus might say to a Jedi Knight. That is this "God is more than a force". The Force in Star Wars is described as an energy field running through all matter. It has a good side and a dark side. Anakin Skywalker is trainee Jedi. The goal of his training is to master this impersonal energy, the Force. But he fails to master the Force and gives in to the dark side becoming Darth Vader.
</p>

<p>
The problem with God as an impersonal force is that it/he can be made to do what you want. It/He becomes a tool of human beings - not allmighty God creator of the universre. In a scene in episode one (The Phantom Menace) the young Obi Wan Kenobi is stranded on a planet and needs to repair Queen Amadala's spaceship. He has no money. He tries to obtain the required parts on credit by manipulating his voice with the force. In doing so he asks people to give him what he needs. He is fully aware that he has no intention or means of paying, it is a con. Yet he is one of the "goodies".   The problem with God as a force or a power in the end is that there is no ultimate right or wrong. In the end you don’t ask what is right but what works. Adolf Hitler made this comment about power and truth, "in staring and waging war it is not right that matters it is victory. They will not ask you if you told the truth but simply whether you won".
</p>

<p>
What Jesus calls his followers to is different. They are not called to relate to a power but to  a person. He says "if anyone will come after me he must deny himself and take up his cross and follow me". As a belief system this more accurately reflects what we are as human beings. To be human is not just obeying me, but  being me in relationship with others. We are made for relationship and friendship. And this is not just with each other but with God. We were made for God and are restless without him. We were called to know and experience a love of God. God cares for us and desires our best.
</p>

<p>
I wonder if in a way this desire for relationship has made Stars Wars attractive to many people. There are a wide variety of characters that we relate to. In it's simplest terms it is the story of a family finding itself again after tragedy.
</p>

<p>
<b>
Committment Is Costly
</b>
<br />

The training of a Jedi Knight is costly. In "The Empire Strikes Back" we see Luke Skywalker running endlessly round a swamp with a wrinkled prune called Yoda on his back. It is exhausting and tiring. In "The Attack of the Clones" Anakin Skywalker faces the challenge of being committed to his training. When his mother dies he fails to control his temper and massacres a village in his anger. When called not to marry but breaks his vow and marries. Commitment is costly.
Likewise the call to Christian discipleship is costly. Like the Jedi Knight it is a life of self denial but goes a step further in that it is also a life of self sacrifice. Jesus says "whoever wants to save his life or lose it but whoever loses his life for me will find it". Becoming a Christian is a total reorientation of life from self to God. It says that Jesus is the Lord, the Boss, the Governor, the one in charge of all that I am. In becoming Christian in the world today people will lose their jobs, are mocked, isolated, lose their homes, face families splitting up, are jailed imprisoned, even tortured and executed.
</p>

<p>
Why are people willing to suffer so much to follow Jesus? To follow Jesus or not to follow him is probably the most important decision anyone could ever make. It is a matter of life and death. If he really is Lord of the Universe it makes sense. To be a Jedi Knight is also costly. Within the world of the film if people opted out of being a Jedi there is no indication that it would make any difference to them. But to be a Christian or not to be a Christian is more than simply a lifestyle choice or choice of job. It is a matter of eternal life or eternal death. Let me ask you are you committed to something worth dying for?
</p>

<p>
<b>
We Win By Losing
</b>
<br />
Jesus came to die, die on the cross. In putting such a good and perfect man on the cross and seeing that evil had triumphed. But in doing so he paid the penalty for our sins and three days later he rose from the dead. In Star Wars most of the time the people win by superior skill or knowledge. They are simply better that their opponents. This is the case expect perhaps in the last film "Return of the Jedi". In the final scenes of the film Luke Skywalker is standing in front of the evil emperor and Darth Vader. The emperor wants to corrupt him and win him to the dark side of the force and enlist him on to his side. He is goaded in to giving in to his hatred and fights a dual with Darth Vader. Darth Vader looses but then Luke Skywalker throws away his weapon and refuses to do what the Emperor wishes. He is at his weakest and completely defenceless so the Emperor prepares to kill him. At that point Darth Vader realises where his true loyalties lie and
 he must do good. He picks up the Emperor and drops him down a convenient ventilation shaft. There is a big bang and you know that the film is nearly over. He wins in his weakness.
</p>

<p>
Similarly the way of Jesus's victory is a way that seems humanly weak, stupid and impossible. For what else can the deliberate and humiliating choice to be executed on a cross be seen as. It is described in 1 Corinthians as foolishness but the writer adds  "the foolishness of God is wiser than a man's wisdom, and the weakness of God is stronger than mans strength". It is not weakness that wins but Jesus death on the cross in our place for our sins. He died for the dark side in us and so offers eternal life.
</p>

<p>
<b>
The World Is Coming To An End
</b>
<br />
The very last scene of the last film seems very downbeat. There has been a great triumph and it ends with a party of some furry animals dancing round a fire watched by the ghosts of Yoda, Obi Wan Kenobi and Anakin Skywalker. For all the momentous events that have happened   there is no real sense of anything actually having changed. History will go on and in due course more evil people will arise.
</p>

<p>
In contrast history as Jesus sees it has a direction. Jesus will return and reward those who have faithfully followed him. As a result we can't just live for now. We have a choice to make will we follow Jesus or not. As in the film there was a choice of two ways so there is a choice of two ways before us now.
</p>

<p>
In the original Star Wars film we have Han Solo,  played by a very young Harrison Ford, a slightly dubious but likeable character who had conned and cheated not a few people on his journey through life. As the Republic fly off to do battle with the Death Star he face with the question will it be as a distant observer or will he fight? Does he really care for anyone or anything? Should he take his money and run before the Republic lose or should he give himself for others?
That in the end is the question that Jesus asks us all? Will we stand with him or will we drift without him?
</p>








<p>
<?php
	backToSermonsTalksPage();
?>
</p>


<!-- ========================================================================== -->
<!--                              End Text Section                              -->
<!-- ========================================================================== -->
</div>


<!-- ========================================================================== -->
<!--                          Start Footer Content Section                      -->
<!-- ========================================================================== -->
<?php
	include('footer.php');
?>
<!-- ========================================================================== -->
<!--                            End Footer Content Section                      -->
<!-- ========================================================================== -->


<!-- ========================================================================== -->
<!--                            End of CSS Layout                               -->
<!-- ========================================================================== -->
</div>  <!-- END <div id="maincontainer"> -->


</body>
</html>

