<?php
	/******************************
		Talk to MySQL
	**********************************/
	require_once("mysql.php");


	/******************************
		Start a session
	**********************************/
	require_once("session.php");
	$oSession = new session();
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 14/01/2005 -->
<head>
<title></title>
<?php
	require_once("nocache.php");	// Stop - hopefully - this page being cached
?>

<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta name="description" content="">
<meta name="keywords" content="">
<meta name="author" content="newey499@hotmail.com">
<meta name="generator" content="AceHTML 5 Freeware">


  <!-- CSS Includes -->
  <link rel="stylesheet" type="text/css" href="css/layout.css" >
  <link rel="stylesheet" type="text/css" href="css/church.css" >
  <link rel="stylesheet" type="text/css" href="css/slideshow.css" >
  <link rel="stylesheet" type="text/css" href="css/tooltip.css" >
  <link rel="stylesheet" type="text/css" media="print" href="css/print.css" >
  <link rel="stylesheet" type="text/css" href="css/cssdropdownmenu.css" />
  <!-- End CSS Includes -->

</head>
<body>

<?php
	require_once("mysql.php");
	require_once("globals.php");
	require_once("genlib.php");
?>

<!-- ========================================================================== -->
<!--                            Start of CSS Layout                             -->
<!-- ========================================================================== -->
<div id="maincontainer">

<!-- ========================================================================== -->
<!--                             Start Top Section                              -->
<!-- ========================================================================== -->
<div id="topsection">
<div class="innertube">

<!-- Top Banner for site -->
<?php
	include_once("topbanner.php");
?>

</div>  <!-- End <div class="innertube"> -->
</div>  <!-- End <div id="topsection"> -->

<!-- This extra pointless div is needed to get IE out of the crap -->
<!-- Without it the top banner is not displayed                   -->
<!--[if IE ]>
	<div>
	</div>
<![endif]-->


<!-- ========================================================================== -->
<!--                               End Top Section                              -->
<!-- ========================================================================== -->



<!-- ========================================================================== -->
<!--                              Start Text Section                            -->
<!-- ========================================================================== -->
<div style="margin-left:2em; margin-right:2em;">

<p>
<?php
	backToSermonsTalksPage();
?>
</p>


<p>
  <h4>Justified By Faith - Romans  4 </h4>
</p>


<p>
In 2006 a group of children travelled from Britain to
Germany to watch the World Cup. Unfortunately when
they got to the stadium they discovered their tickets
were forgeries and they couldn't get in. Tickets for
the match were hard to come by and only available at
high inflated prices. The key question for them and
for thousands of other people was how do I get in?
</p>

<p>
The question of entering God's presence is in a way the
question behind the Book of Romans. How do I get entry
into God's presence? Or to put it in more theological
words, as used in Romans how do I gain righteousness?
How am I justified before God?
</p>

<p>
Gaining entry into God's presence is a problem. For
God is holy that is he is morally perfect. There is
not one speck of wrong in him. God is holy but we are
not. He is righteous but we are not. If we look back
in the first three chapters of Romans we see why
Paul's diagnosis of the human situation makes sense.
There he shows how all mankind has turned it's back on
God and ignored him. He shows how we have chosen to go
our own way and consequently paid the price. We are
without excuse. It is not just the &quot;bad&quot; but all of us
who break God's law. This includes the religious and
the irreligious, the upright and the depraved are all
in the same boat. Paul sums up the situation in Romans
3 verse 23 with these words &quot;for all have sinned and
fallen short of the glory of God.&quot;
</p>

<p>
We affirm this diagnosis of our human situation when
we begin a service with a confession of sin. We also
witness to it in the baptism service. Here people
promise to reject the devil and all rebellion against
God, to renounce sin and the corruption of evil, and
repent of sins that separate us from God and
neighbour.
</p>

<p>
That is the human problem but what is the solution? It
is a question that must be answered. For a God made
the universe and controls space and time our peace and
ultimate well being depends on being with a right
relationship with him. We cannot know harmony if we
are out of sorts with the one who ordered the
universe. One day we must face God and his judgment.
At the end of Romans chapter 3, Paul in a nutshell
explains the solution. The Message version (a
contemporary translation) puts it this way &quot;since we
have complied this long and sorry record of sinners
(both us and them) and proved we were utterly
incapable of living the glorious lives God wills for
us, God did it for us. Out of sheer generosity he put
us in right standing with himself. A pure gift. He got
us out of the mess we were in and restored us to where
he always wanted us to be. And he did it by means of
Christ Jesus. God sacrificed Jesus on the altar of the
world to clear the world of sin.&quot;
</p>

<p>
The implications of this are very radical. It explains
the solution in terms of what God did and not in terms
of what we could do. It is saying that we can do
nothing, nothing at all to put ourselves right with
God. Our good works, morality or religion are a
complete and utter waste of time as far as being made
righteous with God is concerned. Note this is not
saying these things have no value at all, but as far
as putting us right with God they are no value. They
are of no value because God cannot ignore sin and God
owes us nothing. We have no claim on God for anything.
We cannot earn or buy our way back into his presence.
All this is a very humbling idea, for it means it is
only by God's action in Jesus Christ that we are made
righteous.
</p>

<p>
If this comes as a shock or offends our pride and
gives us questions it was also very much in the case
of the Jewish people in Paul's time. Having explained
it once Paul explains it again and he does so using an
example the Jewish people will understand. He writes
about Abraham the founding farther of the Jewish
people who lived about 2000BC at the very dawning of
recorded time.
</p>

<p>
Paul teaches out what righteousness by faith is
through Abraham's story. He does this specifically in
terms of three negatives, that righteousness by faith
means that it is not, not by circumcision,
not by law. As a result we are only made righteous
with God by Grace.
</p>

<p>
<b>
Not by Works - verses 1 - 8
</b>
<br />
<br />
We do not get right with God by our good works. As
good works this would include such things as being
generally a nice person, being the sort of person
which is good to know, being someone who is already to
do &quot;anything for anyone&quot;, or a good citizen or the
sort of person you would like to move into the house
of flat next door to you when it is empty. All these
are ways in which the express the idea of good works
in our culture.
</p>

<p>
In verse 2 we see Paul looking back at the life of
Abraham and his walk with God. If Abraham had been
made right with God by his works he would have had
something to boast about. However rather (verse 3) we
see that Abraham's righteousness was given to him as a
gift. If you work for someone at the end of the week
or the month you have a legal right to your wages. You
can be proud of your work. However rather (verse 3 and
verse 5) it says that his righteousness was credited
to him as a gift. Credited to him means something like
put on his account. It means that is not because of
his goodness but of his trust in God on what he has
specifically done through Jesus Christ that he was
declared righteous.
</p>

<p>
To drive the point home Paul gives another example
from the writing of Israel's greatest King, King
David. If we look in verses 7 to 8 he quotes a Psalm
about the wonder of God's forgiveness. But nowhere is
any mention of David being forgiven and received his
blessing because of anything he has done. When we
consider this it goes completely against the way our
world thinks. See verse 5 hear we read &quot;to the man who
does not work but trusts God who justifies the wicked,
his faith is credited as righteousness.&quot; It turns
everything we know upside down. Surely it is normally
the one who works who gets paid? Imagine if this
principle applied to the work place. How would it be
to run a company on this basis? Or what about the one
who works in such a place? Is it a charter for
laziness? It is saying come to work, do nothing, laze
around and play computer games and make endless phone
calls and then at the end of the month you get a fat
cheque to credit into your account. All for doing
nothing! If the work place were like that it would
both be wrong and unfair.
</p>

<p>
That is what is God has done in saving us. For there
is no other way we can be put right with God other
than by his totally undeserved gift.
</p>

<p>
<b>
Not by Circumcision verses 9 to 12
</b>
<br />
<br />
All adult male Jews were required to be circumcised.
It was a sign of belonging to God and a very important
sign at that. As with many signs in time it became so
important that it took on a life of it's own. A sign
of belonging became an end in itself which signaled
more national identity than specifically a spiritual
relationship with God.
</p>

<p>
The issue for people in Paul's day was circumcision.
For us it may be any outward religious sign. It
reminds us, the sign, be it baptism for adults or
infants or confirmation is only of value in the end if
there is faith with it.
</p>

<p>
When did Abraham declare God as righteous? If you look
in verses 9 and 10 we see that this blessing was not
after he had been circumcised but before. If you go
and look at the story of Abraham in Genesis 11 to 20
you can see how he trusted God with the promise of
having a son and then fourteen years later God
commanded him to be circumcised. As a result (verse
12) we see he is a spiritual father of both those who
have been circumcised and those who have not been
circumcised.
</p>

<p>
<b>
Not by Law verses 13 to 17
</b>
<br />
<br />
Here we see the third means of being made right with
God and inadequate. That is the Law. By this we mean
the keeping of God's commandments.
</p>

<p>
However such a way of being put right with God is not
incompatible with the idea of faith. The problem of
trying to be made right with God through law is that
we break God's law. Lest we think that's to big a deal
remember God looks into our heart, our thoughts, words
and deeds stand under his judgment. Since God is holy
he is rightly angry. And we se there the results
(verse 15) that God is wrathful i.e. he is righteously
angry.
</p>

<p>
So if God is angry how can we come into his presence?
The ways like the religious person, like to Jewish
person might have tried - good works, religion or keep
the Law fail. How do we get in? Well in exactly the
same way that Abraham got in. Abraham is a model for
all of us. In both verse 11 and 16 Paul has written
&quot;He is the Father of us all.&quot; He is the Father of both
the circumcised and the uncircumcised, those you think
they may have a special claim on God and those who
feel far from him. And the way in is not by human
effort but by faith in what God has done.
</p>

<p>
<b>
Only by Grace verses 18 to 22
</b>
<br />
<br />
When we look at the end of the passage in verse 18
towards the end, you see how Abraham was promised a
son. This seemed humanly impossible he and his wife
Sarai had no children and they were both well past the
normal age of having children. But Abraham trusted
God, that is he took God at his word his attitude was
God said it would be so and thus it will happen. That
provides a model for us today. The issue for us is not
having children,  but finding the forgiveness of sins
and being made right with God. How dos this happen?
Its by faith.
</p>

<p>
Let me explain what faith is a little bit more. Faith
as the Bible sees it is not simply believing in the
existence of God, for if that was the case we would
find the devil in heaven! After all the devil believes
that God exists but it doesn’t make any difference.
Nor is faith simply believing that God can do a lot;
that  God is strong; that he can heal etc. Jesus was
once speaking to the people who doubted said &quot;if you
have faith as small as a mustard seed you can say to
this mountain move from here and it will move.&quot;
(Matthew 17 verse 20). If that was the case we would
only find the optimist and the self confident in
heaven. There would be no room for the pessimist and
those who struggle with life and doubt easily.
This is what faith is - an active trust in God. Indeed
we say in the baptism service, not  simply I believe
in God, but I believe and trust in him. So you may
have a weak and wobbly faith that is full of doubts
but if you are prepared to trust God with your will
that is enough.
</p>

<p>
Let me read a bit from the Message version which sums
up what Abraham did &quot;when everything was hopeless
Abraham believed anyway deciding to live not on the
basis of what he saw he could not do but on what God
said he would do... He did not tiptoe around asking
God cautiously skeptical questions. He plunged
straight into the promise and came out strong ready
for God sure God would make good what he had said.&quot;
For Abraham this was the promise of a son. For us to
it is the promise of the Son - the Son of God. When we
believe that Jesus died in our place bearing our sins
and put our trust in him and repent of our sins we are
put right with God
</p>



<p>
<?php
	backToSermonsTalksPage();
?>
</p>


<!-- ========================================================================== -->
<!--                              End Text Section                              -->
<!-- ========================================================================== -->
</div>


<!-- ========================================================================== -->
<!--                          Start Footer Content Section                      -->
<!-- ========================================================================== -->
<?php
	include('footer.php');
?>
<!-- ========================================================================== -->
<!--                            End Footer Content Section                      -->
<!-- ========================================================================== -->


<!-- ========================================================================== -->
<!--                            End of CSS Layout                               -->
<!-- ========================================================================== -->
</div>  <!-- END <div id="maincontainer"> -->


</body>
</html>

