<?php
	/******************************
		Talk to MySQL
	**********************************/
	require_once("mysql.php");


	/******************************
		Start a session
	**********************************/
	require_once("session.php");
	$oSession = new session();
?>
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 14/01/2005 -->
<head>
<title></title>
<?php
	require_once("nocache.php");	// Stop - hopefully - this page being cached
?>

<meta name="description" content="">
<meta name="keywords" content="">
<meta name="author" content="newey499@hotmail.com">
<meta name="generator" content="AceHTML 5 Freeware">

  <!-- CSS Includes -->
  <link rel="stylesheet" type="text/css" href="css/layout.css" >
  <link rel="stylesheet" type="text/css" href="css/church.css" >
  <link rel="stylesheet" type="text/css" href="css/slideshow.css" >
  <link rel="stylesheet" type="text/css" href="css/tooltip.css" >
  <link rel="stylesheet" type="text/css" media="print" href="css/print.css" >
  <link rel="stylesheet" type="text/css" href="css/cssdropdownmenu.css" />
  <!-- End CSS Includes -->


</head>
<body>

<!-- ========================================================================== -->
<!--                            Start of CSS Layout                             -->
<!-- ========================================================================== -->
<div id="maincontainer">



<?php
	require_once("mysql.php");
	require_once("globals.php");
	require_once("genlib.php");
?>

<?php
	include_once("topbanner.php");
?>

<p>
<?php
	backToSermonsTalksPage();
?>
</p>

<p>
<h4>
What Would Jesus Say to a Struggling Parent ?
</h4>
<br />
<b>
Luke 7:11-17
<br />
Sermon preached at Christ Church, Lye by Simon Falshaw
<br />
June 2003
</b>
</p>

<p>
<b>
Introduction
</b>
<br />
We are looking at variety of subjects this month under the title what would Jesus say to various people. Not just theory because Jesus met a huge range people and the Gospel records his encounters.  Tonight we look at what would Jesus say to a struggling parent. Not just parents it could also  be struggling Grandparents. Let me add something to that list.  This is not just for parents - we all encounter children and teenagers as part of everyday life. We all meet people who are sometimes facing difficulties with their children. So what I am talking about  may not just be for you directly sometimes facing worries and difficulties issues with your own  children, but it may be that there is  someone you are called to help.
</p>

<p>
Being a parent is sometimes hard work. It is sometimes very painful. In a very distant way we share something of what God has known - that is creation is risky and sometimes causes great grief. Here we look at this story of a woman, a parent who encountered Jesus in the midst of grief, and discovered that he cared for her as a struggling parent.
</p>


<p>
<b>
The Story
</b>
<br />
Jesus arrives at a town a small out of the way town called Nain.  As he arrives he sees a very large crowd milling around the entrance.  Why are they  there? Imagine being one of that crowd. It is a small village, probably fewer than 1000 at most. Most people know each other If not by name by sight.  Many people are interrelated. Every one knows the low down on every one else. You share gossip. But there is a good side too. People are close and they support each other and they look out for each other. When the harvest fails and there is not enough food to go round you are all one family. And there in crowd with you are your brothers, sisters, cousin, aunts and uncles.
</p>

<p>
A few days ago something very sad happened. There was a woman, she had a sad life, her husband had died 1 or 2 years after they got married. She had bring up her baby son all by herself. People supported her but there is only so much can they do. She toiled day and night to have enough to live on, but she managed and slowly her son grew and began help her. Life became a little easier. After years of hardship a light showed end of this dark tunnel, she could see a way out of the ashes of poverty, her son was growing up and one day being able to provide for his mum.
</p>

<p>
That was last week. For yesterday the son went out to work and by night he was dead.  All the woman's hopes are smashed. Now she stands there by the hearse - bowed and groaning. And around her stand her helpless friends. Their hands are limp, their faces look at the dust. A heavy weight of sadness has settled on them all. Some of them are weeping. It is so awful that they do not know what to say. To loose a son is bad but to lose your only son is a catastrophe. And worse she is a widow. The woman stands there in the middle of the crowd her face streaming with tears and feeling so alone.
</p>

<p>
Perhaps she asks why has this happened, what have I done? And perhaps her conscience digs up old sins, a secret to no one but herself. Is God punishing me? Why God why.
</p>

<p>
But someone is walking through the crowd, towards the coffin. It's Jesus and when he sees the woman his heart feels her pain. He sees the blankness of her future, and he speaks two simple but calming words "Don't cry". Good words but not words that make sense. For what other response would you have if all your hopes and future have been destroyed, and all that lies before you is a dead body a hunk of rotting meat, ready for disposal. It is simply ridiculous to say "Don't cry". For what future does she have - only poverty and a desperate grind to get enough food. What else can we do? Crying is all we have. Tears are our bread - who is this man who says "Don't cry"!
</p>

<p>
He moves away from the woman and towards the coffin, and touches it. But you can't do that - it's dirty - it's taboo. The Holy Scriptures tells us that Gods law says that a priest must not touch a corpse, and just to make sure they say he must not touch the coffin either. The crowd is shocked and silent. The bearer stops uncertain of what to do next.
</p>

<p>
And Jesus speaks again, "Young man I say to you get up". What a gasp the crowd made at his audacity. And then he does just that, he sits up and begins talking. This is no odd muscular twitch in a corpse, a freak, this man is communicating with us he is speaking he is alive. And then Jesus gives him back to his mother.
</p>

<p>
The people are stunned. And within a few minutes the wailing has given way to singing dancing and shouting, and they are saying "A great prophet has appeared among us, God has come to help his people".
</p>

<p>
What would Jesus say to a struggling parent?  God has come to help, he is not so far off distant and unconcerned about your problems, but he has come to you! Yes that’s right you. That’s right to help even me sitting here in these seats tonight. Hallelujah.
</p>

<p>
Whar Would Jesus say to a Struggling Parent?
<br />
Let me sum things up. Jesus might  say two things to a struggling parent today.
<br />
I have come to help. His action here is first of all addressed to the real practical needs of the suffering woman.  If Christianity is not practical what use is it? if it doesn't make a real difference to every day life, and what could be more earthy than children, you must ask the question is it really real?
</p>

<p>
When Jesus says to us I have come to help, the response for us must be to pray. To bring to Jesus the needs of children and concerns of children in confidence that he cares and that when righteous people pray seriously, things happen.
</p>

<p>
And don't we need to do that. If you are a parent or Grandparent you will know that there is always plenty to worry about with children. With babies sometimes they cry and cry but can't speak to say what is wrong, all we can do humanely sometimes is hug them, and wait and put in ear plugs. It drives us to prayer. Suffering in children drives us to desparation and desparation to prayer.
</p>

<p>
And it goes on through the ages. You worry about their  friends, health, school, homework, exams, jobs, girl friends boyfriends etc. In all these situations we can do so much but only so much. People have a free will. In the children this will be themselves. As they grow older that becomes more and more the case. It is in these situations we soon reach the end of our human resources. We reach a point where the only one who can do something is God. We have to pray. What did Jesus say, I have come to help.
</p>

<p>
One caution, Jesus has come to help, but he sets the agenda. Parents want the best for their children but sometimes they want too much. If we pray for our children to be a multimillionaire genius who plays football for England and also have, a successful sideline in politics and the record industry our prayers come to nothing. I am exaggerating.  But those are our ambitions not God's. We must pray for his will. For reasonable health education, job, happiness etc. Use their gifts to their best abilities.
</p>

<p>
Children need it, and much more so today do Grandchildren. They are brought up in a much more godless age than you were, in relationships, education and confusingly multi faith. Sexual behaviour as modelled on television is far from Christian. The internet exposes children to many potential dangers, we must pray, because if we don't who will? And remember what would Jesus say to a struggling parent, I have come to help.
</p>

<p>
Something else he might say. He says has I have come to help - sometimes translated - "visited". Greek words used mean saved. It speaks of Gods action to rescue people. Not just physical but spiritual. What Jesus means when he says I have come to save is he wants our children to know eternal life. We should pray for their salvation and growth in Christ with confidence.
</p>

<p>
It is possible for rich parents to buy their children everything and so spoil them. Possibly too for them to do it wisely and lovingly, and might seem they actually want for nothing - and yet they are missing the most important thing in the world. They don't know Jesus died for them and rose from the dead give eternal life.
</p>

<p>
What did Jesus say a struggling parent, not just I have come to help but I have come to save - but pray for salvation for your children.
</p>

<p>
I wonder how many of you sit here today because someone in your family parent, god parent, grandparent, prayed for you.  Well its time to pass on the blessing. Get on your knees and pray that God will save and bless the next generation.
</p>


<p>
<?php
	backToSermonsTalksPage();
?>
</p>


</div> <!-- End div  id="maincontainer"> -->
<!-- ========================================================================== -->
<!--                            End of CSS Layout                               -->
<!-- ========================================================================== -->


</body>
</html>
