<?php
	/******************************
		Talk to MySQL
	**********************************/
	require_once("mysql.php");


	/******************************
		Start a session
	**********************************/
	require_once("session.php");
	$oSession = new session();
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 14/01/2005 -->
<head>
<title>Christ Church, Lye, West Midlands. UK</title>
<?php
	require_once("nocache.php");	// Stop - hopefully - this page being cached
?>

<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta name="description" content="">
<meta name="keywords" content="">
<meta name="author" content="newey499@hotmail.com">
<meta name="generator" content="AceHTML 5 Freeware">


  <!-- CSS Includes -->
  <link rel="stylesheet" type="text/css" href="css/layout.css" >
  <link rel="stylesheet" type="text/css" href="css/church.css" >
  <link rel="stylesheet" type="text/css" href="css/slideshow.css" >
  <link rel="stylesheet" type="text/css" href="css/tooltip.css" >
  <link rel="stylesheet" type="text/css" media="print" href="css/print.css" >
  <link rel="stylesheet" type="text/css" href="css/cssdropdownmenu.css" />
  <!-- End CSS Includes -->

</head>
<body>

<?php
	require_once("mysql.php");
	require_once("globals.php");
	require_once("genlib.php");
?>

<!-- ========================================================================== -->
<!--                            Start of CSS Layout                             -->
<!-- ========================================================================== -->
<div id="maincontainer">

<!-- ========================================================================== -->
<!--                             Start Top Section                              -->
<!-- ========================================================================== -->
<div id="topsection">
<div class="innertube">

<!-- Top Banner for site -->
<?php
	include_once("topbanner.php");
?>

</div>  <!-- End <div class="innertube"> -->
</div>  <!-- End <div id="topsection"> -->

<!-- This extra pointless div is needed to get IE out of the crap -->
<!-- Without it the top banner is not displayed                   -->
<!--[if IE ]>
	<div>
	</div>
<![endif]-->


<!-- ========================================================================== -->
<!--                               End Top Section                              -->
<!-- ========================================================================== -->



<!-- ========================================================================== -->
<!--                              Start Text Section                            -->
<!-- ========================================================================== -->
<div style="margin-left:2em; margin-right:2em;">



<!-- Top Banner for site -->
<?php
	include_once("topbanner.php");
?>

<br />


<p>
<?php
	backToSermonsTalksPage();
?>
</p>

<p>
<h4>
﻿A Birthday to Remember
<br />
Ezekiel 1:1-3:15
<br />
Christ Church Lye June 2009
</h4>
</p>

<p>
<b>
The Vision
<br />
The Birthday 1:1-3
</b>
</p>

<p>
Some birthdays are more memorable than others. As we go on in life we probably celebrate fewer birthdays but the ones we celebrate tend to be on the more significant dates. Ezekiel’s vision begins in the 30th year (1:1),  very probably Ezekiel’s 30th birthday, and what a memorable birthday - but not for any of the reasons that you might expect.
</p>

<p>
It did not begin as a happy day. Let me explain why. Ezekiel was born in Judah during the reign of King Josiah. You can read about him in 2 Kings 22-23.  During his reign the book of Gods law had been rediscovered in the temple, but not only was it rediscovered it also was read and applied. The nation had publicly renewed its commitment to God. Idol worshipping priests were dismissed, statues cut down. There was  a national revival and it was a time of hope.
</p>

<p>
But then Josiah died and things went from bad to worse.  The nation turned its back on God with a vengeance In Ezekiel’s 25th year, 597 BC,  Judah fell to Babylonian invaders and a large number of people were taken away as slaves and captives. People became strangers in a foreign land.
</p>

<p>
We are a slightly international congregation, quite a few of you, have found yourself living in a country which was not where you were born. Part of Ezekiel’s experience may be part of your experience.
</p>

<p>
Ezekiel had been forced into captivity. There was a deep sense of loss. People felt bereaved. In Psalm 137 you can read about how they felt,  "By the rivers of Babylon we sat down and wept" and it goes on "How can we sing the songs of the LORD while in a foreign land."   For the exiles it was not simply a loss of land and friends and wealth and status and culture but something far more profound. For were they not a unique nation called by God and given a place to live by him? And now they wonder is that really true?  It felt like the loss of God himself.
</p>

<p>
But Ezekiel’s loss was even more acute than that. Look at 1:3 and we read that Ezekiel was a priest.  In Numbers Ch 4 it implies that the age at which someone began to work as a priest was 30.  And so on this day when Ezekiel should have been leading the people of God in worship of almighty God in the temple for the first time, a time of celebration and joy and a sense of great privilege, instead he is sitting by a drainage ditch in a refugee camp.  He must feel crushed and abandoned, and have been wondering,  how has it all come to this?  Where is God?
</p>

<p>
But for one word - one very important word found in v3 "there" ie: in that place "the hand of the LORD was upon him." God is everywhere Augustine of Hippo (c 400 AD) described Gods omnipresence this way “God is an infinite circle whose centre is everywhere and whose circumference is no where." There is no place on this earth, even in this entire universe, where we can be any nearer God than we are now - or any further from him.
</p>

<p>
For children of Israel something of a new truth. Yes they  knew of it, and believed God to be the creator of everything  - but they were so used to the LORD  being God of their nation that they didn't really believe that he was God in all nations and places.  Do we believe that?  Yes and yet I know that I need to keep remembering it.
</p>

<p>
Move on and look at the vision that Ezekiel has - and look at three main parts - the living creatures, the wheels and the throne.
</p>

<p>
<b>
The living creatures  1: 4-14
</b>
</p>

<p>
Ezekiel sees a vision. It begins with a great flashing thunderstorm approaching.  In centre of it, v 5, are what are described as four living creatures, note they are what "looked like" living creatures.  If you go through the passage and note  the number of times that it says that something "had the appearance of" or "looked like". He is seeing something outside normal human experience and so it is difficult to find the words to describe what he sees.
</p>

<p>
Now the very strangeness has sometimes caused people in last 60 years proposed unusual interpretations of Ezekiel’s vision. Some see him as describing a visit by UFO's through primitive eyes. This interpretation probably tells us more about our own age and its worries or hopes than about a text written down 2500 years ago
</p>

<p>
The elements of Ezekiel’s vision - clouds lightening angels, falling down etc are all things we find elsewhere in Biblical visions.  Looking at the evidence that we have from Scripture,  Ezekiel’s vision looks like what we would expect a divine encounter to be like. If Ezekiel met aliens then we have to say that Moses, Isaiah, Jesus, Peter, and John also had UFO encounters. Given that their stories are consistent perhaps what we need to do is turn the question round and ask how reliable and backed up by hard evidence are UFO stories? But that’s another issue.
</p>

<p>
The four living creatures each look like men, v 5 but each has four faces.  Can you make sense of that or imagine it in your head?  No.  Today with the objective scientific view of the world we have inherited we tend to think very literally, and so when come to a passage like this we find it hard to make sense of it. Ezekiel is speaking as a prophet - but the style in which God speaks to him and us here is one of symbols, so when we read we need look behind the literal picture and ask what does it stand for?
</p>

<p>
Each of the living creatures has four faces, v 10.  The Lion, still living in Middle East at this time was known for its strength, and ferocity, also it was known as a symbol of royalty. The Eagle is swift and high flying, the most majestic of birds.  The Ox is strong and then us the man - made in the image of God - symbolic of Gods majesty.  The living creatures have wings - they are angelic, they are sent from God and together they represent God  and express his power, strength, wisdom and majesty.
</p>

<p>
There are four of them, probably representing the four corners of the Earth.  All creation is under God and serves him.  The four faces say something about his vision and knowledge.  He can see everywhere and knows everything.
</p>

<p>
<b>
The Wheels v15-21
</b>
</p>

<p>
Under each creature is a wheel, v 15. They sparkle gloriously made of Chrysolite. I am not quite sure geologically what it is, but the point is this who makes wheels out of precious stones?  The glory and wealth of God's economy is such that the things we consider of great value  are so common place as to be used as tyres.
</p>

<p>
The wheels are strange things for in v 16b "each appeared to be made like a wheel intersecting a wheel".  You might you imagine something like a Gyroscope.  But Ezekiel is not looking through the eyes of an engineer, or car mechanic but those of  an apocalyptic prophet.  What does the symbol mean?  In v17 we see the wheels free the creatures to move in whatever direction they want, v 19, they are not confined to the ground, nor in v 20 is there movement dependant on mechanics or engines. They simply move as the spirit of the creatures wills them to move.
</p>

<p>
Don't try to picture it in your mind too much but remember the point;  these creatures have absolute freedom of movement.  At the centre of the temple in Jerusalem was the ark, and over the ark were statues of angels - a bit like in this vision, but those angels were stationary, and so to these people who feel abandoned and that God has deserted them, here Gods in his angels reveals himself as one who is everywhere and can appear anywhere he is not confined to one building in one country. He is living.
</p>

<p>
<b>
The Throne verses 22-28
</b>
</p>

<p>
Then the vision moves on in v 22.  Above the creatures is an expanse that looks like sparkling ice, isn't there something glorious about fresh untouched snow and ice? It looks so pure.  But our eyes shouldn't stop with this heavenly ceiling  for in v 25 there is a great voice that comes from even higher up. There is throne - made of something that looks like sapphire v 26 and on that throne is one that looks like a man, it is all glorious around him,  and Ezekiel ends in v 28 "This was the appearance of the likeness of the glory of the Lord".  This is God.
</p>

<p>
How do you respond to a vision like that?  There is only one way,  with worship. Confronted with a God who is everywhere and has all power in his hands, who is so glorious that he can't describe him Ezekiel falls face down, v 28.
</p>

<p>
As we look at this passage it can all seem very strange.  We may think but I can't imagine it - it all seems so distant. Or we might think well,  "Yes if I had a vision like that that’s how I would respond."   Even in the Bible visionary encounters like this, that leave people lying face down on the ground are rare, and today we have something even better.  Ezekiel’s vision may have lasted 1/2 hour but today God has come to us in the person of Jesus Christ and through his Holy Spirit is in every one who believes now permanently.
</p>

<p>
So how to we respond - like Ezekiel we need to bow down before God.  Other is one very important thing then book of Ezekiel  teaches us is the transcendence of God, ie God’s otherness and greatness.  That he is not as we are. We are created and dependant beings.  But God has life in himself he has no beginning nor end - he needs nothing. The difference between a flea and one of these angelic beings here may seem enormous  but in comparison with God, God is so much greater they are effectively the same.  They are both made but  he is the one and only  maker.
</p>

<p>
<b>
The Call 2:1-3:15
</b>
</p>

<p>
Worship is one way to respond to Gods call. But God never gives such visions merely for there own sake.  Look at chapter 2-3 you can see how God commissions Ezekiel for his task as a prophet.
</p>

<p>
<b>
Tough Task
</b>
</p>

<p>
In v4 you can see the people he will speak to are obstinate and stubborn. They will oppose his message e.g  v 6 they will be like briers, thorns and scorpions.  Look on in  3:5-6;   it will be so hard that it would be easier going to complete foreigners,  ie: if  Ezekiel went to a people whose language  was completely different - so different that he couldn't even guess what words meant and perhaps so obscure that it hadn't even been written down;   and to people who worshipped Idols and knew nothing at all of the living God of Israel, it would be a more fruitful task than this one.  Sadly the whole house of Israel - in exile and still in Judah are 3:7 hardened and obstinate Sadly true of today - sometimes Gods people can be harder and more stubborn, and  resistant to change  that those outside the church.
</p>

<p>
 God's response is to strengthen  Ezekiel - v 8-9 "I will make you as hardened and unyielding as they are. I will make your forehead like the hardest stone, harder than flint".  God's equipping of Ezekiel is equal to the task. Isn't it wonderful to know that what God calls us to he also thoroughly equips us for. He is utterly  reasonable.
</p>

<p>
Ezekiel was to have a very hard task. It would not be a ministry of great results but whatever happened he was to keep going. Look at 3:11 he is to speak " This is what the sovereign Lords says",  whether they listen or fail to listen."    We all like success. When we go visiting on the Rufford Estate it is good to be able to come and say - yes people listened.  Yes that’s important but it is not the bottom line for doing it.  No the bottom line for this and all Christian ministry is not results, but simply this faithfulness. To bring glory to God - by testifying to him and through our lives his perseverance
</p>

<p>
I once lived on a street and on  that street was a man who felt a call to some sort of Christian work.  So went to see one of the Pastors of the local church. The Pastors reply was ‘well I think you should carry on at work’. The man felt a little disappointed. But I think the Pastor was wise.  For committed Christian ministry so often involves suffering and is costly. It is easy to have a rose tinted view of it. To see it in almost romantic terms.  Unless you are really called to it - don't even think about it. For the Gospel faithfully delivered will at times be unpopular.
</p>

<p>
Ezekiel’s ministry would be incredibly costly.  He would was not able to speak, other than deliver a few prophecies, for 5 years.  He spends a year lying on his side, cooking his food over cow dung and eating a starvation diet because God wants him to symbolise the siege of Islam.  His wife dies and he is not allowed to mourn because God is not mourning, and to make it worse he seems to be almost alone in what he does.  No one else stands with him/.
</p>

<p>
And yet he carries on, Why?  Because he is not motivated by what he can get out it, he doesn't do it for status and what people will think of him, he doesn't do it for the results.  It’s terms of are a measure of job satisfaction it is a terrible, and before we even start the lack of an adequate health and safety policy.  Who would touch a job like that?  Only concerned about the glory of God and above all, whatever the cost.
</p>

<p>
I once was thinking about working overseas I went to a Mission Conference and there was a woman who had worked in Brazil and had been bitten on the face by a dog. She had had fear of suffering from Rabies. She spoke said this, and I remember it very well "If you are going to be called to mission you will suffer".
</p>

<p>
The work Ezekiel is called to will be a bitter-sweet experience.  Look at 2:9 he is given a scroll and on it are words of "Lament and mourning and woe."  Much of Ezekiel’s message, at least up until the final fall of Jerusalem in 587 BC is one of a warning. It is one of declaring that God hates sin and is going to judge. Note there is no sadistic glee in what Ezekiel is called to do.  His is a message of mourning - of unbearable sadness for what has happened to Gods people and for what will happen.
</p>

<p>
But there is another side to it, see 3:3.  When he eats the scroll it tastes sweet. Because it is Gods word and it is true, so it brings blessing. It is possible to be in the midst of the most terrible suffering or evil and wrong and yet if we know that we are where God wants us to be, and we are doing things his way to also have the most tremendous peace.   I think that’s why the scroll tastes sweet.  It may be painful message to deliver but its true because God is Holy and so it brings blessing.
</p>

<p>
Gods call of Ezekiel is not just one of sharing Gods message, no it goes far deeper.  Ezekiel is invited to feel how God feels about what he says, and so when the vision is over (3:14) he goes away in bitterness and anger of spirit.  The bitterness referred to is not unforgiveness , rather it is something like discontent or fierce anger because of a deep wrong or hurt.  The word used is  used of a bear being robbed of her cubs.
</p>

<p>
<b>
Conclusion
</b>
</p>

<p>
To end with lets imagine Ezekiel had had his vision in the UK today. And having had it the Holy Spirit he sat him down on the hill overlooking Lye. How would he feel today as he looked out?
</p>

<p>
And for us as we look at all the little communities of which we are part - are we ready to be faithful like Ezekiel - whatever the cost?  To speak whatever people say, but even more important and before that to feel what God feels for those who turn their backs on him.  Hard but if we do - we will find what Ezekiel found - that God strengthens and equips us so we are equal to the task.  And it brings a blessing for  the word of God is sweet.
</p>


<p>
Simon Falshaw 6/09
</p>



<p>
<?php
	backToSermonsTalksPage();
?>
</p>

<!-- ========================================================================== -->
<!--                              End Text Section                              -->
<!-- ========================================================================== -->
</div>


<!-- ========================================================================== -->
<!--                          Start Footer Content Section                      -->
<!-- ========================================================================== -->
<?php
	include('footer.php');
?>
<!-- ========================================================================== -->
<!--                            End Footer Content Section                      -->
<!-- ========================================================================== -->


<!-- ========================================================================== -->
<!--                            End of CSS Layout                               -->
<!-- ========================================================================== -->
</div>  <!-- END <div id="maincontainer"> -->


</body>
</html>

