<?php
	/******************************
		Talk to MySQL
	**********************************/
	require_once("mysql.php");


	/******************************
		Start a session
	**********************************/
	require_once("session.php");
	$oSession = new session();
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 14/01/2005 -->
<head>
<title></title>
<?php
	require_once("nocache.php");	// Stop - hopefully - this page being cached
?>

<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta name="description" content="">
<meta name="keywords" content="">
<meta name="author" content="newey499@hotmail.com">
<meta name="generator" content="AceHTML 5 Freeware">


  <!-- CSS Includes -->
  <link rel="stylesheet" type="text/css" href="css/layout.css" >
  <link rel="stylesheet" type="text/css" href="css/church.css" >
  <link rel="stylesheet" type="text/css" href="css/slideshow.css" >
  <link rel="stylesheet" type="text/css" href="css/tooltip.css" >
  <link rel="stylesheet" type="text/css" media="print" href="css/print.css" >
  <link rel="stylesheet" type="text/css" href="css/cssdropdownmenu.css" />
  <!-- End CSS Includes -->

</head>
<body>

<?php
	require_once("mysql.php");
	require_once("globals.php");
	require_once("genlib.php");
?>

<!-- ========================================================================== -->
<!--                            Start of CSS Layout                             -->
<!-- ========================================================================== -->
<div id="maincontainer">

<!-- ========================================================================== -->
<!--                             Start Top Section                              -->
<!-- ========================================================================== -->
<div id="topsection">
<div class="innertube">

<!-- Top Banner for site -->
<?php
	include_once("topbanner.php");
?>

</div>  <!-- End <div class="innertube"> -->
</div>  <!-- End <div id="topsection"> -->

<!-- This extra pointless div is needed to get IE out of the crap -->
<!-- Without it the top banner is not displayed                   -->
<!--[if IE ]>
	<div>
	</div>
<![endif]-->


<!-- ========================================================================== -->
<!--                               End Top Section                              -->
<!-- ========================================================================== -->



<!-- ========================================================================== -->
<!--                              Start Text Section                            -->
<!-- ========================================================================== -->
<div style="margin-left:2em; margin-right:2em;">

<p>
<?php
	backToSermonsTalksPage();
?>
</p>




<p>
  <b>The Shocking Truth about the Church</b>
</p>


<p>
 <b>The Church according to Dan Brown</b>
</p>

<p>
One of the accusations that the book the Da Vinci Code
makes is that the Church has for centuries covered up
the truth about Jesus Christ and did so through waging
a particularly vicious campaign against those who
tried to tell the truth. It teaches that the church is
particularly oppressive of women and free thought. We
read "during three hundred years of witch hunts the
church burned at the stake an astonishing 5 million
women" (p. 173 of the Da Vinci Code). The actual
figure  is about only one per cent of this claim,
between fifty thousand people between 1400 and 1800
across Europe.
</p>

<p>
It is hard in the novel to separate the fact from
fiction though Dan Brown seems to believe what he
writes. At one point a Newspaper Editor says this
about the ideas in the book to the central character,
Robert Langdon, "it will kill your reputation. Besides
you are a Harvard historian (for Gods sake), not a pop
schlockmeister looking for a quick buck, where could
you possibly find enough credible evidence to support
a theory like this". Ironically  that fictional line
could well be said to be true of Dan Brown,  his story
and his theories.
</p>

<p>
For instance he states that the Emperor Constantine,
who according to Dan Brown wrote the Bible, was a life
long pagan who was baptised on his death bed, to weak
to protest. (p. 313). This is not surprising since at
the time  it was not unusual to be baptised late in
life. As an Emperor,  Constantine certainly showed
evidence in the way he made laws of some true faith.
He showed compassion for the poor and weak.
</p>

<p>
Another example of Dan Brown's historical inaccuracies
regarding the Church occurs in the treatment of the
Priory of Sion. He states that it was a real secret
society founded in 1099 AD. The document on  which he
bases this is actually well known to be a forgery.
Those who helped to plant the forgery in the
Bibliotheque Nationale in Paris have admitted such.
</p>

<p>
 <b>The shocking truth about God's people</b>
</p>


<p>
if Dan Brown wanted to expose some of the weakness of
the Church, he did not need to dig around in some
obscure corners of history and use unreliable
documents and exaggerate it. God's people have always
been a very mixed bag. You only have to look in the
Bible to see that. Abraham gave away his wife to an
Egyptian Pharaoh because he was afraid. Moses murdered
a man and went on the run. King David committed
adultery and then in a cover up operation arranged for
the women's husband to be killed. Peter was a coward
and ran away when Jesus was arrested.
</p>

<p>
The fact that the Bible does not hide the sometimes
very serious faults with God's people suggest that it
was not written as propaganda. It was not written by
people promoting their own agendas while hiding the
real truth. on the contrary people were sharing the
truth about themselves and the amazing truth about a
God who loves them despite.
</p>

<p>
The real truth about God's people is certainly as
shocking as the fiction that Dan Brown writes. Perhaps
more so because it is true. The history of the church
since the times of the Bible has been equally as bad
at some points. However there was another side to the
church.
</p>

<p>
 <b>The Radical Church.   Acts 4: 32 - 37</b>
</p>


<p>
At one point Dan Brown describes the church in these
words  "nobody could deny the enormous good the modern
church did in today's troubled world and that the
church had a deceitful and violent history". Here in
the early days of the church (this passage is dated
about 35 AD) we see something quite remarkable. We
read "no one claimed that any of his possessions was
his own, but they shared everything they had".  They
certainly did not do things by halves. People even
sold land and houses and gave away the proceeds. They
did it so much that were "there were no needy persons
among them". Though it is not saying they gave away
everything they had, or that anyone could come into
your house at any hour and borrow anything that you
had. Nor was it denying that people had personal
possessions. These things were personal  possession in
as much as you chose to lend or give them away.
</p>

<p>
What the church in Jerusalem renounced was not
possessions but  possessiveness. It was a change of
attitudes in their hearts. This kind of social action
has been seen throughout the history of the church.
Numerous social organisations and charities that we
are familiar with have their roots in Christianity -
for instance the RSPCA. More recently the church has
been a major driving force behind the campaign to
cancel the unpayable debts of third world countries.
</p>

<p>
What we read of in Jerusalem might sound like a bit of
primitive communism. Karl Marx described  communism as
"from each according to their abilities,  to each
according to their needs". Unfortunately socialism (a
stepping stone on the root to communism) has almost
never come into power democratically. It has usually
had to compell people to share their possessions of
land, housing and industry through brute force.
Millions have been executed in China and the Soviet
Union during the last century as a result.
</p>

<p>
The communist desire of fair shares for all is a good
one. But the problem is we do not naturally or easily
want to share what we have. It is fine looking at a
distance and thinking it would be good if people did
that, but would I do it? What made these people so
generous? For this is not the sort of generosity we
see in normal life. We might see it in one or two
people, but not in a whole community. Where does it
come from? The truth about the church is shocking but
it is also shockingly wonderful. But why does it
happen? We'll come back to that question later on.
</p>

<p>
 <b>The Scandalous Church.  Acts 5:1-11</b>
</p>

<p>
There is another side to the church and we see that in
the story of two church members. Ananias like many
had sold some property and then gave some money to the
church. Only that is not quite what happened. It looks
that as he had kept some money back.  When the
collection was being taken up by Peter the leader of
the church he suddenly turns and says to Ananias, "how
is it that Satan has so filled your heart that you
have lied to the Holy Spirit and have kept some of the
money for yourself". Ananias lied,   that is he
pretended to have a generosity he did not actually
have.
</p>

<p>
When he heard that he falls down dead. Being a hot
climate he is quickly buried. It seemed to have
happened so fast and that his wife came to the meeting
in ignorance. The same thing in turn happens to her.
Is this a direct supernatural intervention or was it
simply shock,  leading to a heart attack at such a
great deception being exposed so quickly? Which ever
way it is not meant to be a model that we should
expect to be common  in church practice! The Book of
Acts records many things but by doing so it is not
necessarily stating they are normal church life. There
examples but not commands.
</p>

<p>
However whilst what we do may be different, the God
behind it all is unchanging. If the truth about the
church is  shocking, but  so too is the truth about
God.
</p>

<p>
 <b>Think on these four things - </b>
</p>

<ul>

<li>
We see that God is holy. His standards of holiness
go far beyond ours. His holiness means that he hates
evil. No unrepentant sinner can stand in his presence.
</li>

<li>
We cannot hide from him. Peter knows what has
really been done with the money from Ananias's field
by a God given supernatural instinct. Peter knows that
Ananias is lying to the Holy Spirit.
</li>

<li>
God is real. Sometimes we play at being Christians.
It can be a habit we put on every Sunday. I hope not I
don't think it is but lets always be on our guard.
This dramatic intervention reminds us that God is
really real. We always stand on holy ground.
</li>

<li>
God cannot ignore sin. Ananias faced judgment very
suddenly and without warning. We must all face it one
day.
</li>

</ul>

<p>
So when faced with God it is not surprisingly that the
passage concludes v 11  "great fear seized the whole
church and all who heard about these events".
</p>

<p>
We ask the question what made the church so radically
generous and now we face a second question if God is
like that how are we (not simply other people but we)
going to escape the wrath of God.
</p>

<p>
 <b>A life changing message  4 :33</b>
</p>

<p>
The answer as it often is,  is found in the Bible. And
indeed the very passage we have been looking at. As
someone said the treasurers are in the text. Lets
backtrack to what happened just before these
extraordinary events. Look at v 33 and see what the
Apostles were doing. It was very simple they were
reminding people of Jesus. Look at v 33 "with great
power the Apostles continued to testify to the
resurrection of the Lord Jesus and much grace was
among them". What does this mean? The Apostles were
men that followed Jesus around. They  had known him
initially as a friend and a neighbour. As man like
themselves. And then they'd seen him as a very
remarkable man and a miracle worker. Then tragedy
happened. He was arrested, tortured and with a great
miscarriage of justice condemned to death. When
someone is dead it is permanent.
</p>

<p>
It was meant to be the case with Jesus but instead
after three days in a grave he came back to life. He
reversed the impossible. The only explanation is the
power and reality of God. That is the answer to both
these questions - why were these people so generous
and how do we escape the anger of God at sin.
</p>

<p>
Maybe the early Christians reasoned like this. If this
man rose from the dead he is no ordinary man indeed he
must be as he claimed he is the messiah and indeed
God. If God had to die for my sins then they must have
been very serious indeed. I do indeed stand under
God's wrath. They might also have thought if Jesus is
God and he died and rose again for my sins then they
must really and truly totally removed and forgiven.
</p>

<p>
They might have continued thinking like this. If he
died for me I owe him everything. He loved me enough
to lay down his life for me. So I must love others in
the same way.  That is what they have been doing by
sharing their possessions. They recognise that all
they had was his.
</p>

<p>
It is understanding the events of Jesus that makes the
church a supernatural fellowship.
</p>

<p>
d yet although this is true the church still seems a
very mixed bag. Dan Brown wrote "nobody could deny the
enormous good that the modern church did in today's
troubled world and yet the church had a deceitful and
violent history".
</p>

<p>
I cannot say for  others but I am responsible for
myself. The church has done a tremendous amount of
good and yet. When I am gone I hope people will not
have to say Simon Falshaw was a Christian AND YET and
have a very long list of things to add on. I hope that
I will hope the words AND YET will be as small as
possible. The Da Vinci Code may be full of
inaccuracies but it does at least one small good thing
for the church. It reminds us of the challenge to live
up to the calling, to be worthy of being part of
Christ's church.
</p>

<p>
What keeps us that way? What kept the early church
that way? Look again at verse 33 "and much grace was
among them all". Grace is God's undeserved mercy. The
church has failed humanly God should have got rid of
it ages ago. But by the grace of God it continues so
let us keep our eyes on Jesus.
</p>








<p>
<?php
	backToSermonsTalksPage();
?>
</p>


<!-- ========================================================================== -->
<!--                              End Text Section                              -->
<!-- ========================================================================== -->
</div>


<!-- ========================================================================== -->
<!--                          Start Footer Content Section                      -->
<!-- ========================================================================== -->
<?php
	include('footer.php');
?>
<!-- ========================================================================== -->
<!--                            End Footer Content Section                      -->
<!-- ========================================================================== -->


<!-- ========================================================================== -->
<!--                            End of CSS Layout                               -->
<!-- ========================================================================== -->
</div>  <!-- END <div id="maincontainer"> -->


</body>
</html>

