<?php
	/******************************
		Talk to MySQL
	**********************************/
	require_once("mysql.php");


	/******************************
		Start a session
	**********************************/
	require_once("session.php");
	$oSession = new session();
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 14/01/2005 -->
<head>
<title>Christ Church, Lye, West Midlands. UK</title>
<?php
	require_once("nocache.php");	// Stop - hopefully - this page being cached
?>

<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta name="description" content="">
<meta name="keywords" content="">
<meta name="author" content="newey499@hotmail.com">
<meta name="generator" content="AceHTML 5 Freeware">

  <!-- CSS Includes -->
  <link rel="stylesheet" type="text/css" href="css/layout.css" >
  <link rel="stylesheet" type="text/css" href="css/church.css" >
  <link rel="stylesheet" type="text/css" href="css/slideshow.css" >
  <link rel="stylesheet" type="text/css" href="css/tooltip.css" >
  <link rel="stylesheet" type="text/css" media="print" href="css/print.css" >
  <link rel="stylesheet" type="text/css" href="css/cssdropdownmenu.css" />
  <!-- End CSS Includes -->

</head>
<body>

<?php
	require_once("mysql.php");
	require_once("globals.php");
	require_once("genlib.php");
?>

<!-- ========================================================================== -->
<!--                            Start of CSS Layout                             -->
<!-- ========================================================================== -->
<div id="maincontainer">

<!-- ========================================================================== -->
<!--                             Start Top Section                              -->
<!-- ========================================================================== -->
<div id="topsection">
<div class="innertube">

<!-- Top Banner for site -->
<?php
	include_once("topbanner.php");
?>

</div>  <!-- End <div class="innertube"> -->
</div>  <!-- End <div id="topsection"> -->

<!-- This extra pointless div is needed to get IE out of the crap -->
<!-- Without it the top banner is not displayed                   -->
<!--[if IE ]>
	<div>
	</div>
<![endif]-->


<!-- ========================================================================== -->
<!--                               End Top Section                              -->
<!-- ========================================================================== -->



<!-- ========================================================================== -->
<!--                              Start Text Section                            -->
<!-- ========================================================================== -->
<div style="margin-left:2em; margin-right:2em;">


<!-- Top Banner for site -->
<?php
	include_once("topbanner.php");
?>

<br />


<p>
<?php
	backToSermonsTalksPage();
?>
</p>

<p>
<h4>
﻿Taking God For Granted
<br />
Ezekiel 9-11
</h4>
</p>


<p>
<b>
Introduction Ch. 8
</b>
</p>

<p>
The sovereign all powerful God who has called us is everywhere all the time. But because he is free and sovereign,  the blessing of knowing that presence is not controlled by us.  If people take it for granted and fail to live holy lives sometimes his blessing is withdrawn. It general in life is wrong to take people for granted and sometimes we  fail to thank and honour people  for what they do.
</p>

<p>
God is not tied down by geography.  Because a nation has had a thriving church in the past it does not mean it will continue to have one.  Turkey, Tunisia, Algeria and Libya all were centres of Christianity and Christian mission 1500 years ago. But now the church in those countries,  though  in some cases growing,  is overall tiny.
</p>

<p>
The Same applies to demoninations and churches. Let us not assume because The Church of England has many buildings and is still the state church that it will always be here. If its leaders turn their backs on God by the end of this next century,  we in the Church of England,  will end up as a ecclesiastical division of English Heritage or the National Trust. Statistically, based on current trends the numbers of the active churches will decrease by half in UK in the next 25 years.
</p>

<p>
You only have to look around at the past here in Lye to see this.  Zion - is a mosque;   Salem Chapel a furniture showroom.
</p>

<p>
And so here we see Gods leaving Jerusalem the Holy capital of his people behind. 3 chapters record stage by stage Gods exit from the temple.  Look at 9:3 "Now the glory of the God of Israel went up from above the cherubim where it had been and moved to the threshold of the temple". The glory of God equals the presence of God, so let’s look together this passage at how and why Gods glory leaves his people.
</p>

<p>
<b>
Why? Ch. 9
</b>
</p>

<p>
I like hot weather in moderation. One problem with hot weather is that biology speeds up. If you leave fruit out to ripen you find if you are not careful when you come to eat it its not just ripe it’s also rotten. There is nothing worse than finding it rotten once you have bitten it and it’s in your mouth.
</p>

<p>
Israel was  like,  than rotten - rotten to the very core. Last week in ch. 8 we saw that  even the holiest place of all, the temple, had become a centre for the worship of other Gods. And in 8:17 Gods judgement on the situation is this to say this,  "Is it a trivial matter?
</p>

<p>
No sin can never be trivial because God is holy and good and all that he is stands against sin. Billy Sunday,  the colourful US evangelist of last century,  said "we treat sin as if it was a cream puff but it’s a rattlesnake." Very rarely do people turn away from God suddenly and  overnight. More often faith is lost through a long series of small downhill steps,  in which we justify sin as "its just the way I am" or "Everyone does it" or "its only a small fault"  etc.  We treat sin as trivial. Israel had been turning away from God for centuries and was now so far gone there was no hope.
</p>

<p>
In his vision Ezekiel sees God judgement acted out.  Let’s remember it’s a vision so if some of the details shock us and we want to say is this not the God I know,  perhaps we may be interpreting things literally that are symbolic. But  I think too this vision is deliberately shocking. It is designed to shake the people in captivity (and us) out of their complacency. Sin will not go unpunished. The end result of unrepentant sin is Gods judgement.
</p>

<p>
In v 1 seven men appear - one with a writing pad the other 6 with swords. These are angels. In v 3 Gods glory begins to leave the temple and as he does so v. 4 the man with the writing kit is told to "Go through the city of Jerusalem and put a mark on the foreheads of those who grieve and lament over all the detestable things that are done it."  Note it is not the outward mark that saves people but inward attitude. It’s those who grieve and lament,  ie those who are upset, angry, disturbed or disgusted by what has happened to Gods place.
</p>

<p>
In v 5 the six men with swords are then told to walk through the city killing without pity or compassion all those who do not bear the mark.  It includes everyone.
</p>

<p>
Earlier this week a leader of the Pol Pot regime in Cambodia has gone on trial. 1.7 million people out of a population of 8 million were slaughtered in 5 years of communist extremism. Does this passage sound to you more like genocide than the God of the Bible? Maybe you are thinking this is not the God I worship. Ezekiel may be a book of the Bible but it clearly got in by mistake. When I go home I'm going to cut it out of my Bible.
</p>

<p>
There is much we don't understand in the Bible and anyone who reads the Bible with their brain engaged needs a shelf in their brain marked pending.  Pending the resurrection.  If we can't understand now, one day when we meet Jesus we will.  One of the writers of the book of Proverbs, a book full of sharp insight into life, writes this "I am the most ignorant of men; I do not have a man's understanding. I have not learned wisdom nor have I knowledge of the holy one." Proverbs 30:2.  A truly wise person knows when they are ignorant.
</p>

<p>
But note this. See where the judgement begins;  in v6 at the sanctuary. In Gods house,  with Gods own people.  This is not lashing out in indiscriminate violence, but at his own people and explicitly the leaders of his own people being brought to account (see more of that in ch. 11).  Note too how in v 7 how God sees this action - it is the defiling of the temple. This was the place where God met with man. The sancturywas also sometimes seen as a place of legal sanctuary - where someone committing a crime could flee for safety and justice. So God does not lightly turn it into a place of death, for  he is treating it like dirt something he sees as supremely precious.
</p>

<p>
The wrath of God was described by Martin Luther as "Gods strange work”.  The anger of God is not an innate part of who he is. It will not always be there. It is a reaction to sin. It is for this age one day it will be no more. The heart of the character of God is love. It is not just that God loves but because he is the Trinity he has relationship at the very heart of who he is. That relationship is love. God does not do this lightly - it grieves him.  God’s anger is his loving displeasure at sin. If that was not experienced his love  would not be real.
</p>

<p>
Ezekiel sees the killing and is shocked.  He does not gloat over the city with some sadistic glee or sit back and think aren’t people terrible today. No see in v 8 he collapses with grief - overwhelmed by the near total destruction that he is seeing.  And he says "Are you going to destroy the entire remnant of Israel?"
</p>

<p>
Look on in v 9-10 God explains why he is doing this. The nation’s sin is great, full of bloodshed and injustice, and people have turned to cynicism - God has forgotten us and practical atheism saying "the Lord does not see" Gods judgement is based on justice. It is not arbitrary, he is fair. In verse10 you see that   the punishment must fit the crime – verse 10b "I will bring down on their own heads what they have done."
</p>

<p>
This week in USA the investor Bernard Madoff was sentenced to 150 years in prison for a $50 Billion dollar fraud. This was the maximum sentence - normal sentencing guidelines for fraud stop at $400 Million.  The judge said his crimes went "off the chart".  One man whose brother was disabled and who had invested in his schemes said this “Every time he cashed a cheque to spend for his families lavish lifestyle he killed dreams”. My family had a dream for my brother someday to live in a good family group home".  Punishment must fit the crime and be in proportion to the offence.
</p>

<p>
Mr Madoff is an extreme case.  An his crimes are so enormous that we can't begin to imagine them.  But remember God owns everything.  The World is his he made it. When we use without thanks, selfishly without stewardship then we are stealing from him.  Because we ignore God we are on a global collision course with disaster.  If everyone in the world used resources at the rate we do so in the UK we would need a planet 2.5 times larger.  When we sin against him it is the most serious thing possible.
<p>

<p>
<b>
Surely Not?  Ch. 10
</b>
</p>

<p>
When Ezekiel’s listeners heard this they must have been absolutely struck dumb by what they heard.  Surely this can't happen? But yes its true, God is leaving his people.  In Ch 10 we come back to the vision of Gods glory through which Ezekiel was commissioned.  See again these awesome cherubim with 4 faces.  These creatures are strange to our ears and we probably struggle to imagine them - but we really need to do is think what do the symbols here mean.  Look at Chapter 10:9-17 one thing Ezekiel keeps mentioning repeatedly are the wheels and the freedom of movement that these wheels give, they can go anywhere. But why?
</p>

<p>
And then in v. 18 we see why "Then the glory of the Lord departed from over the threshold of the temple". God is leaving his people in Jerusalem behind. And the glory of God doesn't just leave the temple but go on in  11:23 it leaves the city too. And notice which direction it goes in. It goes east.  It goes with the exiles and away from those who remain, ie Gods blessing is with those who have experiences his judgement and are in a place where they can think through what has happened.  Jerusalem the place of blessing has become a place of evil and Babylon the place of exile has taken its place.
</p>

<p>
<b>
Hope?  Ch. 11
</b>
</p>

<p>
In the midst of Judgement Gods grace is not absent. Jump on to Chapter 11:16 and see Gods sanctuary will be in the nations that they go to.  Today Gods blessing will never leave the church but it may leave churches and for that matter denominations.
</p>

<p>
Churches may close and numbers going down make a church decline. Yes that’s bad but sometimes something has to die before new growth can take place. The tree that is pruned properly will produce lots of fruit.  Look at v18-19 God has a glorious future planned for his faithful cleansed holy people,  " I will give them an undivided heart and put a new spirit in them. I will remove their heart of stone and give them a heart of flesh".
</p>

<p>
There are no temple buildings in the New Testament church. The church in the New Testament is never referred to as a building. So where has the glory of almighty God gone?  It seen in Jesus and in turn when his Holy Sprit lives in you.  Read in 1 Corinthians 5:19 "Do you not know that your body is a temple of the Holy Spirit who is in you whom you have received from God." The glory might have gone from Israel for 70 years, after 70 years the people returned. A new temple was built but it wasn't anything as beautiful as the old, the returned exiles were poor and they struggled.  But then one day the glory of God came in right amongst them in a man who was Jesus Christ. And now it lives in us.
</p>

<p>
When talk about the Holy Spirit being in us do we really realise what we are saying?  The presence of the glorious almighty transcendent totally free God rests in us.
</p>

<p>
<b>
Conclusion
</b>
</p>

<p>
Two things end with 1) Something to think about, let’s understand our times. A truth over exaggerated is dangerous. Another word for it is heresy. I believe in the sovereignty of God. Our walk with him starts when he calls us, and if he has chosen us he will not let us go.  Israel as a nation had been chosen by God, it was unique.  But the sacredness of that calling had been forgotten.  People presumed because if God is with us it doesn't really matter if we sin.
</p>

<p>
Then the truth over exaggerated was Israel’s calling by God.  Today I think the truth over exaggerated  is the nature of Gods love. In some parts of the church love is seen as acceptance without repentance. Here is something from an Oranisation called Inclusive Church.
Above all, we believe that the Gospel as it has been received by the Church of England and across the Communion has something special to say about the love of God and the love of Jesus Christ. Something about welcome; something about openness, and something about including everyone, regardless of who what or why they are.
</p>

<p>
In one way there is something very attractive about a welcome; something about openness, and something about including everyone, regardless of who, what or why they are. I want say yes I agree with that, but stop and think for a minute. Nothing in this definition of the Gospel -nor much else in what I have read from this movement is about the holiness of God. Gods love is seen without referring to his holiness.
</p>

<p>
The two are not separate.  Love is the outworking of Gods goodness.  And Gods moral goodness is seen in his holiness.  So because God is good he loves and because he is good he is Holy and separate from all that is bad. Donald Barnhouse a predecessor of Billy Graham said "Gods love is not lazy good nature as many think it to be, and so drag it in the mud; it is rigidly righteous and therefore Christ died."  The result of love without holiness is a Gospel that is not Christian.  It may mention God it may be preached in church buildings, it may quote the Bible, but the God behind it is not the God of the Bible.
</p>

<p>
We need to apply this to ourselves. God calls us to holiness and to put away all sin.  The opposite to church decline and death is revival. A common feature of all revivals in the past has been that people treat sin seriously. Tthere is zero tolerance of it, and also that there is a sober recognition that there are only two destinies for mankind,  heaven or hell.  And that Jesus Christ alone saves and his salvation is a totally sufficient end applying it self in prayer.
</p>

<p>
To close  I am going read out the 10 Commandments in a modern version to command plus verses from the New Testament.   After each one please repond with the words  Lord have mercy.
</p>

<p>
Simon Falshaw July 2009







<p>
<?php
	backToSermonsTalksPage();
?>
</p>


<!-- ========================================================================== -->
<!--                              End Text Section                              -->
<!-- ========================================================================== -->
</div>


<!-- ========================================================================== -->
<!--                          Start Footer Content Section                      -->
<!-- ========================================================================== -->
<?php
	include('footer.php');
?>
<!-- ========================================================================== -->
<!--                            End Footer Content Section                      -->
<!-- ========================================================================== -->


<!-- ========================================================================== -->
<!--                            End of CSS Layout                               -->
<!-- ========================================================================== -->
</div>  <!-- END <div id="maincontainer"> -->


</body>
</html>

