<?php
	/******************************
		Talk to MySQL
	**********************************/
	require_once("mysql.php");


	/******************************
		Start a session
	**********************************/
	require_once("session.php");
	$oSession = new session();
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 14/01/2005 -->
<head>
<title></title>
<?php
	require_once("nocache.php");	// Stop - hopefully - this page being cached
?>

<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta name="description" content="">
<meta name="keywords" content="">
<meta name="author" content="newey499@hotmail.com">
<meta name="generator" content="AceHTML 5 Freeware">


  <!-- CSS Includes -->
  <link rel="stylesheet" type="text/css" href="css/layout.css" >
  <link rel="stylesheet" type="text/css" href="css/church.css" >
  <link rel="stylesheet" type="text/css" href="css/slideshow.css" >
  <link rel="stylesheet" type="text/css" href="css/tooltip.css" >
  <link rel="stylesheet" type="text/css" media="print" href="css/print.css" >
  <link rel="stylesheet" type="text/css" href="css/cssdropdownmenu.css" />
  <!-- End CSS Includes -->

</head>
<body>

<?php
	require_once("mysql.php");
	require_once("globals.php");
	require_once("genlib.php");
?>

<!-- ========================================================================== -->
<!--                            Start of CSS Layout                             -->
<!-- ========================================================================== -->
<div id="maincontainer">

<!-- ========================================================================== -->
<!--                             Start Top Section                              -->
<!-- ========================================================================== -->
<div id="topsection">
<div class="innertube">

<!-- Top Banner for site -->
<?php
	include_once("topbanner.php");
?>

</div>  <!-- End <div class="innertube"> -->
</div>  <!-- End <div id="topsection"> -->

<!-- This extra pointless div is needed to get IE out of the crap -->
<!-- Without it the top banner is not displayed                   -->
<!--[if IE ]>
	<div>
	</div>
<![endif]-->


<!-- ========================================================================== -->
<!--                               End Top Section                              -->
<!-- ========================================================================== -->



<!-- ========================================================================== -->
<!--                              Start Text Section                            -->
<!-- ========================================================================== -->
<div style="margin-left:2em; margin-right:2em;">

<p>
<?php
	backToSermonsTalksPage();
?>
</p>





<p>
  <b>Things could not get worse</b>
  <br />
  <br />
  <b>What Is Our Problem ? &nbsp;&nbsp;   Romans 1: 18-32</b>

</p>

<p>
How would you describe the human situation? At my
Secondary School on Friday mornings we had hymn
singing. This always included the practice of the
School Hymn. The school was built in 1960 and so
fitting with the times we had a very optimistic hymn.
I can't remember much of the hymn now, but I do know
that it began "These things shall be a loftier race,
then 'ere the world hath known, the light of science
in their eyes". It  was a hymn about all how wonderful
the future would be because we were pupils of Tapton
Comprehensive School and would make it a better place!
</p>

<p>
We carried on singing it for a few years then it
seemed to get dropped. One Teacher, with a very sharp
mind, said to us as a class "where are these loftier
things then?".  She was saying that this hymn was
really a nonsense. Actually she was a Christian and
saw that the  hymn was a lie. For all the optimism of
the 1960's the world was not a better place. What is
the human situation? What are people really like? Are
we fundamentally good with just a few bad apples and
getting better and better?
</p>

<p>
The Book of Romans is a book that begins by asking
this question. And it has a shocking answer. Whilst
the Gospel is undoubtedly good news, indeed the best
news that one could ever hear, Paul's description of
this life changing message begins with two and half
chapters of bad news piled on bad news. The human
situation is bad, very, very bad indeed. After his
introduction he begins in 1:18 with these words, "the
wrath of God is being revealed by Heaven against all
the Godlessness and wickedness of men".
</p>

<p>
You may wonder is that really an accurate description
of mankind? Are we really so Godless and wicked? The
story of Karl Barth, a Swiss theologian born about
1880 shows how one man was forced to change his views
about human nature. He was bought up in a time of
great optimism. People thought that mankind through
science could conquer and improve everything. But then
the First World War came. People saw afresh the depths
of mankind's evil.
</p>

<p>
A few years after the end of the War Winston Churchill
described the moral catastrophe of World War One in
these words "the wounded died behind the lines; the
dead mould into the soil.hospital ships were sunk.and
all on board were left to their fate or killed as they
swam.effort was made to starve whole nations into
submission without regard to age or sex.poison gas in
all its forms stifled or seared the soldiers. Liquid
fire was projected upon their bodies." He concludes
this rather sobering assessment with these words "when
all was over torture and cannibalism, were the only
two expedients of civilised scientific Christian
states had been able to deny themselves, and they were
of doubtful utility". (Quoted in Paul Johnson, Modern
Times p.13-14).
</p>

<p>
Faced with that reality of evil, Barth, had to
reassess the optimistic Christian teaching he had been
brought up with and the view that mankind wasn't
really that bad. He came to write a commentary on the
Book of Romans. There he realised  our fundamental
relationship with God was one of ungodliness, for  "we
assume that he need something..we assume that we are
able to arrange our relationships to Him as we arrange
our other relationships.we dare to deck ourselves out
as His companions, patrons, advisers etc.secretly we
assume we are ourselves maters in the relationship. We
are not concerned with God but our
requirements.against such rebellion can only be
revealed the wrath of God".
</p>

<p>
What he was saying is that we dare to imagine
ourselves as equals with God or at least not far off.
We imagine that in someway we have a claim on him and
that he owes us something. Barth came to realise our
relationship to God and His Gospel is not like a
landing strip welcoming in an aircraft; no the Gospel
lands like a bomb and makes a crater. It demolishes
any thought of an idea that God owes us anything at
all, it destroys our idols.
</p>

<p>
The anger of God is not a popular subject, but a
thoroughly biblical one. It is there throughout the
Old Testament and the rest of letters of the New
Testament. It is also very much present in the
teachings of Jesus. We read in Luke 12 :5 these words
"fear him who after killing of the body has the power
to throw you into hell". Why does this happen? It
happens as a result of Gods anger at sin. If you
remove the anger of God from the Bible you end up with
a holely Bible;  that is a book full of gaps.
</p>

<p>
You cannot have Christianity without the wrath of God
because it is part of His  character. He is good and
morally prefect and the wrath of God is a right to
reaction of evil. Gods anger is personal. It is not
just a natural working out of moral laws in a sort of
impersonal scientific way. No it is His anger at sin.
Note  how Paul describes it as the wrath of God.
</p>

<p>
When we talk about the anger of God we must remember
too that this is not like human anger. It is not as if
God is bad tempered and out to get his own back. No
Gods anger is totally just and right. See is v18 and
all that follows in this chapter is directed against
"Godlessness and wickedness".
</p>

<p>
 <b>WITHOUT EXCUSE - v. 19-20</b>
</p>

<p>
God is right to be angry because it is clear to anyone
who looks that he exists. The vastness of Creation
says that there must be an eternal and almighty power
behind it. The fact that the Universe has a beginning,
scientists call it The Big Bang, means that it must
also have a beginner ie one to start in the first
place. And so we see at the end of verse 20 that
anyone who excuses his rebellion against God by saying
"God does not exist" intellectually does not have a
leg to stand on!
</p>

<p>
In practice that seems to be born out. Most people
believe in some sort of God though it may not be the
God of the Bible and they may not follow him. There
are very few real atheists. The idea that people are
without excuse may be a surprise or come as an
offensive shock to you. We tend to think that when
people have problems believing,  the problem is
primarily one of the mind, ie it is an intellectual
problem. We think that if we reason well enough with
them they will come to believe. No doubt people do
have some real questions that make some people doubt.
And indeed we may have had such questions in the past
or may yet have to face in the future. However in the
end the actual real problem  is that we don't want to
believe and acknowledge God as King and Lord of our
lives. Aldous Huxley, author of Brave New World and
an agnostic said "I had reasons for not wanting the
world to have a meaning. Consequently I assumed that
it had one". In  other words he did not come to the
conclusion "there is no God" after lots of in  depth
thinking and research, rather he decided beforehand he
would prefer if these was not a God or a meaning and
started his reasoning from there. Most people might no
be as blatant as Huxley, but we all have the same
motive at work inside us, a desire to avoid God's
rightful rule over our lives. We are without excuse
for sin.
</p>

<p>
 <b>WITHOUT WISDOM   v. 21-23</b>
</p>


<p>
We all probably know the story of Jack and Beanstalk.
Jack swapped a cow for a few useless beans, only they
turned out to be magic beans. What however if the
beans hadn't been magic? Then Jack really would have
been a fool. The situation of the human race is that
we have taken part in a great swap, a great exchange,
only unlike Jack we have swapped something far more
valuable - a relationship with God for something even
more useless than even plain or magic beans. At least
you can eat beans but sin leads to death.
</p>

<p>
Here Paul has been describing the human race in
general and so  we see what generally happens when
people choose to stop worshipping God. He writes in
verse 21 "their thinking became futile". That is their
way of reasoning becomes one which is going nowhere
and has no purpose. If we look in verse 23 we have an
idea what this means in practice  - "and exchange the
glory of immortal God for images made to look like
mortal man and birds and animals and retiles". Instead
of worshipping an almighty, all powerful all glorious
God who knows everything and is perfectly good the
people instead worshipped man made images not even the
real thing! It is a foolish and stupid exchange.
</p>

<p>
We may think  that sort of idol worship  may sound
very distant, but an idol may be any controlling power
that we give our loyalty to before God. A Missionary
in the Far East was talking to a man about his faith.
The man worshipped an idol in the form of a statue.
One day the man came in to talk and put two items on
the table one was a statue of his God and by that he
wrote on a piece of paper he my god. He then placed a
silver coin on the table and next to that he wrote
Christian God.
</p>

<p>
This is the mistake that many in our western world
have made. We have rejected a God who says "come to me
all who are weary and burdened and I will give you
rest" Matthew 11 verse 28. Instead we have chosen a
frantic chase after more and more little lumps of
metal and fancy bits of water marked paper and A7
sized pieces of plastic. Our thinking has become
futile.
</p>

<p>
 <b>WITHOUT PROTECTION v. 24-25</b>
</p>

<p>
Everyone worships something and if today if it is not
God or money it is probably sex. In v. 24 Paul writes
"therefore God gave them over in the simple desires of
their hearts to sexual; impurity for the degrading of
their bodies with one another". It was written
nineteen hundred and forty years ago and yet is still
very much today.
</p>

<p>
Again it is the same foolish swapping of God that is
true for something that is false. If you look here in
v. 24 (and again in v. 26 and 28) you will see  this
happening because God has allowed it. Paul writes "God
gave them over". This does not mean that God has given
them up for ever? rather it is if someone is pulling a
heavy boat upstream and then lets the stream carry it
away. It is the stream that carries the boat away not
the man who lets go. Here what we have is the removal
of God's restraint and protection. Is the cruel and
unfair of God? Or is rather that he has allowed a man
to go his own way, so maybe he when he sees the mess
that sin causes he will turn back and seek God again?
</p>

<p>
 <b>WITHOUT SHAME - v. 27-28</b>
</p>

<p>
It says in the proverbs that "Where there is no
revelation people cast off restraint". When people
reject God in the end anything goes. And so we read in
verse 27 "in the same way the man also abandoned
natural relations with women and were inflamed with
love for each other". Why is it that Paul mentions
homosexuality at this point? Has he gone off on a bit
of a tangent? Or perhaps it fits very well into his
overall argument?  When people give up worship of
God,  the ultimate object that often replaces God as
the centre of worship is ourselves. Perhaps
homosexuality here represents an extreme form of self
worship.
</p>

<p>
On this subject we need to remember two things.
Firstly the Word of God then is as much the Word of
God now. God's righteousness is not a pot of clay
moulded conveniently to fit the concerns of our age.
People may struggle very deeply with their sexuality
and can find such things deeply disturbing. They need
our support. However our feelings and desires are not
the basis of what is right and wrong. We see and hear
that these problems have their root in the rejection
of the revelation of God. Many people feel strange
things, not just homosexual urges, but that does not
make it in any way right.
</p>

<p>
Secondly we need to be careful ourselves. Paul makes
it quite clear that we all stand under God's anger. We
must not judge those who  struggle with homosexuality
as in any way worse.  God's wrath is revealed against
mankind as rebellion and that includes all whether nor
not it is our problem. And so we look on in the
passage we see that a world without God becomes a
world without shame and without boundaries. Look on in
verse 29 to 31 we see here how evil affects every part
of who we are. When we turn our backs on God,  the
World becomes a bad, a very bad place. Look at what we
have here, murder, God hating, depravity, people who
event ways of doing evil, malice etc. It sounds pretty
bad doesn't it but actually it's worse. For if we look
closely it also includes greed, envy and boasting. We
use these  attitudes so much every day that we are
even persuaded they are virtues. They are  normal
basis on which most of our consumer society is based.
The advertising industry, in the UK  which is worth
about 10 billion pounds per year. Tucked alongside
these is the very acceptable sin of gossip.
</p>

<p>
 <b>WITHOUT A CHANCE verse 31</b>
</p>

<p>
Finally as a result of all this we are without a
chance. I did some research for  this Sermon and
watched half an hour of Big Brother this week. It is
full of some of the things in this passage. It is
sort of programme that is easy to watch from a
distance and think how bad, and I'm glad I don't do
that. However when I talk about sin and the fall and
Big Brother I am not just about sexual immorality
(though it is very much there) but strife, envy,
greed. malice, gossip and slander. All that agro is
the basic fuel that keeps this television programme on
the air year by year. We like to see it. Television
only works if we keep watching it and so often on
television our eyes approve what our mouths deny.
</p>

<p>
In a way that is a picture of all the things in this
passage. It is easy to read and stand at a distance
and say that's not me. However how many groups of
people are described in this passage? Just one.
Humanity is not divided into the really seriously bad
there are normal people like me and you. No this is a
description of all of us. As a result mankind faces a
crisis. As we read the middle of verse 32 "those who
do such things deserve death". We are without hope,
without God and without a chance.
</p>

<p>
 <b>CONCLUSION</b>
</p>

<p>
Do you realise how bad the human situation is?  The
starting point of mans relationship with God is one of
unrighteousness and we are God's enemies. Do we
realise that the wrath of God is being revealed
against the sin of all human kind?  I hope I have
explained this all to you very clearly. If I have then
having heard this you would either feel extremely
gloomy or joyful. If not either I have failed or you
have not understood.
</p>

<p>
The situation is bad but God has provided a way out.
God has provided a way out. God has provided a way of
being right with Him. We read in verse 17 "that a
righteousness has been revealed from God that comes by
faith". Just as we exchange the glory of God for idols
now God offers us a second exchange. My Son takes your
death and sin and in place gives you holiness and
eternal life. How do we obtain that? We cannot do
anything all we can do is simply trust in Christ as
the one who saves us and acknowledge him as Lord.
</p>


<p>
<?php
	print("<a href=\"" . $_SERVER['HTTP_REFERER'] . "\">Back</a>\n");
?>
</p>






<p>
<?php
	backToSermonsTalksPage();
?>
</p>


<!-- ========================================================================== -->
<!--                              End Text Section                              -->
<!-- ========================================================================== -->
</div>


<!-- ========================================================================== -->
<!--                          Start Footer Content Section                      -->
<!-- ========================================================================== -->
<?php
	include('footer.php');
?>
<!-- ========================================================================== -->
<!--                            End Footer Content Section                      -->
<!-- ========================================================================== -->


<!-- ========================================================================== -->
<!--                            End of CSS Layout                               -->
<!-- ========================================================================== -->
</div>  <!-- END <div id="maincontainer"> -->


</body>
</html>

