<?php
	/******************************
		Talk to MySQL
	**********************************/
	require_once("mysql.php");


	/******************************
		Start a session
	**********************************/
	require_once("session.php");
	$oSession = new session();
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 14/01/2005 -->
<head>
<title></title>
<?php
	require_once("nocache.php");	// Stop - hopefully - this page being cached
?>

<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta name="description" content="">
<meta name="keywords" content="">
<meta name="author" content="newey499@hotmail.com">
<meta name="generator" content="AceHTML 5 Freeware">


  <!-- CSS Includes -->
  <link rel="stylesheet" type="text/css" href="css/layout.css" >
  <link rel="stylesheet" type="text/css" href="css/church.css" >
  <link rel="stylesheet" type="text/css" href="css/slideshow.css" >
  <link rel="stylesheet" type="text/css" href="css/tooltip.css" >
  <link rel="stylesheet" type="text/css" media="print" href="css/print.css" >
  <link rel="stylesheet" type="text/css" href="css/cssdropdownmenu.css" />
  <!-- End CSS Includes -->

</head>
<body>

<?php
	require_once("mysql.php");
	require_once("globals.php");
	require_once("genlib.php");
?>

<!-- ========================================================================== -->
<!--                            Start of CSS Layout                             -->
<!-- ========================================================================== -->
<div id="maincontainer">

<!-- ========================================================================== -->
<!--                             Start Top Section                              -->
<!-- ========================================================================== -->
<div id="topsection">
<div class="innertube">

<!-- Top Banner for site -->
<?php
	include_once("topbanner.php");
?>

</div>  <!-- End <div class="innertube"> -->
</div>  <!-- End <div id="topsection"> -->

<!-- This extra pointless div is needed to get IE out of the crap -->
<!-- Without it the top banner is not displayed                   -->
<!--[if IE ]>
	<div>
	</div>
<![endif]-->


<!-- ========================================================================== -->
<!--                               End Top Section                              -->
<!-- ========================================================================== -->



<!-- ========================================================================== -->
<!--                              Start Text Section                            -->
<!-- ========================================================================== -->
<div style="margin-left:2em; margin-right:2em;">

<p>
<?php
	backToSermonsTalksPage();
?>
</p>





<p>

<h4>
23/03/2008
<br />
Christ Church Lye:  9 a.m. Holy Communion Easter Day
</h4>

</p>

<p>
Luke 24: 1 - 12
<br />
(1) We live today in a sceptical and cynical world; a world in which so many are suspicious of others and their motives. It seems to be assumed that almost anyone in authority, whether politicians, celebrities, captains of industry, or even lawyers, cannot be trusted to tell the truth, if that truth is inconvenient for them. At best, it's assumed that the truth they do tell is highly selective. It's a bit like the story that came out a few weeks ago, about the claim that pharmaceutical companies were only publishing studies that showed that their anti-depressants worked, and were ignoring those studies that suggested otherwise. The inconvenient can be "air-brushed" out of the story, so it's thought. Likewise, anyone who says, quite seriously, "Oh, I'm sure this story is true, because I read it in the papers and heard it on TV", would be looked upon as being a bit simple in the head.
</p>

<p>
(2) So it's perhaps not surprising if we find it hard-going to persuade others of the truth-claims of the Christian faith. Most people, I guess, would accept that a man called Jesus of Nazareth walked this earth a couple of thousand years ago. But they're probably not prepared to sign up to more than that as established fact. So, the person of Jesus remains just an historical figure, of little or no relevance to us today and certainly of no help to me in improving my lifestyle or giving me reasons to go on living.
</p>

<p>
(3) When we come to the heart of the good news about Jesus - his death on a cross for the sins of the world, and his resurrection to prove that he had won our salvation - that's when today's scepticism and cynicism is at its toughest to break through. "You don't believe these fairy-stories, do you? Science shows that dead men don't come back to life. These are just tales the church - the evil clerics - added on later to keep people in its power; having to believe six impossible things before breakfast every day. You must be gullible to believe all that. Where's the evidence? Aren't you just taking a massive, blind step of faith? And didn't the "Da Vinci Code" show that the church was covering up inconvenient facts, which show that your faith is founded on a lie? I daresay at times most of us have heard some of these opinions voiced, whether directly to us or on TV.
</p>

<p>
(4) It's important that we, as Christ's followers today, respond to comments such as these: First, because, if we don't, not only are people going to miss hearing the good news that can transform their lives and their futures, but eventually the Christian message will disappear from the public life of this country. We cannot rely on the BBC or other broadcasters to screen further programmes like "The Passion" if no one is prepared to speak up for the Christian faith. Second, it's important that we do speak up because the story of Jesus we read in the gospels is true! Jesus really did come to earth; he really did die on the cross for our sins; and he did rise again to live for ever. Therefore, he achieved what he set out to do when he came - to open the door to salvation and fellowship with God for all who believe in him. Thirdly, it's important that we speak up because there is evidence for the truth of these claims, credible evidence on which we can rely, and we should make abundantly clear what that evidence is.
</p>

<p>
(5) Today's reading from Luke's gospel forms part of the evidence that the truth claims for the gospel can be, and should be, taken seriously. One reason for this, I believe, is that the accounts in the four gospels sound genuine, and not made up to fit in with a pre-determined idea or policy. Surely, if someone wanted to build a new movement around a central character featured in some sort of saga, they could have composed a smoother story in which the coming to life of our hero was so clear and obvious that it immediately convinced and transformed all who heard the message. Unfortunately, real life is seldom like that; it's rather messy and things don't always go according to plan.
</p>

<p>
(6) Luke was prepared to "tell it like it is", including the inconvenient bits. This was apparent in the introduction to his gospel, when he stated that he had "carefully investigated everything from the beginning" and then wrote "an orderly account" of what he had observed. So it is that when we come to Luke's account of Jesus' burial after his crucifixion, no one had any thoughts of any other possibilities except that Jesus was dead. despite the fact that, on their journey to Jerusalem, reported in chapter 18, and after Peter's confession, reported in chapter 9, Jesus had told his disciples that he would be killed but then raised from the dead. These were ordinary folk, but they weren't simple. They knew that dead men don't rise just as clearly as any sceptic of the technological 21st century knows. This is the first piece of evidence for Easter that I want to put before you this morning.
</p>

<p>
(7) Now we move into chapter 24 verse 1, at the start of the Sunday morning after the Friday before. The women who had been with Jesus throughout his crucifixion took their first opportunity to finish properly the anointing of his body. That's what they expected to be doing that morning. But they were taken aback by what happened when they arrived at Jesus' tomb, the tomb they had carefully marked out on the Friday evening when his body was laid inside: My second piece of evidence was what greeted them, in verses 2 and 3 - the massive round stone that had sealed the tomb had been rolled back, and when they went in they couldn't find the body. This negative piece of evidence - the absence of Jesus' body - features in all four gospel accounts. On its own, it doesn't prove anything, as it is hard to establish a position or a theory from the absence of data; it certainly didn't convince the women of Jesus' resurrection, as verse 4 tells us that they were wondering about what they had seen. However, no one has come up with evidence to support a credible explanation for the absence of Jesus' body, except that he had come back to life. And that explanation is supported by the next bit of evidence, which is of a positive nature, this time: In verses 3 to 8, the women were confronted by two strangely dressed men, who told them that they were wasting their time looking for Jesus: "He is not here; he has risen!" Then the strangers reminded them that Jesus had told them about his resurrection earlier on, in Galilee. Then it all came back at last, the penny dropped, the women must have been "gobsmacked".
</p>

<p>
(8) So, you see, evidence can be important in changing a person's mind - that is, if they are prepared to have their mind changed. What seemed to have done it for the women involved three types of evidence:
<p>
(a) the evidence of their own eyes: here, the negative evidence of the empty tomb.
<br />
(b) the evidence of others: here, the two strangers.
<br />
(c) the evidence of Jesus' words.
</p>
None of these pieces of evidence on its own may have convinced the women: they were puzzled about what the empty tomb might mean; the strangers' message might on its own have sounded unbelievable, and they had forgotten what Jesus had told them. However, taken together, the evidence appeared to have brought them round to believing the unbelievable. From there, it would have been quite natural to go and tell others, which is what we read in verses 9 to 12.
</p>

<p>
(9) In a made-up story one might expect the problem of Jesus' death to have been sorted out by the women's news: they come back with their astounding and all-powerful news, that Jesus is alive after all, the disciples believe them and are over the moon, and the Christian church begins its new life. Maybe that's what some think the gospels tell us, and understandably react in a sceptical way, thinking that the story makes the disciples out to be a bit naive and is too simplistic to believe anyway. But that's not what Luke's record tells us. The disciples were rather hard-headed - stubborn some might say - and refused to believe the women's story. Maybe this was because the women were so excited that bits of their news came out in an incoherent way, and they were a bit emotional - and we blokes don't do emotion too much, do we? Or maybe it was because they were women, and men at that time took what a woman said with a pinch of salt.  Whatever the case, the disciples rubbished the story. Sounds realistic, doesn't it?
</p>

<p>
(10) Now, had that refusal to believe the women's story ended the matter, the history of the world would have developed in a totally different way, and we wouldn't be here today. But something about the news got to Peter. He wanted so much to find out for himself what it was the women had seen, that he ran to the tomb, and found it empty, just as the women had said. But the evidence still wasn't enough to command his belief. As verse 12 ended, "he went away, wondering to himself what had happened."  It was not until he had met the risen Jesus for himself that the evidence for the resurrection was so conclusive that Peter believed and in due course had his life transformed.
</p>

<p>
(11) A train of events like this could well reflect our experience as we share the Easter story with others who are not yet Christians. We could well meet with scepticism or outright rejection as we give what we think is powerful and convincing evidence for the reality of Christ in today's world. But, even though that might be the initial reaction, this evidence could well trigger a response in our friends or neighbours that moves them to check out this "Jesus thing", so that they don't just hear words about him, but meet up with him for themselves.
</p>

<p>
(12) So, what we have in Luke's gospel, and in the other gospels, is a story of unfolding evidence that Jesus has indeed risen from the dead, just as he had predicted to his disciples. Some of this evidence is negative - the empty tomb - some is positive - strangers telling the women that Jesus had risen. Along with Jesus' own words, the evidence makes up a coherent whole, but was not enough to convince some of the disciples. But the cumulative evidence convinced at least one man - Peter - that it was worth a further look - And as the story unfolds and Peter and the others find out the truth for themselves by meeting the risen Christ, I would maintain that this account of Luke's carries all the hallmarks of a true story of events that really happened. Furthermore, I know it's true, for I have met the living Lord Jesus myself. He really does live! And the evidence for it found in the gospels can be relied on and passed on with confidence.
</p>

<p>
Alleluia! The Lord is risen!
<br />
He is risen indeed! Alleluia!
</p>

<p>
Rev Dr Chris Kent
</p>


<br />





<p>
<?php
	backToSermonsTalksPage();
?>
</p>


<!-- ========================================================================== -->
<!--                              End Text Section                              -->
<!-- ========================================================================== -->
</div>


<!-- ========================================================================== -->
<!--                          Start Footer Content Section                      -->
<!-- ========================================================================== -->
<?php
	include('footer.php');
?>
<!-- ========================================================================== -->
<!--                            End Footer Content Section                      -->
<!-- ========================================================================== -->


<!-- ========================================================================== -->
<!--                            End of CSS Layout                               -->
<!-- ========================================================================== -->
</div>  <!-- END <div id="maincontainer"> -->


</body>
</html>

