<?php
	/******************************
		Talk to MySQL
	**********************************/
	require_once("mysql.php");


	/******************************
		Start a session
	**********************************/
	require_once("session.php");
	$oSession = new session();
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 14/01/2005 -->
<head>
<title>Christ Church, Lye, West Midlands. UK</title>
<?php
	require_once("nocache.php");	// Stop - hopefully - this page being cached
?>

<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta name="description" content="">
<meta name="keywords" content="">
<meta name="author" content="newey499@hotmail.com">
<meta name="generator" content="AceHTML 5 Freeware">

  <!-- CSS Includes -->
  <link rel="stylesheet" type="text/css" href="css/layout.css" >
  <link rel="stylesheet" type="text/css" href="css/church.css" >
  <link rel="stylesheet" type="text/css" href="css/slideshow.css" >
  <link rel="stylesheet" type="text/css" href="css/tooltip.css" >
  <link rel="stylesheet" type="text/css" media="print" href="css/print.css" >
  <link rel="stylesheet" type="text/css" href="css/cssdropdownmenu.css" />
  <!-- End CSS Includes -->

</head>
<body>

<?php
	require_once("mysql.php");
	require_once("globals.php");
	require_once("genlib.php");
?>

<!-- ========================================================================== -->
<!--                            Start of CSS Layout                             -->
<!-- ========================================================================== -->
<div id="maincontainer">

<!-- ========================================================================== -->
<!--                             Start Top Section                              -->
<!-- ========================================================================== -->
<div id="topsection">
<div class="innertube">

<!-- Top Banner for site -->
<?php
	include_once("topbanner.php");
?>

</div>  <!-- End <div class="innertube"> -->
</div>  <!-- End <div id="topsection"> -->

<!-- This extra pointless div is needed to get IE out of the crap -->
<!-- Without it the top banner is not displayed                   -->
<!--[if IE ]>
	<div>
	</div>
<![endif]-->


<!-- ========================================================================== -->
<!--                               End Top Section                              -->
<!-- ========================================================================== -->



<!-- ========================================================================== -->
<!--                              Start Text Section                            -->
<!-- ========================================================================== -->
<div style="margin-left:2em; margin-right:2em;">


<!-- Top Banner for site -->
<?php
	include_once("topbanner.php");
?>

<br />


<p>
<?php
	backToSermonsTalksPage();
?>
</p>


<!-- ========================================================================== -->
<!--                              Start Content Section                         -->
<!-- ========================================================================== -->


<h4>
﻿The Fall. by Jim Ford.
</h4>


<p>
I parked the car opposite the Three Sisters in Glen Coe. It was a beautiful day, the sky was blue with a few white fluffy clouds. I walked up and over Bidean nam Bian and along the ridge down to the beallach aiming for the  summit of Stob Coire Sgreamhach. (bealach - low point or saddle between summits). The walking had been tough and in parts I was definitely out of my comfort zone. The snow was extensive over about 2000 feet but at this time of year, it was April, it was very soft, not slushy, but not crisp and icy as it is in mid-winter. I was told later that snow on mountains can be particularly hazardous in spring, a fact I learned the hard way! Snow in winter allows you to dig in with your crampons and ice axe, and secure a firm hold, so that slopes can be safely traversed or ascended and descended.
</p>

<p>
There were a couple of other blokes going along the same route as me but were quicker so were at different stages along the way. One was just about to go over the edge of the beallach and we discussed what might be the safest way down the very steep snow slope below the edge. Sliding on ones bottom and digging in feet might work! I carried on up to my last summit occasionally looking back to see how the young fellow was getting on. It was very slow but he was descending safely. I lost sight of him and carried on up, reached the summit and returned to the beallach to attempt
the descent. I put on my crampons, rucksack on my back and walking poles in my hands. I sat on the edge, dug my heels in and slid forward.
</p>

<p>
WHOOSH! I was sliding, twisting and turning, totally out of control, zooming down the snow slope, thinking WHAT THE . . . .! Did my life flash before my eyes? Well no it didn’t. I think I was trying to work out what to do to stop myself falling. I was totally disorientated and could not focus on my surroundings. I might as well have been free falling in a pitch black void. I thought that I might arrest my fall by digging in with my walking poles, then I thought that I ought to just relax and go limp. This was all in a matter of seconds of course, I probably fell about 100 feet, in 10 or so seconds? I thought I heard my walking pole zoom past my left ear, a metallic sound on ice, but on reflection, much later, I think it was the sound of my shoulder cracking. Anyway, I suddenly cried out WELL GOD, COME ON THEN!
He responded immediately. Within a second or two I was lying flat, with my face in the snow, feet down the slope, feeling my clothes wet and not knowing what or where I was. I just stared into the snow. My nose feeling the coldness of its surface. My lips tasting the freshness of the flakes as they melted in my mouth. My breathing was fast and erratic, not

gasping for air, more deep sighing with relief, I suppose. My heart was pounding but as the minutes went by, and it was several minutes, my body calmed and I gradually became aware of my surroundings. I gingerly lifted my head and looked back up the slope, it was just as steep looking back up it as it was looking down it a few minutes before, perhaps even steeper. I looked to my left and to my right, snow and more snow. The sky was still blue and it was still a lovely day.
My left arm was hurting; must have pulled something! I had also lost a walking pole, it went flying down the mountain. I’d only bought the poles last month after my other pair had broken, more expense! Dare I turn over and look down the slope? Not feeling very confident, still very steep. Relax a bit more, gather my thoughts. Plan of action? Turn on side, left leg over, dig heel in, over onto bottom, dig right heel in, sit up. Ok, do it. Did it slowly, looked around and took stock! Where am I, what to do? Arm sore! Do what I was supposed to do at the top, sit and dig heels in and gradually shuffle down on my bottom. Use remaining pole to give extra support against the slope. Dig in pole, then left heel, then right heel, slide bottom to heels. A long way still to go, will take ages, never mind, must be safe.
Ten or so minutes of slip sliding I began to feel sick and was retching
up bile or something, so I paused for a couple of minutes. Not sure what that was all about! I got to a position where the slope was gentle enough to stand up and walk the rest of the way down. Carefully I got to my feet and stood still for a few seconds to get my balance. My bottom was so cold and wet that I had no sensation in it. My hands were just as numb even though I had gloves on. I managed to get moving and walked towards the lower limit of the snow and began looking for the path which was shown on the map, so I knew that it was there somewhere, but it was covered by patches of snow. My arm was hurting a lot and it did cross my mind about having it examined at the hospital in Fort William. Anyway, I needed to find this path. I walked to the left, rocky edges means scrambling. To the right was too steep so I figured that the path must be down the middle, but where? Come on Lord! Where is it? I’m not fit to scramble off, I need Your help please!
Just to the edge of the snow I saw a patch of gravel, and then a bit more. Thank you Lord, it was the path. I knew it wasn’t going to be an easy path, but at least it was taking me in the right direction. I looked back up at the snow slope and sighed a sigh of relief. Thank you Lord. I also saw a couple of people, I had met earlier, attempting to come off the edge of the beallach. The path led me down the glen into an area known as a secret


valley. A place where cattle rustlers used to hide their stolen beasts from the authorities. I saw what I thought was someone dressed in red sitting on a rock at the end of the valley area. It turned out to be a red tent where a bloke and his two teenage children were preparing to spend the night. They were trying to light a wood fire which was giving off a wonderful smell into the late afternoon air. I had a chat with them, wished them well and the man said that he hoped that I got my arm sorted out ok. He told me that the rest of the path wasn’t too bad, just a tricky stream crossing to negotiate.
</p>

<p>
I was really taking my time, my arm was next to useless and I certainly didn’t want to slip again. The stream was fast flowing, about 10 yards wide and 3 or 4 feet deep in places. I searched the bank and found a suitable place to cross and managed to get to the other side without too much difficulty. The worst part of the walk off was when I came across a fallen tree which was blocking the path. I couldn’t get over it with only one hand, so I had to wriggle under it. I sat down on the path, in a flow of water, and squeezed myself under the log. It was a nightmare, the pain in my arm was excruciating! Despite the difficulties I actually felt quite peaceful and was enjoying, in an odd way, the plod towards my car far below in Glen Coe.
</p>

<p>
I eventually reached the car at 7.15. It had taken me almost 4 hours to get there after my fall. I decided that I must go to A & E in Fort William. My clothes were soaking wet and smelly so, with great difficulty, I changed them. This meant that I would get warm more quickly and also be kind to the nurses at the hospital. I drove the 20 miles or so, changing gear with great difficulty, getting to the hospital at about 8pm. The doctor thought that I may have torn a muscle but an X-ray revealed an avulsion fracture (bone torn away) at the top of my humerus.
</p>

<p>
My wife had to come from the Midlands on the train so that she could drive me home. I had an operation on my arm where a screw and plate were inserted and the muscle repaired. I was to wear a sling for 6 weeks.
</p>

<p>
Reflections.
</p>

<p>
Should a person walk alone on mountains? There is much to be said for experiencing the solitude found in such wild and remote places. From a safety point of view, it can be argued that one should be in a group of at least three. As a Christian, I believe that I am never alone, God is always with me. However, we should take proper safety precautions and not take Him for granted. I had all the correct gear and am experienced in winter walking in Scotland. I slipped and fell, an accident, my mistake, nothing to



do with God. I cried out to Him in my time of desperation and He responded and saved me, from what? One can only imagine!
As I plodded from the mountain it felt as though God was guiding me to safety. As I mentioned earlier, I felt at peace. This was, perhaps a feeling of relief at surviving the fall but was mixed with a sense of divine intervention, of God’s presence. A nurse at the hospital observed that I had rescued myself from the mountain, but I believe  that I was rescued by God!
</p>




<!-- ========================================================================== -->
<!--                                End Content Section                         -->
<!-- ========================================================================== -->


<p>
<?php
	backToSermonsTalksPage();
?>
</p>


<!-- ========================================================================== -->
<!--                              End Text Section                              -->
<!-- ========================================================================== -->
</div>


<!-- ========================================================================== -->
<!--                          Start Footer Content Section                      -->
<!-- ========================================================================== -->
<?php
	include('footer.php');
?>
<!-- ========================================================================== -->
<!--                            End Footer Content Section                      -->
<!-- ========================================================================== -->


<!-- ========================================================================== -->
<!--                            End of CSS Layout                               -->
<!-- ========================================================================== -->
</div>  <!-- END <div id="maincontainer"> -->


</body>
</html>

