<?php
	/******************************
		Talk to MySQL
	**********************************/
	require_once("mysql.php");


	/******************************
		Start a session
	**********************************/
	require_once("session.php");
	$oSession = new session();
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 14/01/2005 -->
<head>
<title></title>
<?php
	require_once("nocache.php");	// Stop - hopefully - this page being cached
?>

<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta name="description" content="">
<meta name="keywords" content="">
<meta name="author" content="newey499@hotmail.com">
<meta name="generator" content="AceHTML 5 Freeware">


  <!-- CSS Includes -->
  <link rel="stylesheet" type="text/css" href="css/layout.css" >
  <link rel="stylesheet" type="text/css" href="css/church.css" >
  <link rel="stylesheet" type="text/css" href="css/slideshow.css" >
  <link rel="stylesheet" type="text/css" href="css/tooltip.css" >
  <link rel="stylesheet" type="text/css" media="print" href="css/print.css" >
  <link rel="stylesheet" type="text/css" href="css/cssdropdownmenu.css" />
  <!-- End CSS Includes -->

</head>
<body>

<?php
	require_once("mysql.php");
	require_once("globals.php");
	require_once("genlib.php");
?>

<!-- ========================================================================== -->
<!--                            Start of CSS Layout                             -->
<!-- ========================================================================== -->
<div id="maincontainer">

<!-- ========================================================================== -->
<!--                             Start Top Section                              -->
<!-- ========================================================================== -->
<div id="topsection">
<div class="innertube">

<!-- Top Banner for site -->
<?php
	include_once("topbanner.php");
?>

</div>  <!-- End <div class="innertube"> -->
</div>  <!-- End <div id="topsection"> -->

<!-- This extra pointless div is needed to get IE out of the crap -->
<!-- Without it the top banner is not displayed                   -->
<!--[if IE ]>
	<div>
	</div>
<![endif]-->


<!-- ========================================================================== -->
<!--                               End Top Section                              -->
<!-- ========================================================================== -->



<!-- ========================================================================== -->
<!--                              Start Text Section                            -->
<!-- ========================================================================== -->
<div style="margin-left:2em; margin-right:2em;">

<p>
<?php
	backToSermonsTalksPage();
?>
</p>





<p>
  <b>The DaVinci Code - Is the Bible Reliable?</b>
</p>


<p>
E .M. Forster said "that the secret of writing a good
book is to make people want to keep turning to the
next page". That is certainly the case with The Da
Vinci Code. It is one of the best fiction books of all
time, having sold to date at least 50 million copies.
The book was described by the New York Times with
these words "intrigue and menace mingle with one of
the finest mysteries I have ever read. An amazing tale
with enigma piled on secrets, stacked on riddles ".
Alternatively some have read it and described it, a
little cruelly, as the "baddest,  bad bad book ever
written badly".
</p>

<p>
Whatever the literary qualities of the book, that is
not the issue I wish to discuss today. It is the
content. This causes concern to many people especially
Christians, root it is an attack on Christianity as we
know it. Let me summarize the plot. It begins with the
murder of a museum curator in the Louvre in Paris. In
his death throes, the man has left a coded message
scattered around the Museum. The story concerns the
unraveling of this code which reveals that Leonardo Da
Vinci (hence the title) and many other famous people
were members of a secret organisation,  The Priory of
Sion. This organisation holds the secret of the true
identity of Christ. He was not God, but just a man who
happened to marry Mary Magdalene. His bloodline
continues to this day amongst the descendants of the
Kings of France. The Bible has been tampered with to
suit the purposes of a male dominated Church. The
original goddess worship which Jesus persued with Mary
Magdalene has been suppressed and is only known to the
faithful few.
</p>

<p>
The book challenges many of the central tenets of
Christianity. For instance is the Bible true and
reliable? Is the text we have substantially what the
original writers wrote and is a true record of Jesus
Christ? It challenges who Jesus was. Did he really
claim to be God or is it a claim made up by the Church
later on for their own purposes? Did he marry Mary
Magdalene? Is the Church deeply corrupt and only run
by  people interested in preserving their own power?
</p>

<p>
Maybe these are questions you have or maybe not.
However at this moment I ask you not to switch of and
think I am not going to read the book or see the film
because I don't need to know. These are questions that
people have whether they have seen the film or read
the book or not. They are questions that people often
ask about Christianity. Today I want to look at the
first of those questions is the Bible reliable? I want
to briefly look at four peoples views and let you to
make up your own mind. They are Dan Brown, the Old
Testament writer King David, one of Jesus' closest
followers Peter and finally Jesus himself.
</p>

<p>
Dan Brown and the Bible.
Why do we have the  four Gospels? This is a good
question raised by the Da Vinci Code. One character
(Leigh Teabing) claims that "the Bible as we know it
was collated by the Roman Emperor Constentine.... he
commissioned and financed a new Bible which omitted
those Gospels which spoke of Christ's human traits and
embellished those Gospels which made him more Godlike.
(the Da Vinci Code p 313 - 317).  Perhaps at this
point in reading the book you may want to either a).
throw the book in the bin in disgust or b). think "Ah!
I always knew there was something really fishy about
this Christianity stuff - now what is the real
story."?
</p>

<p>
And indeed it is true that Archeologists have found
fragments, indeed sometimes quite large fragments of
ancient books purporting to be about Jesus. It is
estimated there are between 40 and 80 of these books.
They books claims to be Gospels. However before we
need go any further we need to ask a more basic
question, what actually is a Gospel? Many things are
called Gospels but simply to use the word Gospel is
misleading because there is great variety in styles of
this body of literature.
</p>

<p>
Imagine a two minute slot on the TV News about the
conflict in Iraq, is that a documentary? In a
documentary,  as a type of television programme we
would expect something reasonably long (half an hour
to an hour) and something that covers the subject in
depth, from the point of view of at least more than
one person. Not only that it would be a distinct
programme with an introduction, ending with credits
and probably some music. In the same way for a Gospel
to be reasonably described as a Gospel it should at
least have a basic outline of Jesus' life. Namely his
origins, life, teachings, miracles, death and
resurrection. That being so how do these alternative
Gospels match up?
</p>

<p>
There is not enough time to cover all the alterantive
Gospels in detail now but let us simply look  at one
of the  more widely known ones mentioned in the Da
Vinci Code. That is the Gospel of Thomas. It was found
in a jar in a field in Egypt in 1945 at Nag Hammadi.
It consists of a collection of a 144 possible saying
of Jesus. Some sayings are very similar to what we
have in the Gospels others are very different.
</p>

<p>
It is perhaps the differences that stand out more.
Firstly very few ancient manuscript copies of the
Gospel of Thomas exist. Amongst those that we do have
there is quite a lot of variation between the copies.
The copies we have are in Coptic (the land of ancient
Egypt) from about 400 AD, possibly translated from an
earlier but lost text written about 150 AD. This means
the text of the Gospel of Thomas has we have it today
may well be not quite what was originally written. In
contrast the text of the four most established Gospels
is very consistent and found in a very large numbers
of manuscripts hundreds - hundreds not tens. In
addition these manuscripts date from a much earlier
period,  closer to when the Gospels were originally
written.
</p>

<p>
Secondly the contents of the Gospel of Thomas are very
different from the four canonical Gospels. These all
follow a similar outline beginning with John the
Baptist, and then going on to look at Jesus' miracles
and teaching, his death and resurrection. There are
some differences in content and the stories are told
from different angles but they are essentially the
same story.
</p>

<p>
The Gospel of Thomas is very different. It contains
none of the above but rather is simply a collection of
sayings. It appears to be a rather random list of
possible sayings of Jesus. Some are very similar to
the Gospels, others very different and sometimes even
bizarre - eg Logion 7.  This reads as follows Jesus
said "lucky is the lion that the human will eat so
that the lion will become human. And foul is the human
that the lion will eat and the lion will still become
human".
</p>

<p>
As a whole, the Gosple of Thomas seems to read like a
rather bad version of the devotional aid 'Living
Light'. It is like a collection of favourite Bible
verses which have been written down from memory, but
not written not directly from the text and then
recopied the same way a few times. Jumbled in with
that is the odd bit of popular wisdom  such as,  "God
helps those who help themselves". The resulting text
is not particularly useful in understanding the
historic Jesus nor probably a particularly reliable
source of information about him. It is the echo of the
echo of the voice of Jesus.
</p>

<p>
A similar critique could be made of some of the other
purported Gospels of Jesus. Dan Brown begins his novel
with three statements which is claims are facts. At
many points his novel characters such as Leigh Teabing
discuss real documents and events. The question for us
is does he then   jump into speculation or is his
novel really based on fact.
</p>

<p>
 <b>David's View - Psalm 12.</b>
</p>

<p>
 This is a  prayer of David.  an Old Testament King of
Israel,  who is experiencing a situation in which  all
those around him seem to lie. It distresses him.
However in the midst of this he remembers "the words
of the Lord are flawless, like silver refined in a
furnace seven times" (v6). David remembers that when
God speaks he speaks the truth. The truth has a
quality and purity that goes way beyond anything that
we as human beings know. The picture he has is of
heating  silver ore in a  crucible. The rubbish and
impurities rise to the surface and are skimmed off.
Normally once is enough but when God speaks it is
absolutely pure and so here the process is repeated
seven times. Seven is a number often associated with
perfection in the Bible. David is saying there is not
even a hint of inaccuracy, mistake or exaggeration
that might be in human speech when God speaks.
This is because of the nature of God. The Bible is
reliable not because we can absolutely prove it is so
nor eliminate all errors but firstly because of the
character of God. You can argue over the Bible being
reliable,  however I believe it because firstly that
God is faithful and true. Since he is faithful and
true anything that comes from him has the same
qualities.
</p>

<p>
You might have spotted that this is a circular
argument. In other words the Bible is reliable because
God is faithful and true. How do we know that God is
faithful and true, because we read it in the Bible.
All our thinking is to  some extent circular. There
are assumptions that you can't prove and just take as
read.
</p>

<p>
I do not accept these assumptions because they are
plucked from mid air or it is convenient to see that
they are backed up by the way the world is. For
instance the existence of scientific laws suggests a
reliable and consistent creator. In addition the
events in the Bible are backed up by history and
experience. The character of Jesus is one of utter
faithfulness and truth.  He frequently quoted on and
based his arguments on the Bible. David thought the
Bible was a reliable pure truth from God - but what do
you think it is.
</p>

<p>
 <b>Peter's View - 2 Peter 1 verses 12-21B</b>
</p>

<p>
Peter was one of Jesus' closest followers in the
earliest days. In verses 13-14 he finds himself living
in a tent of his body which would soon be put aside.
He is referring to his imminent death. There is a very
strong church tradition that he is martyred in Rome,
about 65 AD under the Emperor Nero's persecution of
the Church. Even if that didn't happen it is very
clear that the early Christians such as Peter suffered
a lot by claiming that Jesus Christ had risen from the
dead, was the ultimate Lord and would come again to
judge the earth. Yet it is still possible that they
made all this up.
</p>

<p>
Peter however claims that he was an eye witness of
Jesus' life. He writes (verse 16) "we did not follow
cleverly invented stories when we told you about the
power and coming of our Lord Jesus Christ". He goes on
to mention his experience of seeing Christ's majestic
glory (verse 17) at the Transfiguration .Here he had a
glimpse into the future and the full glory of God to
be revealed in Christ. "The Glory of God" was used in
the Old Testament at times as a literary way of
expressing God himself. What Peter is implying here is
he believes that Jesus is God.
</p>

<p>
Peter and other New Testament writers, were eye
witnesses to the life, works and teachings of Jesus.
Two of the four Gospels, Matthew and John, were
written by people who were Jesus; Apostles, who spent
three years following Jesus around. Mark  very
probably got the information for his Gospel direct
from Peter.
</p>

<p>
They are not the only ones with this view of Jesus.
Through the previous 1500 years of history,  men,
called prophets had been looking ahead to the coming
of Jesus.   Peter explains their work in verses 20-21
"no prophecy of scripture came by the prophets own
imagination. For prophecy never had its origins in the
will of man. But men spoke from God as they were
carried along by the Holy Spirit". As scripture Peter
means primarily the Books of the Old Testament.
However if we go to 2 Peter we see here that Peter
brackets the writings of Paul in the same category as
the "other scriptures". (2 Peter 3: 16) His claim is
that the Bible was not complied as a result of messy
4th century imperial politics. Rather the Bible is
written by eye witnesses and people at the time
inspired by God. It comes from God. That was Peter's
view what is your view?
</p>

<p>
 <b>Jesus' View - Luke 24 v 36-49</b>
</p>

<p>
We now move on to Jesus' view of the Bible. It is the
evening of the first Easter Day. Jesus has risen from
the dead and appears to his disciples. They cannot
believe what they see,  even after touching and
feeling him. So he asks for a piece of fish and eats
it in their presence. What more proof could you need?
But Jesus has more to say to them.   He turns them to
Bible (v44-45), specifically the Law of Moses (that is
Genesis and Deuteronomy) the prophets by which he
means not just the prophetic books but also the
historical books.  He also points them to the Psalms,
being the Psalms, Proverbs, Job etc.  He is refering
to the whole of the Old Testament. As they look he
says to them effectively "if you want to understand me
this is the place to look". We say that   seeing is
believing.  Jesus claims that believing in the Bible
is as  reliable as seeing and touching him. The whole
of the Old Testament is the story of God's purpose and
history unfolding and reaching it's conclusion in
Jesus. It is not just a place to look but the place to
look.
</p>

<p>
 <b>Jesus says (v44)  "everything must be fulfilled".</b>
</p>

<p>
There is a certainty about the events predicted in the
Old Testament that is like anything else in human
experience. Because God speaks it will happen. When
God speaks it is different to when we speak for his
word perfectly expresses his will and being an all
powerful God nothing can stop that from happening.
If we want to understand Jesus, Jesus suggests that
the Bible is the book to look in. Dan Brown seems to
think otherwise. What do you think?
</p>

<p>
 <b>Conclusion</b>
</p>

<p>
I began with the quote   "the secret of a good book is
that you most want to keep turning the pages". Dan
Brown has written many other books and I think that
his first book Deception Point really is a page
turner. It turns a world changing scientific discovery
found under an ice sheet in the Arctic. As the plot
unfolds it turns out to be  not quite what it seems
but rather politicians manipulating the truth for
their own end. th ebook shows how when even scientific
fraud takes place it is shocking how easily people can
jump to conclusions and believe things because
everyone else believes. Yet when the characters in the
book look more closely they  see the truth is very
different.
</p>

<p>
Many people are very skeptical about Christianity
today and easily believe the things that Dan Brown
writes. Christianity seems old fashioned and people
believe that the Bible is largely made up, but when we
read the book itself and encounter Jesus we find
something else. When the Bible is read,  God speaks
and we encounter Jesus, we too can have an encounter
with him and he will transform our lives. Luke's
Gospel ends with Jesus ascension to heaven and records
"they worshipped him and returned to Jerusalem with
great joy" What will you experience be?
</p>








<p>
<?php
	backToSermonsTalksPage();
?>
</p>


<!-- ========================================================================== -->
<!--                              End Text Section                              -->
<!-- ========================================================================== -->
</div>


<!-- ========================================================================== -->
<!--                          Start Footer Content Section                      -->
<!-- ========================================================================== -->
<?php
	include('footer.php');
?>
<!-- ========================================================================== -->
<!--                            End Footer Content Section                      -->
<!-- ========================================================================== -->


<!-- ========================================================================== -->
<!--                            End of CSS Layout                               -->
<!-- ========================================================================== -->
</div>  <!-- END <div id="maincontainer"> -->


</body>
</html>

