<?php
	/******************************
		Talk to MySQL
	**********************************/
	require_once("mysql.php");


	/******************************
		Start a session
	**********************************/
	require_once("session.php");
	$oSession = new session();
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 14/01/2005 -->
<head>
<title></title>
<?php
	require_once("nocache.php");	// Stop - hopefully - this page being cached
?>

<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta name="description" content="">
<meta name="keywords" content="">
<meta name="author" content="newey499@hotmail.com">
<meta name="generator" content="AceHTML 5 Freeware">

  <!-- CSS Includes -->
  <link rel="stylesheet" type="text/css" href="css/layout.css" >
  <link rel="stylesheet" type="text/css" href="css/church.css" >
  <link rel="stylesheet" type="text/css" href="css/slideshow.css" >
  <link rel="stylesheet" type="text/css" href="css/tooltip.css" >
  <link rel="stylesheet" type="text/css" media="print" href="css/print.css" >
  <link rel="stylesheet" type="text/css" href="css/cssdropdownmenu.css" />
  <!-- End CSS Includes -->

</head>
<body>

<?php
	require_once("mysql.php");
	require_once("globals.php");
	require_once("genlib.php");
?>

<!-- ========================================================================== -->
<!--                            Start of CSS Layout                             -->
<!-- ========================================================================== -->
<div id="maincontainer">

<!-- ========================================================================== -->
<!--                             Start Top Section                              -->
<!-- ========================================================================== -->
<div id="topsection">
<div class="innertube">

<!-- Top Banner for site -->
<?php
	include_once("topbanner.php");
?>

</div>  <!-- End <div class="innertube"> -->
</div>  <!-- End <div id="topsection"> -->

<!-- This extra pointless div is needed to get IE out of the crap -->
<!-- Without it the top banner is not displayed                   -->
<!--[if IE ]>
	<div>
	</div>
<![endif]-->


<!-- ========================================================================== -->
<!--                               End Top Section                              -->
<!-- ========================================================================== -->



<!-- ========================================================================== -->
<!--                              Start Text Section                            -->
<!-- ========================================================================== -->
<div style="margin-left:2em; margin-right:2em;">

<p>
<?php
	backToSermonsTalksPage();
?>
</p>




<h4>When Did Jesus Live?</h4>

<p>
When did Jesus live? This may seem like a question too simple to be worth asking. But many people who are not Christains and know little or nothing about Christainity assume that the stories we have about Jesus are largely myths. We assume that since our system of dating the years begins with Jesus birth he must have been  born in 0AD. However the system for dating  was started many years after the birth of Jesus  by a Latin Monk Dionysius Exiguus in 531 AD.  He tried to work out the year of Jesus' birth but lacking all the information we now have, allmost certainly got it wrong.  We can tie in the major events of Jesus life with other historical sources and the Gospels themeslves give us a great deal of information.
</p>

<p>
The precise year of Jesus' birth is uncertain but we can have a better idea of when he was active in ministry. Luke records John the Baptist began preaching in the 15th year of the reign of the Roman emperor Tiberius (Luke 3:1). The previous emperor Augustu died on 1th August 14AD making the fifteenth year of his reign approximately 29 AD.  The approximation is due to differences in the way of counting the years of an emperors reign with different calendars.
</p>

<p.
When Jesus begins his ministry Luke records that Jesus was about 30 years old (Luke 3:23). A tradition of some Jewish rabbis gives Jesus the age 33-34 at this stage in his ministry which would mean he was born in 4/5 BC.  This fits in with astronomcal evidence. The conjunction of Mars,  Saturn and Jupiter in the sky  in 4/5 BC may have been the star that the wise men saw.  However there are other factors that make dating Jesus birth difficult.  There is  a lot of uncertainty about Quirius (Luke 2:2) - who he was and when he lived.
</p>

<p>
The ministry of Jesus lasted for 3-4 years. John's Gospel records Jesus visting Jerusalem for three passover feasts (John 2;13, 6:4, and 11:55).  When John's Gospel is read in the light of other three Gospels it seems that there might be a two year gap between the first  two passovers. This would put Jesus last passover and crucifixtion as taking place in Jerusalem in  33AD.
</p>

<p>
The Jewish historian Josephus records that all  the major officials who took part in Jesus' trial were in office at this time.  Caiaphas, the high priest was in office from 18AD until  37AD when he was deposed. Pontius Pilate was prefect of Judea from 26AD to 36AD. Herod Antipas (King Herod - Luke 23:6-12)  was  the tetrach of Galilee and Perea from 4BC to 39AD.
</p>

<p>
If someone asks you "when did Jesus live?",  from the sources we have,   4BC to 33AD is a fairly accurate answer.
</p>

<p>
So is the Gospel history or myth?  The question is not new. The early church lived in a confusing multireligious age full of rumour - and yet it thrived and grew. Peter wrote to the Christains living in the pagan culture of modern day Turkey with this advice "allways be prepared to give an answer to everybody who asks you to give  the reason for the hope that you have" 1 Peter 3:15.
</p>





<p>
<?php
	backToSermonsTalksPage();
?>
</p>


<!-- ========================================================================== -->
<!--                              End Text Section                              -->
<!-- ========================================================================== -->
</div>


<!-- ========================================================================== -->
<!--                          Start Footer Content Section                      -->
<!-- ========================================================================== -->
<?php
	include('footer.php');
?>
<!-- ========================================================================== -->
<!--                            End Footer Content Section                      -->
<!-- ========================================================================== -->


<!-- ========================================================================== -->
<!--                            End of CSS Layout                               -->
<!-- ========================================================================== -->
</div>  <!-- END <div id="maincontainer"> -->


</body>
</html>

