<?php
	/******************************
		Talk to MySQL
	**********************************/
	require_once("mysql.php");


	/******************************
		Start a session
	**********************************/
	require_once("session.php");
	$oSession = new session();
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 14/01/2005 -->
<head>
<title></title>
<?php
	require_once("nocache.php");	// Stop - hopefully - this page being cached
?>

<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta name="description" content="">
<meta name="keywords" content="">
<meta name="author" content="newey499@hotmail.com">
<meta name="generator" content="AceHTML 5 Freeware">

  <!-- CSS Includes -->
  <link rel="stylesheet" type="text/css" href="css/layout.css" >
  <link rel="stylesheet" type="text/css" href="css/church.css" >
  <link rel="stylesheet" type="text/css" href="css/slideshow.css" >
  <link rel="stylesheet" type="text/css" href="css/tooltip.css" >
  <link rel="stylesheet" type="text/css" media="print" href="css/print.css" >
  <link rel="stylesheet" type="text/css" href="css/cssdropdownmenu.css" />
  <!-- End CSS Includes -->

</head>
<body>

<?php
	require_once("mysql.php");
	require_once("globals.php");
	require_once("genlib.php");
?>

<!-- ========================================================================== -->
<!--                            Start of CSS Layout                             -->
<!-- ========================================================================== -->
<div id="maincontainer">

<!-- ========================================================================== -->
<!--                             Start Top Section                              -->
<!-- ========================================================================== -->
<div id="topsection">
<div class="innertube">

<!-- Top Banner for site -->
<?php
	include_once("topbanner.php");
?>

</div>  <!-- End <div class="innertube"> -->
</div>  <!-- End <div id="topsection"> -->

<!-- This extra pointless div is needed to get IE out of the crap -->
<!-- Without it the top banner is not displayed                   -->
<!--[if IE ]>
	<div>
	</div>
<![endif]-->


<!-- ========================================================================== -->
<!--                               End Top Section                              -->
<!-- ========================================================================== -->



<!-- ========================================================================== -->
<!--                              Start Text Section                            -->
<!-- ========================================================================== -->
<div style="margin-left:2em; margin-right:2em;">

<p>
<?php
	backToSermonsTalksPage();
?>
</p>





<p>
  <b>Were Adam and Eve Real Historical People</b>
</p>


<p>
The Bible begins with the  creation of universe and
the high point of this is the creation of man and
women- Adam and Eve.  The style of the first creation
story is unusual. It is highly repetitive (1) and
different in form to much in th rest of scripture. In
many ways it resembles a long and highly repetitive
hymn.  It is certainly not in the style of a
scientific report.  As such it does not have to be
seen as recording six literal days of creation in order
to be faithful to its original message. (2)
</p>

<p>
However does this mean that Adam and Eve are not to be
seen as actual specific individuals? Could they just
be symbols of our humanity?
</p>

<p>
Not without difficulty,  since their historicity seems
to be clearly supported from two New Testament
passages.  In Romans 5:12-21 Paul&apos;s argument about the
scope of Christ salvation depends on  a comparison
between the one man (Adam) and the one man Christ.
(3). When debating with the Athenian intellectuals ,
Paul speaks of how God &quot;from one man made every nation
of men.&quot; (Acts 17:26).
</p>

<p>
How then do we reconcile the claims of an evolutionary
understanding of the origins of man with the Genesis
account? Firstly there needs to be a certain degree of
caution as to the claims of evolution (4). The fossil
record for early man and related hominids has many
gaps and a limited number of specimens. Many of these
are limited to just a few bones.  Any detailed
explanation for our origins as homo sapiens in
scientific terms must be provisional.
</p>

<p>
Secondly there are some strands of evidence that point
to the authenticity of Adam.
<br />
1)  The technology and
lifestyle described in Genesis 2-4 resembles that of
what we know of Neolithic man (10,000-6,000 BC).
<br />
2)
Genetic evidence suggests that all living people today
are closely related and share a common ancestor (5).
<br />
3)  There is evidence in cave paintings and in the
burial of the dead of some development of spiritual
awareness in hominids in the period 40 -10,000 BC.
</p>

<p>
It is therefore not unreasonable to believe Adam and
Eve were special creations of God sometime in this
time period.
</p>

<p>
NOTES
<br />
<br />
1) e.g See how often we read the words &quot;And God
said..&quot;  or &quot;and there was evening and there was
Morning - the second/third...day&quot;
<br />
2) The idea that Genesis 1 does not have to be
interpreted as six literal days is not a modern
accommodation to the theory of evolution. Many
wondered long before the age of science as to meaning
of the days of creation. e.g  Augustine of Hippo (354
-430 AD)  &quot;What these days are is impossible for us to
imagine, to say nothing of describing them&quot;, City of
God:  Book XI,  Ch 6
<br />
3)  Romans 5:12, 15,17, 19.
<br />
4) Henri Blocher writes of evolution as a whole &quot;As a
large and flexible  paradigm or macro-model  it is
incapable of formal proof. It has shown itself able to
deal with a great many difficulties but many others
have not been solved.&quot;  Original Sin: Henri Blocher,
1997,  p39-40.
<br />
(5) See quote in Romans: John Stott, 1994, p 163
<br />

</p>









<p>
<?php
	backToSermonsTalksPage();
?>
</p>


<!-- ========================================================================== -->
<!--                              End Text Section                              -->
<!-- ========================================================================== -->
</div>


<!-- ========================================================================== -->
<!--                          Start Footer Content Section                      -->
<!-- ========================================================================== -->
<?php
	include('footer.php');
?>
<!-- ========================================================================== -->
<!--                            End Footer Content Section                      -->
<!-- ========================================================================== -->


<!-- ========================================================================== -->
<!--                            End of CSS Layout                               -->
<!-- ========================================================================== -->
</div>  <!-- END <div id="maincontainer"> -->


</body>
</html>

