<?php
	/******************************
		Talk to MySQL
	**********************************/
	require_once("mysql.php");


	/******************************
		Start a session
	**********************************/
	require_once("session.php");
	$oSession = new session();
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 14/01/2005 -->
<head>
<title></title>
<?php
	require_once("nocache.php");	// Stop - hopefully - this page being cached
?>

<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta name="description" content="">
<meta name="keywords" content="">
<meta name="author" content="newey499@hotmail.com">
<meta name="generator" content="AceHTML 5 Freeware">


  <!-- CSS Includes -->
  <link rel="stylesheet" type="text/css" href="css/layout.css" >
  <link rel="stylesheet" type="text/css" href="css/church.css" >
  <link rel="stylesheet" type="text/css" href="css/slideshow.css" >
  <link rel="stylesheet" type="text/css" href="css/tooltip.css" >
  <link rel="stylesheet" type="text/css" media="print" href="css/print.css" >
  <link rel="stylesheet" type="text/css" href="css/cssdropdownmenu.css" />
  <!-- End CSS Includes -->

</head>
<body>

<?php
	require_once("mysql.php");
	require_once("globals.php");
	require_once("genlib.php");
?>

<!-- ========================================================================== -->
<!--                            Start of CSS Layout                             -->
<!-- ========================================================================== -->
<div id="maincontainer">

<!-- ========================================================================== -->
<!--                             Start Top Section                              -->
<!-- ========================================================================== -->
<div id="topsection">
<div class="innertube">

<!-- Top Banner for site -->
<?php
	include_once("topbanner.php");
?>

</div>  <!-- End <div class="innertube"> -->
</div>  <!-- End <div id="topsection"> -->

<!-- This extra pointless div is needed to get IE out of the crap -->
<!-- Without it the top banner is not displayed                   -->
<!--[if IE ]>
	<div>
	</div>
<![endif]-->


<!-- ========================================================================== -->
<!--                               End Top Section                              -->
<!-- ========================================================================== -->



<!-- ========================================================================== -->
<!--                              Start Text Section                            -->
<!-- ========================================================================== -->
<div style="margin-left:2em; margin-right:2em;">

<p>
<?php
	backToSermonsTalksPage();
?>
</p>



<p>
<h4>
Trinity 3 (St John the Baptist): &quot;Freed for Obedience&quot; - Rev Dr Chris Kent
</h4>
</p>

<p>
<b>
Romans 6: 15 - 23
</b>
<br />
<b>
John 8: 31 - 36
</b>
</p>

<p>
(1) We're now at the fourth stage of our journey through the central chapters of Paul's letter to the Christians in Rome. This part of the letter gets right to the heart of the gospel: In chapter 5, Paul follows his look at the story of Abraham to come out with an astounding statement of how we can become acceptable to God and enter into a life-changing relationship with him. In contrast to the way people try to gain divine favour - by &quot;doing the right things&quot; or by &quot;being good enough&quot; - the real way in to acceptance by God comes from God and not from us. It's called grace; it's available because of Christ's death and resurrection, and we can only receive it as a gift, through faith in Jesus. But, if we do accept God's grace in Christ, we not only gain a new standing in God's eyes, we receive a new life, eternal life. And we become part of God's kingdom, with a new Lord, Jesus Christ.
</p>

<p>
(2) Then, as chapter 6 begins, Paul starts to explore what this new life means in practice. Because God really does effect a change in the life of each person who puts their faith in Jesus; it's not just a religious fairy story or symbolic language, or an intellectual theory, or access to new knowledge; the life of the Christian has been transformed; we are re-made to live life in a new way. But we are still in the same old world, and are faced with the same old influences the same old temptations towards sin. It's as though we are torn between two worlds: the kingdom of God and our old life. How, then, should we strike out, in our new life? Should it really make a difference? Does it matter?
</p>

<p>
(3) Chapter 6 divides up into two halves, each starting with a question. Maybe both questions are rhetorical, or maybe they reflect two positions taken by those who just could not take on board the notion that all God asks from someone in order to accept them is faith in Christ, rather than amassing a collection of &quot;religious brownie points&quot;, through doing good deeds or knowing all the right things. These sceptics could have been trying to discredit the good news by claiming that it's a &quot;soft option&quot; that allows us to do what we like. Paul answers each in turn. In his answer to the first question, he shows that one key implication of the new life in Christ is freedom from the power of sin and the need to win God's favour. He ends the section with these powerful words, in verse 14: &quot;. sin shall not be your master, because you are not under law, but under grace&quot;. In Christ, we have freedom from the power of sin.
</p>

<p>
(4) Today's New Testament lesson provides Paul's answer to the second question, which is really a rephrasing of the sceptic's challenge to grace as being the basis of our being accepted by God. Verse 15 reads: &quot;Shall we sin because we are not under law but under grace?&quot; The argument goes like this: &quot;OK, if God accepts me on the basis of his unconditional and undeserved love - in other words, his grace - and because Jesus died on the cross to deal with the matter of my sins. And, if I have accepted this grace by putting my faith in Jesus. then I've ticked all the boxes, and I'm promised eternal life. That's great, it's in the bank, I'm secure for life, and for eternity. Now I can get myself a life. Doesn't matter how I do it, as long as I'm having a good time. Maybe I'll try a few adventurous things that might be of a dodgy nature and lead me into temptation. but, I can handle it. and even if I don't always stay &quot;on the straight and narrow&quot;, there's always confession and God will forgive, because of his grace. In fact, this grace business is really good, because it means that I can carry on with my old lifestyle, and just add the occasional attendance at church to mark out that my faith is still ticking over.&quot;
</p>

<p>
(5) Does this sound a bit of a parody? Surely, no one would think that way? But isn't this a possible logical extension of the position Paul holds: that, if God forgives us unconditionally, because of Jesus and his grace, why shouldn't we assume that he will go on forgiving us, no matter what we do, as long as we &quot;sign up&quot; to Christianity and believe in Jesus? I think that it is a possible consequence of grace, which could be a major weakness in the Christian position on salvation, if that's all there is to the argument. But it's an extension that will inevitably lead to a hypocritical lifestyle, and play straight into the hands of supporters of a secular approach to life, and of others who would wish to discredit Christianity. Because, if Christians are perceived to be no different from anyone else in their lifestyles and standards of behaviour and morality, who will take the gospel seriously?
</p>

<p>
(6) Over recent years, atheist and secular points of view have been getting increasing amounts of media time, and have become more insistent that religion is a false way of describing reality. There is evidence that this could be having some effect on public opinion in the UK. For example, according to the 8th June edition of the Church of England Newspaper, two of the top ten books in Amazon's best-selling list are by highly articulate militant atheists out to show that religion is bunk, and God is a delusion - that is, books by Richard Dawkins and Christopher Hitchens. In his book, and in the recent TV series, &quot;The Root of all Evil&quot;, Dawkins goes even further, and actually calls religion evil. Now, his arguments have been refuted quite clearly by Alister McGrath, but don't cases that show Christians doing the most appalling things, such as child abuse, while apparently being pillars of the church, provide powerful evidence for the secularist case? Taking God's grace lightly can damage the credibility of the gospel.
</p>

<p>
(7) But there's another reason for not taking God's grace lightly, which is a more individually personal one; that is, it's dangerous, and could seriously damage your spiritual prospects. This is Paul's focus as he meets the sceptic's challenge. In verses 16 to 22 of Romans 6, he uses ideas from the slave market to illustrate his argument.
</p>

<p>
(8) For Paul, the idea that we can be masters of our own lives and our own destinies is an illusion. We all follow something: it might be fashion, celebrities, the latest idea or social ritual, the dictates of family or a loved one, riches, career, one's own preferences or instinct. Whatever it is, Paul argues, we become bound to it, we become its slaves. I suppose if he were writing today Paul might have used the illustration of drugs and addiction. In Paul's view, there is no alternative in life; we all have to choose what to follow as its slave. Again, in his view, in verse 16, there are only two types of master to follow: what he calls sin - which involves us in trying to lead life independently of God - and obedience [to God]. In verses 17 and 18, Paul explains becoming a Christian using this picture: it's like being set free from one master and taken on by another. But, in contrast to his concentration on the &quot;God side&quot; of the transaction, for instance, in chapter 5, here he homes in on the human part: Becoming a Christian is not just a matter of faith, it's also to do with faithful living - or, as in verse17, obedience to &quot;. the form of teaching to which you were entrusted&quot;. So, becoming a Christian should result in a change of lifestyle, in obedience to Jesus' teaching, even if God's grace and acceptance come first. In the words of verse 18, Christians have been set free to become &quot;slaves to righteousness&quot;.
</p>

<p>
(9) Now, this isn't just a theoretical notion, nor is living as a Christian solely, or even primarily, about &quot;thinking blessed thoughts&quot; or &quot;having good intentions&quot;: keeping our faith to ourselves, while &quot;going with the flow&quot; in our behaviour. In Paul's argument, being &quot;slaves to righteousness&quot; means that we use what he calls, in verse 19, &quot;the parts of your body, or members&quot;, in very different ways from the ways we used them before becoming Christians. Under our new master, God, Paul tells us to offer the parts of our bodies &quot;in slavery to righteousness leading to holiness.&quot; In other words, we are under obligation to respond to God's grace in Christ by being obedient and living lives of a holy quality, just like Jesus. in our thoughts and speech and deeds.
</p>

<p>
(10) That's not a condition we have to carry out before becoming accepted by God, so we never have to &quot;become good enough&quot;, but it's an expected part of the package involving how we respond to God's initiative of grace.
</p>

<p>
(11) Now, that's what Paul says we &quot;ought&quot; to do. But, having looked at this passage, and decided to say, &quot;Thanks, but no thanks&quot; to Paul's morality lecture, &quot;I'll just stick to grace and God's promise of eternal life&quot;, would this response matter? Well, Paul's answer is emphatically, &quot;Yes, it does matter; because it affects where you're ultimately headed&quot;. In verses 16 and 21, he tells us of the two destinations: being a slave to sin leads to death, but being a slave to obedience (that is, obedience to God and Christian teaching) leads to righteousness and holiness. This, he tells us in verse 22, leads to eternal life. In verses 20 and 21, Paul tells his readers to think back to their pre-Christian lifestyles, and where these lifestyles were ultimately leading. Their lives lived separately from God, if persisted in, would be self-destructive and lead ultimately to eternal separation from God, and therefore to eternal death. a frightening prospect to most of us, I guess. In contrast, the Christian who seeks to live life in obedience to God will have the promise of eternal life confirmed. However, if someone becomes a Christian and chooses a sinful lifestyle, it is as though they have gone back to their own slave-master. If they persist in that choice, that choice is destructive, and their ultimate destination will be re-routed to the original one. So, not only is it important to respond practically to God's grace, persistent failure to choose the obedient route is dangerous, and will seriously damage your spiritual prospects.
</p>

<p>
(12) So Paul ends, in verse 22, by contrasting the two choices that face all Christians, indeed all people: The first is the choice of life separate from God, or indeed choosing to try to reach God by one's own route and efforts: this pays a wage, because it depends on human efforts, and that wage is eternal death. The second choice is that of receiving God's grace by faith in Jesus and seeking to live life in obedience to him and his teaching; as this depends on God's initiative, and the price has already been paid (by Jesus on the cross), so the result is a gift from God: &quot;eternal life in Christ Jesus our Lord&quot;.
</p>

<p>
(13) God give us grace to stick with our choice to live in obedience to Jesus, and may the Holy Spirit give us the power to live this way.
</p>



<p>
<?php
	backToSermonsTalksPage();
?>
</p>


<!-- ========================================================================== -->
<!--                              End Text Section                              -->
<!-- ========================================================================== -->
</div>


<!-- ========================================================================== -->
<!--                          Start Footer Content Section                      -->
<!-- ========================================================================== -->
<?php
	include('footer.php');
?>
<!-- ========================================================================== -->
<!--                            End Footer Content Section                      -->
<!-- ========================================================================== -->


<!-- ========================================================================== -->
<!--                            End of CSS Layout                               -->
<!-- ========================================================================== -->
</div>  <!-- END <div id="maincontainer"> -->


</body>
</html>

