<?php
	/******************************
		Talk to MySQL
	**********************************/
	require_once("mysql.php");


	/******************************
		Start a session
	**********************************/
	require_once("session.php");
	$oSession = new session();
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 14/01/2005 -->
<head>
<title>Christ Church, Lye, West Midlands. UK</title>
<?php
	require_once("nocache.php");	// Stop - hopefully - this page being cached
?>

<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta name="description" content="">
<meta name="keywords" content="">
<meta name="author" content="newey499@hotmail.com">
<meta name="generator" content="AceHTML 5 Freeware">


  <!-- CSS Includes -->
  <link rel="stylesheet" type="text/css" href="css/layout.css" >
  <link rel="stylesheet" type="text/css" href="css/church.css" >
  <link rel="stylesheet" type="text/css" href="css/slideshow.css" >
  <link rel="stylesheet" type="text/css" href="css/tooltip.css" >
  <link rel="stylesheet" type="text/css" media="print" href="css/print.css" >
  <link rel="stylesheet" type="text/css" href="css/cssdropdownmenu.css" />
  <!-- End CSS Includes -->

</head>
<body>

<?php
	require_once("mysql.php");
	require_once("globals.php");
	require_once("genlib.php");
?>

<!-- ========================================================================== -->
<!--                            Start of CSS Layout                             -->
<!-- ========================================================================== -->
<div id="maincontainer">

<!-- ========================================================================== -->
<!--                             Start Top Section                              -->
<!-- ========================================================================== -->
<div id="topsection">
<div class="innertube">

<!-- Top Banner for site -->
<?php
	include_once("topbanner.php");
?>

</div>  <!-- End <div class="innertube"> -->
</div>  <!-- End <div id="topsection"> -->

<!-- This extra pointless div is needed to get IE out of the crap -->
<!-- Without it the top banner is not displayed                   -->
<!--[if IE ]>
	<div>
	</div>
<![endif]-->


<!-- ========================================================================== -->
<!--                               End Top Section                              -->
<!-- ========================================================================== -->



<!-- ========================================================================== -->
<!--                              Start Text Section                            -->
<!-- ========================================================================== -->
<div style="margin-left:2em; margin-right:2em;">


<!-- Top Banner for site -->
<?php
	include_once("topbanner.php");
?>

<br />


<p>
<?php
	backToSermonsTalksPage();
?>
</p>


<p>
<b>
﻿God's Judgment - A Message that Needs to be Heard
<br />
Ezekiel 3:16-6:14
<br />
Christ Church Lye   June 2009
</b>
</p>

<p>
<b>
Introduction    3:16-23
</b>
</p>

<p>
 4 yrs ago Channel 4 ran a TV programme called "the new 10 Commandments” It asked how the traditional the10 Commandments to be  seen today?  It included a poll where people voted for what they thought should be in the 10 Commandments for today. The publicity blurb described programme with these words -
</p>

<p>
“What follows is a comprehensive trashing of the old order, as seven of the most hallowed commandments are dashed to the ground. The New Ten Commandments which replace them are upbeat, positive, lacking the fire and brimstone of the ancient “shall not’s.”
</p>

<p>
I don't know what background music accompanied the programme but as read that quote I think Frank Sinatra's  “I did it my way” would have been appropriate.  We know that we live in a nation that has turned its back on God, and that is not just reflected in personal morality but in our very laws.  As we look at the 10 Commandments it is shocking see that for many of them the  laws of our country  allow and encourages them to be broken - and even worse sometimes penalises people if they disagree.  Laws like that are not laws. They cannot be called laws - they are un-laws.
</p>

<p>
Please turn to Ezekiel - 5:5.  Ezekiel is speaking to Israel and said 2600 years ago "In her wickedness she has rebelled against her laws and my decrees more than the nations and countries around her." I do not know how we stand compared to our neighbours and to make comparisons is unhelpful I think because it makes us avoid the problem.  The problem is this as a nation we stand under Gods judgement, for God is perfectly righteous and holy. He is 100% pure.  We read in 1John 1 “God is light and in him is no darkness at all”.
So what is our response? One thing it is most certainty not is to stand back at a distance and say how terrible and then walk on as if it’s not my concern. Or even worse think we are somehow better.  No, God loves our nation and wants people to turn back to him. Sin hurts and messes up peoples lives, and ultimately it leads to destruction.
</p>

<p>
If we look at Ezekiel we can see how we should respond.  Turn back to 3:16. In this situation Ezekiel is called to be a watchman (v 17).  A watchman would stand on the walls of an Israelite city at night, he would look out for invasion and danger, and if he saw such coming he would warn the city so it could protect itself.  Ezekiel is called to warn the nation of Gods coming judgement. Ie: our response is to a ministry of serious and desperate warning people of Gods coming judgement.
</p>

<p>
Go back that Channel 4 documentary for a minute. Do you know what they came out with as the new 1st commandment?
</p>

<p>
“Treat others as you would like to be treated.”   Actually you may recognise that that is not new at all. It comes more or less straight out of the New Testament. Jesus sums up the teaching of the Sermon on the Mount in these words "So in everything do to others what you would have them do to you, for this sums up the law and the prophets."  God has given us a conscience and even left to ourselves we know what is right and wrong.  If you looked at Channel 4 new commandments you would see some other similarities.  What is more interesting is what is missing. What is missing is critical. God is absent and so in the end there isn't any sense of accountability.  Let me remind you what it said in the beginning about that programme - "The New Ten Commandments which replace them are upbeat, positive, lacking the fire and brimstone of the ancient “shall not’s.”
</p>

<p>
That is a lie. God does not give 10 Commandments because he is worried we might enjoy ourselves.  No each one is an expression of the character of God. They express his love. They are good.  Keeping them brings blessing.  It says at the end of the 5th commandment - honour father and mother "So that you may live long in the land the Lord your God is giving you." Exodus 20:12.
</p>

<p>
The 10 commandments without accountability is nonsense.  It says in the end it doesn't matter whether you keep this or not.  What is the point of a country passing laws if it has no police force, or a school having an anti bullying policy if it doesn't enforce it? Or a factory with a health and safety policy which it never checks?
</p>

<p>
The first four of the 10 Commandments are all explicitly to do with honouring God. Worship him only, worship him rightly - not through statues, do not misuse his name. Rest on the Sabbath because he rested. It seems we know what is right and we want it - but in our own way, and without God.   That is at the heart of sin. Man going his own way, putting himself on the throne and not God. I know that is my problem. God is holy and cannot ignore sin. Judgement is always an unpopular message.  Our fallen nature rebels against it and avoids the issue or try’s to reason it away or distorts the scriptures to deny it or gets embarrassed about talking about it.  That is the sitaution  today and it was no  different in Ezekiel’s day. For this reason, and because the people of Ezekiel’s day were particularly hard hearted and unwilling to listen, God calls Ezekiel to the most extreme and graphic measures to get the message of Gods impending Judgement across.
</p>

<p>
<b>
Warning - The Siege 3: 24-4:17
<br />
4 mini acted parables.
</b>
</p>

<p>
First is the Siege of Jerusalem.  Ezekiel draws a picture of Jerusalem on a flat clay tablet. And then round it all the paraphernalia of a city under siege.  Everyone would recognise this. Everyone knew that Jerusalem had been besieged and probably would be again.  What is Ezekiel going to say? But he doesn't say anything, instead he goes to the kitchen and digs out a huge cast iron frying pan. And then places it like a wall between himself and the besieged city. What does it mean?  Many things in Ezekiel are not entirely clear, but maybe the hardness and unmalleability of iron speaks of the firmness and certainty of God’s purpose against the city.  It will fall and be largely destroyed.
</p>

<p>
But how can that be the people think? Surely this is Gods city, and  at the heart of which is God’s holy temple where God’s priests lead worship. Ah but where is Ezekiel the priest in this model? On which side of the Iron wall is Ezekiel? He is outside of the city. And that is where God is - standing outside the city to bring judgement on it.
</p>

<p>
Second in verses 4-8 Ezekiel is lying on his side.  Note here Ezekiel’s role in the parable changes - he now represents the people and not God.  He was told to lie on his left side for 390 days symbolise Israel bearing sin. 390 days is roughly is the length of monarchy. 390 years of spiritual decline.  He then lies on his right side for 40 days for the sin of Judah,  representing probably the 40 years rebellious wanderings of the people in the desert with Moses.
</p>

<p>
Now just think for a minute what these actions mean.  He is saying for key parts of the history of your nations - despite the great kings like David and Solomon and the great prophets like Moses and Elijah - overall your national history is one of unremitting sin and rejection of me!!
</p>

<p>
And then in v. 8 we see that for part of the time Ezekiel is tied up.  Go back to verse 3:25 to see that other people have tied him up - perhaps because he is seen as a trouble maker.  Perhaps this represents the constriction and restraint of the city under siege.
</p>

<p>
Third parable.  The food Ezekiel eats 4:9-16.  While Ezekiel acts out this parable in public every day for well over a year he is to do so whilst on a starvation diet. Look at v. 9-11 and the footnotes at the bottom of the page see how little he eats. About 8 oz of grains - note no meat or vegetables, and only 1 pint of water per day.  See in v. 16-17 he is mimicking the desperate conditions of the people besieged in Jerusalem, who are lit wasting away, but not only because of lack of food -but as in v.17 because of their sin.
</p>

<p>
In the desperate part of the siege of Jerusalem the people would lack fuel for cooking.  In v. 14 Ezekiel is told to cook his food using his own excrement as fuel. He is so shocked that he cries out in verse 14 "Not so sovereign Lord". What Ezekiel was asked to do is shocking to us - but consider how much more so to Ezekiel, a priest, a man set part as Holy. God relents - and he is allowed to cook his food over cow dung instead.   I think God asked him cook his food over own excrement s a test, as part of his message.
</p>

<p>
How did you react when heard that?  Probably with revulsion.   And that is the point, for that is how God feels about sin. It revolts him. It is the most morally ugly thing that there is. It disgusts him because it is the negation of all that he made us to be in love. And so he feels the strongest possible feelings against it. Note too what is not being said - it is sin but not God hates not sinners. If he hated us he would have never bothered sending Ezekiel and just abandoned us to fate.  The very fact we have this message shows he loves us.
</p>

<p>
Fourth Ezekiel’s hair 5:1-4. I think all these actions are going on at same time. But at end of the siege he is to cut off his hair, and divide it into three parts. Verse 2 1/3rd burnt, 1/3rd struck with a sword, and 1/3rd scattered in the wind - symbolising the fate of those in the besieged city.
</p>

<p>
But again in the middle of this picture of total destruction - there is the grace of God.  Look at verse 3 a few strands of hair are saved tucked inside Ezekiel’s robe.
</p>

<p>
<b>
Warning - The Judgment Chapter 5
</b>
</p>

<p>
But what does it all mean?  Imagine the scene - for well over a year people having been watching Ezekiel’s behaviour. At first it puzzles them, it’s bizarre, may be it disturbs them because they think they know what he is saying.  But during the whole of this time Ezekiel has not uttered one word of explanation.  Go back to  3:26 and read what God says "I will make your tongue stick to the roof of your mouth so that you will be silent and unable to rebuke them, though they are a rebellious house."  Ezekiel will be silent, and in fact he remains silent for seven and a half years apart from when God gives him a prophetic word to speak.
</p>

<p>
Isn't that bizarre Ezekiel has had the most stunning and awesome vision imaginable, then he is called to be watchman - one who shouts out a warning. And now a week later he is told to be almost silent.  What is God doing?
</p>

<p>
Is it perhaps that when people are hard hearted and will not listen the thing that speaks to them most is silence? They know we disagree and expect us to speak.  And isn't this how Jesus spoke at his trial - by silence. For so much of the time people threw accusations at him and he said nothing. In Mark’s Gospel it says of Jesus that when he was silent...and Pilate was amazed.  Ezekiel’s silence would make people think - so that after over a year of not opening his mouth when he does people listen to every word.
</p>

<p>
And when Ezekiel begins he begins with a bombshell.  Look at 5:5 This is what the sovereign Lord says: "This is Jerusalem." All these things that you have been seeing and wondering about and maybe understanding, well they are going to happen to Gods holy city Jerusalem.
</p>

<p>
Now remember Ezekiel is speaking to people in exile. There is still a kingdom of sorts in Jerusalem.  The exiles might have looked at themselves and wistfully longed to be back.  Maybe they wondered too if we are here we must have done something particularly bad to deserve to be here. But Ezekiel’s word turns their ideas on head.  No - you may be hard hearted and have problems but it is those in Jerusalem who think they are blessed and think have escaped exile who have a far bigger problem.
</p>

<p>
He outlines the problem in v 6. They ignored Gods good and loving commandments. Not only has he ignored them but v 7 done so with such pig headed passion that "You have not even conformed to the standards of the nations around you."  Hand in hand with this moral decline goes decline in worship - see v 9, they worship detestable idols. In v 12 we see the result.  People will fall by plague sword or famine. This is three thirds ie almost the whole of the population.
</p>

<p>
Now spotting idols and sin especially in others is easy. I read something this week in a Christian magazine entitled "Golden Calf of the year award 2008"  - and there was a picture of a man in sun glasses leaning casually against a very nice Gold coloured sports car. I thought I like that. It’s not me.
</p>

<p>
It’s easy to spot idols in others. I began by looking at the new 10 Commandments.  But then who is this passage addressed to? Not to pagan nations around, not the Babylonians - though it may have implications for them. No first it was to Gods chosen people - in Jerusalem and in exile.  Likewise it is a word that we as a Church must make sure that we hear and apply to ourselves.
</p>

<p>
An idol can be anything but just as easily it can be an idea a goal or an ambition. e.g As look myself I ask am I more interested in having a full church than being faithful to God whatever happens? Or popularity, we all like to be liked.  I am a minister in a church that in parts is turning its back on God.  Someone advised me last year "Oh just keep your head down and don't worry about things".  Personal comfort and peace at any cost were idols in Ezekiel’s age and are just as much as temptations today.
</p>

<p>
<b>
A Warning to those Watching Chapter 6.
</b>
</p>

<p>
One final word from Ezekiel in chapter 6, having spoken of the people in Jerusalem-he now speaks to the mountains of Israel 6:2.  This is the countryside around Jerusalem. They faced the temptation of observing these terrible events at a distance and so think – it’s not affected us, there’s nothing to worry about. After all what do you expect in a big city?
</p>

<p>
But see in v 3-4 they too had forsaken the worship of almighty God and faced his judgement. They looked on at distance in miles and said it won't happen to us. We look on at a distance but in time - 2600 years later.  Let us make sure that we don't say of course things were different then 2600 years ago. That wouldn't happen today, God does not change and Idolatry is not far from any of us.
</p>

<p>
But the word to those watching is also a word of hope.  There is a great deal of hope in the book of Ezekiel - especially towards the end.  But before people hear the good news they need to face up to the bad. There is no resurrection and Pentecost without the first Good Friday.
</p>

<p>
The wrath of God was described by Martin Luther as "Gods strange work".  The anger of God is not an innate part of who he is. It will not always be there. It is a reaction to sin. It is for this age and  one day it will be no more. The heart of the character of God is love. It is not just that God loves but because he is the Trinity he has relationship at the very heart of who he is. That relationship is love.  And so here in midst of this parable of Judgement there is lightening flash of hope.  To see the end of the judgement look at v 7-10.
</p>

<p>
God is not angry because he is difficult and grumpy but in v 7 there is a clear goal namely that people will turn back to him.  And so some will turn back to him in verse 8, they will remember God and understand the awfulness of what they have done wrong see verse 9. And see too - God does not do this lightly - it grieves him. God’s anger is his loving displeasure at sin. There is hope - and now that hope is made real to us because we have Jesus Christ.
</p>

<p>
<b>
Conclusion
</b>
</p>

<p>
Ezekiel is a heavy and challenging book. Maybe you are thinking  "I don't like this, I hope we don't have much more of it", but it’s a truth we need to hear.
</p>

<p>
The Gospel does not make sense without the message of Ezekiel.  If sin were not so serious there would be no reason for Jesus having to die.  God could have saved us in some other less costly way. But because sin was so terrible the cost of our salvation was the greatest cost imaginable. And if sin was not so serious and judgement were not real why bother becoming a Christian. Without the message of Judgement in Ezekiel the Gospel becomes just another lifestyle option in the spiritual shopping mall.   If it suits you fine - but if doesn't so what? Try the meditation centre down the road.
</p>

<p>
Like the iron frying pan Judgement cannot be avoided, if God did not judge sin he would not be God.  Saying good and bad actually matters.  Cooking the food over manure speaks of what sin does- it defiles. It shows us how God feels about evil. The fate of Ezekiel’s hair reminds us there is a punishment for sin, but also shows there is hope.  For some of the hair is saved.  Ezekiel lies on one side bearing the sin of Israel. The penalty has to be paid and now we have one who has done just that. Jesus.
</p>

<p>
And so the response for us is that of Ezekiel - we are called to be watchmen, to warn people of Gods anger at sin and the inevitably of judgement and the possibility of being saved from that through Jesus Christ.  If God give us the call - will we follow?
</p>

<p>
Simon Falshaw June 2009
</p>



<p>
<?php
	backToSermonsTalksPage();
?>
</p>


<!-- ========================================================================== -->
<!--                              End Text Section                              -->
<!-- ========================================================================== -->
</div>


<!-- ========================================================================== -->
<!--                          Start Footer Content Section                      -->
<!-- ========================================================================== -->
<?php
	include('footer.php');
?>
<!-- ========================================================================== -->
<!--                            End Footer Content Section                      -->
<!-- ========================================================================== -->


<!-- ========================================================================== -->
<!--                            End of CSS Layout                               -->
<!-- ========================================================================== -->
</div>  <!-- END <div id="maincontainer"> -->


</body>
</html>

