<?php
	/******************************
		Talk to MySQL
	**********************************/
	require_once("mysql.php");


	/******************************
		Start a session
	**********************************/
	require_once("session.php");
	$oSession = new session();
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 14/01/2005 -->
<head>
<title></title>
<?php
	require_once("nocache.php");	// Stop - hopefully - this page being cached
?>

<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta name="description" content="">
<meta name="keywords" content="">
<meta name="author" content="newey499@hotmail.com">
<meta name="generator" content="AceHTML 5 Freeware">

  <!-- CSS Includes -->
  <link rel="stylesheet" type="text/css" href="css/layout.css" >
  <link rel="stylesheet" type="text/css" href="css/church.css" >
  <link rel="stylesheet" type="text/css" href="css/slideshow.css" >
  <link rel="stylesheet" type="text/css" href="css/tooltip.css" >
  <link rel="stylesheet" type="text/css" media="print" href="css/print.css" >
  <link rel="stylesheet" type="text/css" href="css/cssdropdownmenu.css" />
  <!-- End CSS Includes -->

</head>
<body>

<?php
	require_once("mysql.php");
	require_once("globals.php");
	require_once("genlib.php");
?>

<!-- ========================================================================== -->
<!--                            Start of CSS Layout                             -->
<!-- ========================================================================== -->
<div id="maincontainer">

<!-- ========================================================================== -->
<!--                             Start Top Section                              -->
<!-- ========================================================================== -->
<div id="topsection">
<div class="innertube">

<!-- Top Banner for site -->
<?php
	include_once("topbanner.php");
?>

</div>  <!-- End <div class="innertube"> -->
</div>  <!-- End <div id="topsection"> -->

<!-- This extra pointless div is needed to get IE out of the crap -->
<!-- Without it the top banner is not displayed                   -->
<!--[if IE ]>
	<div>
	</div>
<![endif]-->


<!-- ========================================================================== -->
<!--                               End Top Section                              -->
<!-- ========================================================================== -->



<!-- ========================================================================== -->
<!--                              Start Text Section                            -->
<!-- ========================================================================== -->
<div style="margin-left:2em; margin-right:2em;">

<p>
<?php
	backToSermonsTalksPage();
?>
</p>





<h4>When Did Paul Live?</h4>

<p>
When did the Apostle Paul live? The events of the Acts of the Apostles occured a long time ago and allthough they are history they lack one feature that we assume is an essential part of history. There are no dates. This doesn't mean that they are any less historical.  Luke sometimes refers to contemporary events known to his readers (e.g  Acts 12:28, 18:2). He also mentions kings, queens and other officials that we know about from paralell historical records.
</p>

<p>
The main character of the second half of the book of Luke is Paul. How does his story fit in with what we know from other sources? Three years after his conversion Paul effected a dramatic escape from the city of Damascus, by being lowered over the city wall in a basket. (2 Cor 11:32). This happened three years after his conversion (Gal 1:18). Aretas, who was king at the time, ruled in Damascus from 37 to 40 AD. Paul must therefore have been converted sometime before this event, ie between 34 and 37 AD.
</p>

<p>
In Acts 11:28-30 we read about Paul (Saul) and Barnabus visiting Jerusalem with a famine relief gift during the reign of Emperor Claudius. This famine happened during the rule of Tiberius Alexandra in Judea which was from 46-48 AD. It is also recorded that a local Queen, Helena of Adiabene, did a similar thing to the Christians in Antioch and fetched corn from Eygpt for the inhabitants of Jerusalem at about this time. Papyri show famine conditions in Eygpt just before this in 45 AD. Helena could not have made a collection or gift from there until there was a surplus of grain, possibly in late 46 AD. The date for the gift sent with Paul and Barnabus is therefore probably around 45 or 46 AD.
</p>

<p>
Paul travelled widely and visted many cities. One place where he stayed for a significant period was Corinth. The Roman historuan Orosius records that Emperor Claudius expelled the Jews from Rome in his 9th year of reign. This dates the event to 49 or 50 AD. Luke records that this coincides with the arrival of Paul in Corinth (Acts 18:2) Paul encounters trouble from Jewish opposition in Corinth. The proconsul (Roman Governor) at the time was a man called Gallio (Acts 18:12-17). An inscription has been found confirming that he was proconsul in 51-52 AD. Pauls trial before Galion occurs after living in Corith for 18 months and so fits in well with an  arrival in the city in 50 AD.
</p>

<p>
Much more could be written about Paul in history. But I have not written all these dates merely to give a history lesson.  Many people attack and rubbish the Christian faith. Intelligent and otherwise sensible people write it off as a fairy story. The media delights in sensational, obscure and speculative ideas about Jesus and the early church that are totally lacking in foundation. Together all these factors can have a long term and gradual undermining effect on our faith. In the New Testament in contrast we have a credible historical record of events on the 1st century AD. The lives and stories of people in the Gospels and Acts tie in with what we know from elsewhere. History does not "prove" the Bible is true nor that Jesus is Lord, but we can tell people the story of Jesus with confidence that the New Testament is not creative writing but a thoroughly reliable record of what happened.
</p>

<p>
The Apostle Peter wrote to the Christians living in the pagan culture of modern day Turkey with this advice "always be prepared to give an answer to everybody who asks you to give the reason for the hope that you have" 1 Peter 3:15. To reach unsaved and confused people today we need to do the same.
</p>





<p>
<?php
	backToSermonsTalksPage();
?>
</p>


<!-- ========================================================================== -->
<!--                              End Text Section                              -->
<!-- ========================================================================== -->
</div>


<!-- ========================================================================== -->
<!--                          Start Footer Content Section                      -->
<!-- ========================================================================== -->
<?php
	include('footer.php');
?>
<!-- ========================================================================== -->
<!--                            End Footer Content Section                      -->
<!-- ========================================================================== -->


<!-- ========================================================================== -->
<!--                            End of CSS Layout                               -->
<!-- ========================================================================== -->
</div>  <!-- END <div id="maincontainer"> -->


</body>
</html>

