<?php
	/******************************
		Talk to MySQL
	**********************************/
	require_once("mysql.php");


	/******************************
		Start a session
	**********************************/
	require_once("session.php");
	$oSession = new session();
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 14/01/2005 -->
<head>
<title></title>
<?php
	require_once("nocache.php");	// Stop - hopefully - this page being cached
?>

<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta name="description" content="">
<meta name="keywords" content="">
<meta name="author" content="newey499@hotmail.com">
<meta name="generator" content="AceHTML 5 Freeware">

  <!-- CSS Includes -->
  <link rel="stylesheet" type="text/css" href="css/layout.css" >
  <link rel="stylesheet" type="text/css" href="css/church.css" >
  <link rel="stylesheet" type="text/css" href="css/slideshow.css" >
  <link rel="stylesheet" type="text/css" href="css/tooltip.css" >
  <link rel="stylesheet" type="text/css" media="print" href="css/print.css" >
  <link rel="stylesheet" type="text/css" href="css/cssdropdownmenu.css" />
  <!-- End CSS Includes -->

</head>
<body>

<?php
	require_once("mysql.php");
	require_once("globals.php");
	require_once("genlib.php");
?>

<!-- ========================================================================== -->
<!--                            Start of CSS Layout                             -->
<!-- ========================================================================== -->
<div id="maincontainer">

<!-- ========================================================================== -->
<!--                             Start Top Section                              -->
<!-- ========================================================================== -->
<div id="topsection">
<div class="innertube">

<!-- Top Banner for site -->
<?php
	include_once("topbanner.php");
?>

</div>  <!-- End <div class="innertube"> -->
</div>  <!-- End <div id="topsection"> -->

<!-- This extra pointless div is needed to get IE out of the crap -->
<!-- Without it the top banner is not displayed                   -->
<!--[if IE ]>
	<div>
	</div>
<![endif]-->


<!-- ========================================================================== -->
<!--                               End Top Section                              -->
<!-- ========================================================================== -->



<!-- ========================================================================== -->
<!--                              Start Text Section                            -->
<!-- ========================================================================== -->
<div style="margin-left:2em; margin-right:2em;">

<p>
<?php
	backToSermonsTalksPage();
?>
</p>






<p>
<h4>
What Would Jesus have said to a  Prostitute

<br />
Luke 7: 36-50
<br />
Sermon Preached by Reverend Simon Falshaw
<br />
At Christ Church,  Lye - June 2003.
</h4>

</p>

<p>
<h4>
Introduction
</h4>
<br />
Today we ask the question &quot;What would Jesus say to a prostitute?&quot;.   When advertising this series we delivered some leaflets to local houses. A number of people looked at the titles and made comments. One man looked at the title of this talk and made a remark that I don't wish to repeat. But what he had said showed me,  that   in most peoples minds,  Jesus and prostitutes are not associated. We don't even think of them as being in the same sentence.
</p>

<p>
However God made everyone, loves everyone and sent his Son to die for everyone,  including prostitutes. And not only prostitutes but anyone else who feels deeply guilty of falling short of God's standards in this area. Early in his ministry Jesus was accused by religious leaders of mixing with the wrong sort of people. They said why does he eat with sinners? Jesus reply to this question was &quot;it is not the healthy that need a doctor but the sick….I have not come to call the righteous, but the sinners.&quot; That includes all of us. We may or may not have a sense of sexual failure like the woman in our reading, but we have all sinned and need God's forgiveness.
</p>

<p>
<h4>
A Sinful Woman
</h4>
<br />
Jesus was a people person and was always out amongst people. When he spoke he said things that were listened to and people wanted to meet him. There are many records of him attending parties. Here we have a woman who has previously seen and heard Jesus,  and now wants to meet him properly. She is described in verse 37 as &quot;a woman who had lived a sinful life&quot;. This statement together with the fact that her hair was loose means almost certainly she was a prostitute. People might have said or thought &quot;we know what sort of person she is. We know what she’s up to.&quot; People might have looked at her with a combination of condemnation and disgust.
</p>

<p>
What did she feel though? Did she feel trapped? Economically - perhaps this was the only way she had of earning a living? Physically - maybe she had been controlled and exploited by someone else? Perhaps she feared being beaten up if she left her job? Psychologically -  at the centre of her being is a sense of self hatred (disgust) and worthlessness which  maybe stops her trying to escape her situation? Her sin makes her feel bad about herself, and because she feels bad she feels she that she doesn't  deserves anything better. She punishes herself by letting people take advantage of her sexually.
</p>

<p>
Her story perhaps mirrors those who have been forced into prostitution in many East European countries. This is the comment of a woman from Albania who was kidnapped and taken to Italy and forced into prostitution. Approximately 2000 woman and children face this ordeal every year in the United Kingdom. Sometimes they are released and make their way home. However the woman from Albania commented on the sense of shame that she had &quot;I still can’t tell my family what really happened&quot;.
</p>

<p>
Jesus steps into this situation and gives  hope. He has healed people and changed people as they come to meet him. He set people oppressed by demons free. He says words of hope to the suffering such as &quot;blessed are the poor in spirit&quot; Lk 6:20.   This woman knows spiritual poverty. She stands far away from holy God and wonders how could he ever accept her? But Jesus offers hope to her because he says to  the poor in spirit, &quot;yours is the Kingdom of God&quot;.
</p>

<p>
Jesus seemed to accumulate a crowd of so called undesirables wherever he went. Who would be in his crowd today? Perhaps minor criminals, persistent vandals, drug dealers, arrogant and corrupt politicians, serial gossipers, defrocked clergy, porn barons, prostitutes, contract killers, terrorists and even rapists. This is what Jesus meant when we said &quot;it is not the healthy who need a doctor but the sick…I have not come to call the righteous but sinners&quot;. This is how the woman feels and she realises that her only hope is to seek out Jesus.
</p>

<p>
Mealtimes in Jesus' day were often taken  outside. It might have been relatively easy to walk into a meal and join in. The people would be reclining around the central table. The woman enters and  sees Jesus. Immediately she feels so overwhelmed in his presence that she breaks down and begins to cry. You could imagine her crying and shaking in such distress that tears stream out onto his feet.
</p>

<p>
In the hot sweaty climate the custom was to wash peoples feet from the dust and grime when they enter the house. She wants to express love and gratitude because of what Jesus can do or even has already done for her. Normally a bowl of water would suffice to wash someone's feet, but in her case it was her own tears that washed Jesus feet. She had not got a towel and so she uses her hair. Washing feet was a normal courtesy,  but in gratitude of what Jesus has done for her she pours  out a bottle of perfume onto his feet.
</p>

<p>
For those standing around her display looks ridiculous and over emotional. So much so they begin to feel uncomfortable. They think it is bad enough that this sort of person should be at the party, but that she should put on a great show of so called sorrow was really disgusting. It is obviously not real. People like that cannot change. Such people deserve God’s punishment.
</p>

<p>
However Jesus turns to this woman and says &quot;your sins are forgiven you may go in peace&quot;. No, actually he doesn't say that. In the passage  (verse 38-39) the woman is in front of him is weeping and he doesn't quite tell her that yet. Rather than speak to the woman he speaks to the Pharisee at whose house he was eating. It wasn’t the prostitute who really had a spiritual problem it was the Pharisee. Let us look for a minute at the Pharisee.
</p>

<p>
<h4>
The Hard Pharisee
</h4>
<br />
The Pharisees often  seemed to have a bad press in the Gospels. The word &quot;Pharisee&quot; almost seems like a synonym for &quot;the baddie&quot;. Sharing a name with this Pharisee I have a particular empathy for him. So for a minute lets just think of some of the good things that Pharisee’s do or have done. So if you see a Pharisee in the street, give him a big hug and tell him his not so bad after all!
</p>

<p>
They were committed and keen Jews. They wanted to put God first and to serve him wholeheartedly.
<br />
They were hard working. They were not lazy, forgetful or too busy when it came to reading the scriptures. They were
 diligent and frequent in prayer.
<br />
They were hospitable. They were committed to each other and fellowship of the meals was very important.
<br />
Morally they were impeccable. Very concerned to do the right thing in a pagan society. There were not sleeping around, they lived faithfully with their wives.
<br />
They did not compromise. They knew that the Romans were pagan invaders of God's holy land. There were not going to kow tow to them to get favours which some other Jews might have done.
<br />
They were spiritually seeking. They wanted the Messiah to come and were actively trying to work out when this would be and what he would be like.
<br />
They took the Bible seriously. They believed that from beginning to end it was the inspired word of God.
<br />
They were generous givers. They tithed (that is they gave away) 10% of their income. Their Synagogues were never lacking money.
<br />
They defended the faith. They were often found in debate about their beliefs out of desire to win over others and defend what they believed clearly. By their behaviour you might describe them as sound evangelicals!!
<br />
They were committed to worship with others every Sabbath. They never said it's to cold or to wet, I don't want to  worship, they came.
</p>


<p>
And such was Simon the Pharisee a deeply religious and committed man. He reacts in exactly the right way when he sees this prostitute throwing herself all over Jesus feet doesn't he? Isn't she trying to seduce him? Does he think &quot;I know what she wants!&quot; Jesus might well of been invited to the meal to be sussed out. And now the Pharisees know what he's really like. Look at the people he associates with how can he claim to be a prophet? This is not a man of God.
</p>

<p>
Jesus however knows what Simon  is thinking. Maybe he has a direct word from the Holy Spirit. Maybe he just senses it in Simons face and the atmosphere of the room. In response he tells a story (verse 41-42). Two men owe some money. One owes a few hundred pounds to the bank and the other has masses of debts amounting to tens of thousands of pounds. Incredibly the bank writes off both debts. Who would you expect to be more excited? The answer that Simon gives (verse 43) is &quot;I suppose the one who had the bigger debt cancelled&quot;.
</p>

<p>
Jesus' answer to Simon goes something like this. &quot;You wonder why this woman acts like this? I tell you it's because her sins have been forgiven. Where does all this weeping, kissing my feet, anointing me with expensive perfume come from? Didn't you just say that when a debtor has been forgiven a huge debt he feels great love and gratitude to the one who released the debt?&quot;
</p>

<p>
This woman had a huge debt of sin..  Don't  you understand her gratitude towards me? You said &quot;I supposed the one who had the bigger debt cancelled&quot;. Isn't that by your own admission evidence that she has indeed been forgiven!&quot; Maybe then a gasp of amazement runs around the table when they realise what Jesus is claiming - this and what this woman has realised - Jesus really does forgive sins.
</p>

<p>
<h4>
And What About Us
</h4>
<br />
We need to watch ourselves. We must be aware of a negative spirituality in the Pharisee. With all the constant discussion about sexuality in the Anglican Church when we do see clear sin we should make sure that if we speak we do so with humble and cautious hearts. And that we ourselves are open to change. Simon the Pharisee had so much yet he lacked the one main thing. He did not know forgiveness of sins and he did not seem to know God.
</p>

<p>
It is possible to be very religious, very moral, very concerned for your inner spirituality but still not really know God.  We can be rather like a show home on a new housing estate. A new house structurally A1, beautifully furnished, well decorated but without any life because no one actually lives there. That is how we are without the life of God coming into us through forgiveness.
</p>

<p>
At the end of World War Two the allies rounded up some key Nazi's and put them on trial at Nuremberg. A US Army Chaplain was assigned to them and given the job of looking after their spiritual needs. Some were hard and arrogant and indifferent to him. However some had open hearts. Amazingly, incredibly, they came to know God and his forgiveness as some of them waited on death row.
</p>

<p>
If you are a Christian you are going to spend eternity with these people. If that thought shocks or surprises you then ask yourself do I really know and understand the vastness of God's forgiveness? Do I appreciate the vastness of his love?  The cost of God forgiving small every day sins is as much of those as the war criminals. All cost the death of his Son.
</p>

<p>
So what would Jesus say to a prostitute? I think the words at the end of this story - &quot;your sins are forgiven&quot; and &quot;your faith has saved you go in peace&quot;.
</p>






<p>
<?php
	backToSermonsTalksPage();
?>
</p>


<!-- ========================================================================== -->
<!--                              End Text Section                              -->
<!-- ========================================================================== -->
</div>


<!-- ========================================================================== -->
<!--                          Start Footer Content Section                      -->
<!-- ========================================================================== -->
<?php
	include('footer.php');
?>
<!-- ========================================================================== -->
<!--                            End Footer Content Section                      -->
<!-- ========================================================================== -->


<!-- ========================================================================== -->
<!--                            End of CSS Layout                               -->
<!-- ========================================================================== -->
</div>  <!-- END <div id="maincontainer"> -->


</body>
</html>

