<?php
	/******************************
		Talk to MySQL
	**********************************/
	require_once("mysql.php");


	/******************************
		Start a session
	**********************************/
	require_once("session.php");
	$oSession = new session();
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 14/01/2005 -->
<head>
<title></title>
<?php
	require_once("nocache.php");	// Stop - hopefully - this page being cached
?>

<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta name="description" content="">
<meta name="keywords" content="">
<meta name="author" content="newey499@hotmail.com">
<meta name="generator" content="AceHTML 5 Freeware">

  <!-- CSS Includes -->
  <link rel="stylesheet" type="text/css" href="css/layout.css" >
  <link rel="stylesheet" type="text/css" href="css/church.css" >
  <link rel="stylesheet" type="text/css" href="css/slideshow.css" >
  <link rel="stylesheet" type="text/css" href="css/tooltip.css" >
  <link rel="stylesheet" type="text/css" media="print" href="css/print.css" >
  <link rel="stylesheet" type="text/css" href="css/cssdropdownmenu.css" />
  <!-- End CSS Includes -->

</head>
<body>

<?php
	require_once("mysql.php");
	require_once("globals.php");
	require_once("genlib.php");
?>

<!-- ========================================================================== -->
<!--                            Start of CSS Layout                             -->
<!-- ========================================================================== -->
<div id="maincontainer">

<!-- ========================================================================== -->
<!--                             Start Top Section                              -->
<!-- ========================================================================== -->
<div id="topsection">
<div class="innertube">

<!-- Top Banner for site -->
<?php
	include_once("topbanner.php");
?>

</div>  <!-- End <div class="innertube"> -->
</div>  <!-- End <div id="topsection"> -->

<!-- This extra pointless div is needed to get IE out of the crap -->
<!-- Without it the top banner is not displayed                   -->
<!--[if IE ]>
	<div>
	</div>
<![endif]-->


<!-- ========================================================================== -->
<!--                               End Top Section                              -->
<!-- ========================================================================== -->



<!-- ========================================================================== -->
<!--                              Start Text Section                            -->
<!-- ========================================================================== -->
<div style="margin-left:2em; margin-right:2em;">

<p>
<?php
	backToSermonsTalksPage();
?>
</p>






<p>
  <b>Why Do We Need the Gospel Romans 1:16</b>
</p>

<p>
	<b>Can books change the World?</b>
</p>


<p>
ITV ran a series in April with the title `Twelve Books that changed the
World'. Melvyn Bragg, who was the author and presenter of the series
said this "when people think of things that change the world they tend
to think of
extraordinary events; the assignation of leaders, the invasion of
countries,
the havoc reeked by natural disasters. But there is something less
attention grabbing but just as powerful, which changes the world -
books". Melvyn Bragg's list of books included the First Edition of the
Rules of the Football Association. When this was first published in
1863 it enabled teams playing across London to meet together for the
first time. This in turn developed into National leagues and World Cup
football as we know it today. When we consider the level of interest
and social force behind football we have to concede it was indeed a
book that has changed the world.
</p>

<p>
I want to talk about another book which I believe has changed the world
- that is the Book of Romans. In many ways it was a fresh understanding
of the book of Romans that was the spark that gave rise to the
Reformation in the 16th century. This, with its emphasis on the
Priesthood of all believers (ie that all are in an equal relationship
with God), put a new value on everyday work, as opposed to the idea
that religious work was somehow special and better. This in turn paved
the way for the Industrial Revolution. In a similar way it can be
argued, it also led to the rise of democracy in Western Europe and the
United States. And perhaps to by a new emphasis on scripture alone as
the final authority on matters of faith, as a side effect acknowledge
the limits of what the Church had a right to teach about, and in turn
led to a freer investigation of the natural world and the rise of
modern science.
</p>

<p>
Now all of these points may or may not be true, though academics have
argued and written about all of them. However this is undoubtedly true
that the message of Jesus Christ, the Gospel, as exemplified by the
book of Romans, has indeed changed lives.
</p>

<p>
 <b>The story of Martin Luther</b>
</p>

<p>
illustrates this point. He was a man who sought after God
whole-heartedly. He decided that the best way of getting to heaven was
to become a monk. He was a very serious monk who fasted and prayed for
days on end. He wrote later "I was a very good monk.if a monk ever got
to heaven by his monkery it was I". Despite his religious zeal, his
conscience was not clear and he felt alienated from God. Indeed he was
angry with God since he seemed more like a terrifying judge than a
saviour. He was a Lecturer in theology and came to expand the book of
Romans. As he did so he came to understand that God was merciful to him
in Jesus Christ. He described his experience this way " I have felt
myself to be reborn and have gone through open doors into paradise. The
whole of scripture took on a new meaning.the passage of Paul became to
me the gateway of heaven." .
</p>

<p>
However significant those twelve books
listed by Melvyn Bragg may be none of them has changed the world like
the Gospel. Books may change the sporting world but not everyone like
sport. I imagine many households over the next few months will be split
down the middle between the footies and the normal people!
</p>

<p>
However we are all born eternity. The message of the Gospel that Luther
rediscovered has implications for everyone. These are life or death
implications. One verses at the beginning at the book of Romans sums up
both the book and very much the whole message of Jesus Christ. This is
Chapter One verse 16, "I am not ashamed of the Gospel, because it is
the power of God for the salvation of everyone who believes: first for
the Jew, then for the Gentile. " If we look at this verse we will begin
to see why the Gospel is needed and why we should listen to it.
</p>

<p>
	<b>The Gospel message is a challenging message. v 16a</b>
</p>


<p>
Paul begins by writing "I am not ashamed of the Gospel". By this he
means he is proud of the Gospel but if so why does he not simply say
so? The Gospel message is radical. It cuts across so many things that
the human race holds dear and say they are no good or are false gods.
If we really understand the Gospel and share it we will face hostility
and in turn the temptation to be ashamed.
</p>

<p>
In Paul's world the Gospel was a foolish thing to believe. The Jews
asked "how could a man whose been crucified, who had been cursed by
God, possibly be God's chosen one?" How can such an act of weakness
demonstrate the power of God? In turn the Greeks and Romans with their
love of philosophy might ask "how could something so simple and crude
possibly be wise? And today the Gospel still cuts across many deeply
held believes in turns of what the Gospel says about God, that Jesus
Christ is the only way to God, it can be highly offensive. It means
that however sincere a Buddhist, Hinduist, Muslim, Pagan, or or
follower of any other belief may be, they are ultimately following a
religious system that is useless and also harmful. The Gospel also
teaches that man at heart is a sinner and a rebel. We are lost. Our
good deeds, our general respectability, the keeping of the Law of the
land, our giving to charity, or going to Church, of having been
Baptised (even by immersion!) are as far as getting right with God is
concerned, and our eternal destiny, of no use.
</p>

<p>
If either of those statements has made you feel uncomfortable or
annoyed I do not saythem because I want to annoy or upset you. I am
simply being faithful to what God and the Bible says. These things are
not the way the world thinks. To say them is to tread heavily on
peoples' spiritual toes. As we say and live things out there is a
temptation to feel ashamed. This Gospel message is a radical message
and a challenge that rocks our society to its foundations. However if
we do ever feel isolated or odd or awkward we should be encouraged for
it is a sign that our faith is real.
</p>


<p>
	<b>The Gospel message is powerful - v 16a.</b>
</p>


<p>
Paul writes that the Gospel message "is the power of God for the
salvation of everyone who believes". He does not mean that the Gospel
message is just powerful and other things might be powerful but not
quite as much. It is something deeper and more radical. It is that as
far as doing God's work the Gospel is THE way that God does things. The
message itself is powerful and will speak to people.
</p>

<p>
We live in a multi media age an age of many alternative truths. Because
sharing the Gospel can be hard going we face the temptation to think
that we need to add something onto the Gospel for it to become really
effective. However when we add something onto it we are by implication
we are admitting that it is actually less than it needs to be or is
inadequate.
</p>

<p>
No the Gospel message in itself is powerful.
On the other hand we are not called to be spiritual dinosaurs. God will
use technology - but only in as much as it actually claims the Gospel
of Jesus Christ. By the Gospel, I mean something like this. The world
is God's and we have ignored and failed God so faces right anger at our
sin. Jesus Christ is God's chosen one. We see in Romans 1:2 that all of
the Old Testament points to his coming. By his death on the Cross in
our place Jesus bore our sin. In turn by his resurrection he shows all
this to be true and that he has conquered death. In 1:4 we read "that
he was declared with power to be the Son of God" and as consequence of
this (verse 5) he calls us to "the obedience that comes from faith".
The power of this message is in the message itself not in the means.
However the incarnation of Jesus and the diversity of scripture shows
us that God works through culture and we should not ignore it, but
rather ensure that whatever means we use is faithful in content.
</p>

<p>
	<b>The Gospel saves - v 16 b.</b>
</p>


<p>
The Christian message is a message of salvation. This is one reason why
we sometimes feel the temptation to be ashamed. The Gospel says that in
terms of religion what you have without Christ is inadequate and you
need to be rescued by God.
</p>

<p>
Paul is introducing his theme here so it does not go into great detail.
However if we read on in Chapters one to three see how he explains the
depths of the human problem and so concludes in Chapter three verse 23
"for all have sinned and have fallen short of the glory of God". He is
explaining what we need to be saved from and why Christianity is a
religion of salvation above all. The need of salvation of all, even the
most devotedly religious and apparently good is seen in the life of
John Wesley, He was an ordained minister in the Church of England and
went to America as a Missionary in 1735. While he was there he did
experience much spiritual fruit but rather a steadily increasing sense
of religious disillusionment. So much so that at the end of the time he
wrote "I went to America to convert others but was myself never
converted!". Shortly after returning he went rather unwillingly to
meeting of the Moravian Church in London. There he heard a man reading
the introduction to Luther's commentary on Romans. As God's word, ie
the Gospel, was proclaimed something happened. He wrote this " about a
quarter before nine while he was describing the change which God;s
works in the heart through Christ, I felt my heart strangely warmed..,
and an assurance was given me that he had taken away my sins, even mine
and saved me from the law of sin and death". If this deeply religious
man needed saving how much more do we?
</p>

<p>
	<b>A Message for everyone - v 16c.</b>
</p>


<p>
Paul writes "salvation is first for the Jew then for the Gentile". In
other words he is saying that the Gospel is needed by the whole world.
Paul was a Jew and for 1500 years the Jewish people had a special
relationship with God. However God never intended to limit his
relationship just to them. The Jewish people were called to reveal God
to the world. Finally in Jesus Christ that happened. Now God is calling
people everywhere into a relationship with him. It is this idea that
gets us to the heart of why Paul wrote the book of Romans.
</p>

<p>
The Church was a new creation, that is something unlike any other
organism that existed before. Men and women, slaves and free, rich and
poor met together as equals before God. That equality included Jewish
people who had known God for centuries and had many entrenched ideas on
how one should worship God and live before him. Alongside them there
were also people who had known none of that and perhaps before the
conversion had lived very immoral lives. Can you imagine what would
happen when these two groups of people got together? There will be
explosions, tensions, misunderstandings and judging of people. It might
be like today combing a Church of very high Church Anglo-Catholics who
met in a grade one listed Norman Church building with a two year old
Pentecostal Church plant that met in a disused garage. I imagine there
might be a little bit of conflict.
</p>

<p>
A lot of the book of Romans is about
helping the different groups of people to live together. Have a look at
Chapters nine to eleven. It is all about why the Jewish still have a
place in God's plan despite their lack of acceptance to the Gospel. It
helps Gentile people not to become arrogant and fail to value them. We
could also go ahead and have a look at Chapters fourteen to fifteen we
see here there is a great deal about not judging people who have
scruples perhaps particularly Gentile people not judging Jewish people.
What is the glue that holds these disparate groups of people together?
The answer is in this book and this very verse, that is the Gospel. We
see 1:14 that this is the gift that Paul was sending to the Romans.
Paul's particular mission was to reach out to the Gentiles and he was
now moving from one end of the Mediterranean to the other. He had been
working in the eastern Mediterranean and was now planning to go to
Spain and on his way call in at Rome. To do so he wanted to prepare the
way and arrive at a community in Rome that understood what he was doing
and why God called him to reach the Gentiles. It is the Gospel, God's
unconditional acceptance of all people in Jesus Christ that would
prepare the way for this. It would feed support and unite a church taht
would welcome him and also support him as he went on his way to Spain
</p>

<p>
	<b>The Gospel and you</b>
</p>


<p>
The Gospel is powerful and changes lives. John Bosco Wari is an
Anglican church Minister in Uganda. As a young Christian he was
kidnapped in revenge for the actions of another relative. As they
kidnapped him they marched him off to kill him but as he went he shared
the Gospel with them and one by one his guards slopped off maybe
convicted by what they heard. He eventually managed to escape and went
to hide on the top of a nearby hill, he hid there in the daytime but at
night he came down from the hill to preach the Gospel in neighbouring
villages despite the risk. There is his story we see something of the
power of the Gospel. It changes lives today.
</p>

<p>
 <b>Let me leave you with two questions.</b>
</p>

<p>
Firstly: do you believe the Gospel
of Jesus Christ can change your life? Do you want to know the kind of
certainty and joy that Luther and Wesley and John Bosco Wari knew? Do
you want to know that your sins are forgiven and know a clean
conscience? To know that you are totally accepted by God?
How can that happen? Well we simply take God at his word. As it says
here "is the power of God for salvation on everyone who believes". This
does not mean that we just believ in the existence of God or Jesus.
Belief in the Chrsiatin sense usually means to believe and trust in
something. Second question: Is the good news of Jesus Christ changing
your life? God accepts us as we are and does want to leave us that way.
Jesus came to save the lost and change the found. Are you being
changed?
</p>






<p>
<?php
	backToSermonsTalksPage();
?>
</p>


<!-- ========================================================================== -->
<!--                              End Text Section                              -->
<!-- ========================================================================== -->
</div>


<!-- ========================================================================== -->
<!--                          Start Footer Content Section                      -->
<!-- ========================================================================== -->
<?php
	include('footer.php');
?>
<!-- ========================================================================== -->
<!--                            End Footer Content Section                      -->
<!-- ========================================================================== -->


<!-- ========================================================================== -->
<!--                            End of CSS Layout                               -->
<!-- ========================================================================== -->
</div>  <!-- END <div id="maincontainer"> -->


</body>
</html>

