<?php
	/******************************
		Talk to MySQL
	**********************************/
	require_once("mysql.php");


	/******************************
		Start a session
	**********************************/
	require_once("session.php");
	$oSession = new session();
?>
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 14/01/2005 -->
<head>
<title></title>
<?php
	require_once("nocache.php");	// Stop - hopefully - this page being cached
?>

<meta name="description" content="">
<meta name="keywords" content="">
<meta name="author" content="newey499@hotmail.com">
<meta name="generator" content="AceHTML 5 Freeware">

<!-- CSS Includes -->
<link rel="stylesheet" type="text/css" href="css/layout.css" />
<link rel="stylesheet" type="text/css" href="css/church.css" />
<link rel="stylesheet" type="text/css" media="print" href="css/print.css">

	
</head>
<body>

<?php
	require_once("mysql.php");
	require_once("globals.php");
	require_once("genlib.php");
?>

<?php
	include_once("topbanner.php");
?>

<!-- ========================================================================== -->
<!--                              Start Text Section                            --> 
<!-- ========================================================================== -->
<div style="margin-left:2em; margin-right:2em;">

<br />

<?php
	print("<a href=\"" . $_SERVER['HTTP_REFERER'] . "\">Back</a>\n");
?>


<!-- ========================================================================== -->
<!--                              Start Content Section                         --> 
<!-- ========================================================================== -->


Use h4 for headings


<!-- ========================================================================== -->
<!--                                End Content Section                         --> 
<!-- ========================================================================== -->



<?php
	print("<a href=\"" . $_SERVER['HTTP_REFERER'] . "\">Back</a>\n");
?>


<!-- ========================================================================== -->
<!--                              End Text Section                            --> 
<!-- ========================================================================== -->
</div>

<?php
	include_once("footer.php");
?>

</body>
</html>
