<?php
	require_once "../globals.php";
	require_once("../mysql.php");
	require_once("../buildform.php");
?>
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 02/12/2004 -->
<head>

	<title>Newsletters</title>
<?php
	include_once("../nocache.php");						// Stop clients from cacheing - hopefully
?>
	<meta name="description" content="">
	<meta name="keywords" content="">
	<meta name="author" content="Chris Newey">
	<meta name="generator" content="AceHTML 5 Freeware">

  <!-- CSS Includes -->
  <link rel="stylesheet" type="text/css" href="../css/layout.css" >
  <link rel="stylesheet" type="text/css" href="../css/church.css" >
  <link rel="stylesheet" type="text/css" href="../css/slideshow.css" >
  <link rel="stylesheet" type="text/css" href="../css/tooltip.css" >
  <link rel="stylesheet" type="text/css" media="print" href="../css/print.css" >
  <link rel="stylesheet" type="text/css" href="../css/cssdropdownmenu.css" />
  <!-- End CSS Includes -->

</head>
<body>

<!-- ========================================================================== -->
<!--                            Start of CSS Layout                             -->
<!-- ========================================================================== -->
<div id="maincontainer">

<!-- ------------------ HEADER --------------------------------------- -->


<?php

require_once('topbanner.php');

	$_GET['opcode'] = strtoupper($_GET['opcode']);

	switch ($_GET['opcode'])
	{
		case INSERT_REC:
			print "<h3>Insert a new Newsletter</h3>\n";
			break;
		case UPDATE_REC:
			print "<h3>Update this Newsletter Entry</h3>\n";
			break;
		case DELETE_REC:
			print "<h3>Delete this Newsletter</h3>\n";
			break;
		case NEWSLETTER_PUBLISH:
			print "<h3>Email this Newsletter to Subscribers</h3>\n";
			break;
		default:
			break;
	}
?>
<hr />
<!-- ---------------- END HEADER ------------------------------------- -->



<?php

	$query = "SELECT	id,
										DATE_FORMAT(publicationdate,'%d/%m/%Y') as pubdate,
						 				title,
										filename,
						 				newslettertext,
										emailed
        		FROM newsletters";


	if ((strcmp(strtoupper($_GET['opcode']), INSERT_REC) == 0)) {
		$query = $query . " LIMIT 0 OFFSET 1";  // This is an insert so only get one row for the meta information
	}
	else {
		$query = $query . " WHERE id = " . $_GET['id'];
	}

	/*************************
	$flds  = array('eventtime' 		=> 'Time',
								 'eventdate' 		=> 'Date',
	               'eventname'		=> 'Event Name',
	               'eventdesc' 		=> 'Description',
							  );
	***********************/



	$pkey = array('id'	=> $_GET['opcode']);

	$obj = new buildForm($_GET['opcode'],$query,$pkey,$flds);

	$obj->addField('emailed','Emailed',"",'Sent out on Mailing List');
	$obj->addField('pubdate','Publication Date','DD/MM/YYYY');
	$obj->addField('title','Title','Mandatory');
	$obj->addField('filename','Filename','Enter if Newsletter on file');
	$obj->addField('newslettertext','Newsletter Text');


	$obj->submitTarget = "sqlnewsletter.php";
	$obj->pkey = array('id' => $_GET['id']);

	$obj->addLink("index.php","Admin");	// Add a link to take us back to the Admin page
	$obj->addLink("../index.php","Home");			// Add a link to take us back to the Home page
	$obj->addLink("bnewsletter.php","Newsletters");	// Add a link to take us back to the Home page


	echo "<div class=\"cdnform\">\n";
	$obj->exec($opcode);
	echo "</div>\n";
?>
</P>

<!-- ------------------ FOOTER --------------------------------------- -->
<HR>


</div> <!-- End div  id="maincontainer"> -->
<!-- ========================================================================== -->
<!--                            End of CSS Layout                               -->
<!-- ========================================================================== -->


</body>
</html>
<!-- ---------------- END FOOTER ------------------------------------- -->
