<?php
	require_once "../globals.php";
	require_once("../mysql.php");
	require_once("../buildform.php");
?>
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 02/12/2004 -->
<head>

	<title>Regular Events</title>
<?php
	include_once("../nocache.php");						// Stop clients from cacheing - hopefully
?>
	<meta name="description" content="">
	<meta name="keywords" content="">
	<meta name="author" content="Chris Newey">
	<meta name="generator" content="AceHTML 5 Freeware">

  <!-- CSS Includes -->
  <link rel="stylesheet" type="text/css" href="../css/layout.css" >
  <link rel="stylesheet" type="text/css" href="../css/church.css" >
  <link rel="stylesheet" type="text/css" href="../css/slideshow.css" >
  <link rel="stylesheet" type="text/css" href="../css/tooltip.css" >
  <link rel="stylesheet" type="text/css" media="print" href="../css/print.css" >
  <link rel="stylesheet" type="text/css" href="../css/cssdropdownmenu.css" />
  <!-- End CSS Includes -->

</head>
<body style="margin-left:20px; margin-top:20px;">

<!-- ========================================================================== -->
<!--                            Start of CSS Layout                             -->
<!-- ========================================================================== -->
<div id="maincontainer">

<!-- ------------------ HEADER --------------------------------------- -->


<?php

require_once('topbanner.php');

	$_GET['opcode'] = strtoupper($_GET['opcode']);

	switch ($_GET['opcode']) {
		case INSERT_REC:
			print "<h3>Insert a new Regular Event</h3>\n";
			break;
		case UPDATE_REC:
			print "<h3>Update this existing Regular Event</h3>\n";
			break;
		case DELETE_REC:
			print "<h3>Delete this Regular Event</h3>\n";
			break;
		default:
			break;
	}
?>

<!-- ---------------- END HEADER ------------------------------------- -->



<?php

	$query = "SELECT id, dayofweek, weekofmonth, startdate, enddate, eventtime, eventname," .
             " eventdesc,isvisible, linkurl FROM regularevents ";


	if ((strcmp(strtoupper($_GET['opcode']), INSERT_REC) == 0)) {
		$query = $query . " LIMIT 0 OFFSET 1";  // This is an insert so only get one row for the meta information
	}
	else {
		$query = $query . " WHERE id = " . $_GET['id'];
	}


	$pkey = array('id'	=> $_GET['opcode']);

	$obj = new buildForm($_GET['opcode'],$query,$pkey, isset($flds) ? $flds : null);

	$obj->addField('dayofweek',   'Day');
	$obj->addField('weekofmonth', 'Week');
	$obj->addField('startdate',   'Start Date');
	$obj->addField('enddate',     'End Date');
	$obj->addField('eventtime',   'Event Time', 'HH:MM', 'Use 11:11 to suppress Display of Time' );
	$obj->addField('isvisible',   'Visible');
	$obj->addField('linkurl',     'Link URL');
	$obj->addField('eventname',   'Event Name');
	$obj->addField('eventdesc',   'Event Description');

	$obj->submitTarget = "sqlregevents.php";
	$obj->pkey = array('id' => safeGet('id'));

	$obj->addLink("index.php","Admin");	// Add a link to take us back to the Admin page
	$obj->addLink("index.php","Home");			// Add a link to take us back to the Home page
	$obj->addLink($_SERVER['HTTP_REFERER'],"Regular Events");			// Add a link to take us back to the browse page


	echo "<div class=\"cdnform\">\n";
	$obj->exec(safeGet('opcode'));
	echo "</div>\n";
?>
</P>

<!-- ------------------ FOOTER --------------------------------------- -->
<HR>


</div> <!-- End div  id="maincontainer"> -->
<!-- ========================================================================== -->
<!--                            End of CSS Layout                               -->
<!-- ========================================================================== -->


</body>
</html>
<!-- ---------------- END FOOTER ------------------------------------- -->
