<?php
	require_once "../globals.php";
	require_once("../mysql.php");
	require_once("../buildform.php");

?>
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 02/12/2004 -->
<head>

	<title>Forthcoming Events</title>
<?php
	include_once("../nocache.php");						// Stop clients from cacheing - hopefully
?>
	<meta name="description" content="">
	<meta name="keywords" content="">
	<meta name="author" content="Chris Newey">
	<meta name="generator" content="AceHTML 5 Freeware">

  <!-- CSS Includes -->
  <link rel="stylesheet" type="text/css" href="../css/layout.css" >
  <link rel="stylesheet" type="text/css" href="../css/church.css" >
  <link rel="stylesheet" type="text/css" href="../css/slideshow.css" >
  <link rel="stylesheet" type="text/css" href="../css/tooltip.css" >
  <link rel="stylesheet" type="text/css" media="print" href="../css/print.css" >
  <link rel="stylesheet" type="text/css" href="../css/cssdropdownmenu.css" />
  <!-- End CSS Includes -->

</head>
<body>

<!-- ========================================================================== -->
<!--                            Start of CSS Layout                             -->
<!-- ========================================================================== -->
<div id="maincontainer">

<!-- ------------------ HEADER --------------------------------------- -->


<?php

require_once('topbanner.php');

	$_GET['opcode'] = strtoupper($_GET['opcode']);

	switch ($_GET['opcode']) {
		case INSERT_REC:
			print "<h3>Insert a new Forthcoming Event</h3>\n";
			break;
		case UPDATE_REC:
			print "<h3>Update this existing Forthcoming Event</h3>\n";
			break;
		case DELETE_REC:
			print "<h3>Delete this Forthcoming Event</h3>\n";
			break;
		default:
			break;
	}
?>

<!-- ---------------- END HEADER ------------------------------------- -->



<?php

	$query = "SELECT id,
					orgid,
					DATE_FORMAT(eventdate,'%d/%m/%Y') as eventdate,
					date_format(eventdate,'%H:%i') as eventtime,
					eventname,
					eventdesc,
                    contribemail,
                    contactname,
                    contactphone,
                    contactemail,
                    isvisible,
					linkurl,
					tempfiles,
					twittertext,
					sendtotwitter,
					sendtofacebook,
					sendtogoogleplus,
					senttosocialmedia,
					lastupdated
				FROM forthcomingevents";

	if ((strcmp(strtoupper($_GET['opcode']), INSERT_REC) == 0)) {
		$query = $query . " LIMIT 0 OFFSET 1";  // This is an insert so only get one row for the meta information
	}
	else {
		$query = $query . " WHERE id = " . $_GET['id'];
	}

	/*************************
	$flds  = array('eventtime' 		=> 'Time',
								 'eventdate' 		=> 'Date',
	               'eventname'		=> 'Event Name',
	               'eventdesc' 		=> 'Description',
							  );
	***********************/



	$pkey = array('id'	=> $_GET['opcode']);

	$obj = new buildForm($_GET['opcode'],
						 $query,
						 $pkey,
						 (isset($flds) ? $flds : array()) );

	$obj->addField('isvisible','Visible',"YES", 'Set to "NO" to stop the event being displayed');
	$obj->addField('eventtime','Time','HH:MM', 'Use 11:11 to suppress Display of Time. Two digits required for Hours and Minutes');
	$obj->addField('eventdate','Date','DD/MM/YYYY', 'Two Digits for Day and Month. Four Digits for Year');
	$obj->addHiddenField('linkurl','Link URL');
	$obj->addHiddenField('tempfiles','Temporary Files', '', 'Temporary files associated with event - comma delimited');
	//$obj->setTextAreaSize('tempfiles', 4, 80);
	$obj->addField('eventname','Event Name','Mandatory','The name of the Event Eg. "Open Door Pancake Lunch"');
	$obj->addField('eventdesc','Description','','A short description of the event');
	$obj->addHiddenField('contribemail',"Contributor Email");
	$obj->addField('contactname',"Contact Name", '', 'Name of person to contact regarding event.');
	$obj->addField('contactphone',"Contact Phone", '', 'Telephone number of person to contact regarding event.');
	$obj->addField('contactemail',"Contact Email", '', 'Email of person to contact regarding event.');

	$obj->addField('twittertext',"Twitter Text","",
		"Text sent to Twitter Facebook etc. Note. What is typed here is exactly what is sent (Max. 140 characters)");
	$obj->addField('sendtotwitter',"Send to Twitter", '',
		'If this is set to "YES" then the message is sent to Twitter and copied to Facebook regardless of the Facebook setting below.');
	$obj->addField('sendtofacebook',"Send to Facebook", '',
		'Send above message to Facebook. If "Send to Twitter" is set to "NO" and "Send to Facebook" is set to "YES" ' .
		'then the message is only sent to Facebook.');
	$obj->addHiddenField('sendtogoogleplus',"Send to Google+", 'NO',
		'This is for the future. Goggle have yet to release the code that will permit the updating of Google+ from software.');
	$obj->addHiddenField('senttosocialmedia',"Sent to Social Media");
	$obj->addHiddenField('lastupdated',"Last updated");

	$obj->submitTarget = "sqlforthevents.php";
	$obj->pkey = array('id' => safeGet('id'));

	$obj->addLink("index.php","Admin");	// Add a link to take us back to the Admin page
	$obj->addLink("../index.php","Home");			// Add a link to take us back to the Home page
	$obj->addLink($_SERVER['HTTP_REFERER'],"Forthcoming Events");			// Add a link to take us back to the browse page

	// Increase the size of the text entry area
	$obj->textarearows = 20;
	$obj->textareacols = 80;

	echo "<div class=\"cdnform\">\n";
	$obj->exec( (isset($opcode) ? $opcode : '') );
	echo "</div>\n";
?>
</P>

<!-- ------------------ FOOTER --------------------------------------- -->
<HR>


</div> <!-- End div  id="maincontainer"> -->
<!-- ========================================================================== -->
<!--                            End of CSS Layout                               -->
<!-- ========================================================================== -->


</body>
</html>
<!-- ---------------- END FOOTER ------------------------------------- -->
