<?php
	require_once "../globals.php";
	require_once("../mysql.php");
	require_once("../buildform.php");
	$_POST['opcode'] = strtoupper($_POST['opcode']);

	switch ($_POST['opcode']) {
		case INSERT_REC:
			$pageTitle="Insert a new Regular Event";
			break;
		case UPDATE_REC:
			$pageTitle="Update this existing Regular Event";
			break;
		case DELETE_REC:
			$pageTitle="Delete this Regular Event";
			break;
		default:
			$pageTitle="Unexpected opcode " . $_POST['opcode'];
			break;
	}

?>
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 02/12/2004 -->
<head>
<title>Regular Events</title>
	<meta name="description" content="">
	<meta name="keywords" content="">
	<meta name="author" content="Chris Newey">

  <!-- CSS Includes -->
  <link rel="stylesheet" type="text/css" href="../css/layout.css" >
  <link rel="stylesheet" type="text/css" href="../css/church.css" >
  <link rel="stylesheet" type="text/css" href="../css/slideshow.css" >
  <link rel="stylesheet" type="text/css" href="../css/tooltip.css" >
  <link rel="stylesheet" type="text/css" media="print" href="../css/print.css" >
  <link rel="stylesheet" type="text/css" href="../css/cssdropdownmenu.css" />
  <!-- End CSS Includes -->

</head>
<body style="margin-left:20px; margin-top:20px;">

<!-- ========================================================================== -->
<!--                            Start of CSS Layout                             -->
<!-- ========================================================================== -->
<div id="maincontainer">

<!-- ------------------ HEADER --------------------------------------- -->
<?php
require_once('topbanner.php');


print "<H3>$pageTitle</H3>\n";
?>

<!-- ---------------- END HEADER ------------------------------------- -->


<?php

/*********************
 Validate fields to be written to row

 ****************************************/
function validate() {

	$result = true;
	$oDate = new mysqldate();

	// If we are going to delete it we don't care if its valid
	if ($_POST['opcode'] == DELETE_REC)
	{
		return True;
	}


	// start date must be a valid date
	if ((!isset($_POST['startdate'])) || (!is_string($_POST['startdate'])) || (trim($_POST['startdate']) == ""))
	{
		dispError("Start Date is not a valid date");
		$result = false;
	}
	else
	{
		if ( ! $oDate->checkUKdate($_POST['startdate']) )
		{
			dispError("Start Date is not a valid date");
			$result = false;
		}
	}

	// end date if present must be a valid date - an empty date is OK - it means no expiry date
	if ((!isset($_POST['enddate'])) || (!is_string($_POST['enddate'])) || (trim($_POST['enddate']) == ""))
	{
		if ( trim($_POST['enddate']) == "")
		{
			$_POST['enddate'] = 'NULL';
			$result = true;
		}
		else
		{
			dispError("End Date is not a valid date");
			$result = false;
		}
	}
	else
	{
		if ( trim($_POST['enddate']) == "00/00/0000")
		{
			$_POST['enddate'] = 'NULL';
			$result = true;
		}
		else if ( trim($_POST['enddate']) == "DD/MM/YYYY")
		{
			$_POST['enddate'] = 'NULL';
			$result = true;
		} else if ( (! $oDate->checkUKdate($_POST['enddate']) ) )
		{
			dispError("End Date is not a valid date");
			$result = false;
		}
	}

	$oTime = new mysqltime();
	// Event time must be a valid time
	if ((!isset($_POST['eventtime'])) || (!is_string($_POST['eventtime'])) || (trim($_POST['eventtime']) == ""))
	{
		dispError("Event Time is not a valid time");
		$result = false;
	}
	else
	{
		if ( ! $oTime->checkTime($_POST['eventtime']) )
		{
			dispError("Event Time is not a valid time");
			$result = false;
		}
	}

	//eventname may not be blank
	if ((!isset($_POST['eventname'])) || (!is_string($_POST['eventname'])) || (trim($_POST['eventname']) == ""))
	{
		dispError("Event Name may not be blank");
		$result = false;
	}

	//eventdesc may not be blank
	if ((!isset($_POST['eventdesc'])) || (!is_string($_POST['eventdesc'])) || (trim($_POST['eventdesc']) == ""))
	{
		dispWarn("Warning : Event Description may not be blank");
	}

	return $result;
}




/********************
 Add/Amend/Delete SQL
 ***********************/
function doSQL() {

	/* Connect to a MySQL server */
	$dbHandle = mysql_connect(MYSQL_SERVER, MYSQL_USERNAME, MYSQL_PASSWORD)
	   or die('Could not connect: ' . mysql_error());

	mysql_select_db(MYSQL_DATABASE)  or die('Could not select database');

	$oDate = new mysqldate();

	switch ($_POST['opcode']) {
		case INSERT_REC:
			$stmnt = sprintf("INSERT INTO regularevents
											(dayofweek, weekofmonth, startdate, enddate, eventtime, eventname, eventdesc, isvisible, linkurl)
											VALUES ('%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s')",
											mysql_real_escape_string($_POST['dayofweek']),
											mysql_real_escape_string($_POST['weekofmonth']),
											mysql_real_escape_string($oDate->UkDateToMySql($_POST['startdate'])),
											mysql_real_escape_string($oDate->UkDateToMySql($_POST['enddate'])),
											mysql_real_escape_string($_POST['eventtime']),
											mysql_real_escape_string($_POST['eventname']),
											mysql_real_escape_string($_POST['eventdesc']),
											mysql_real_escape_string($_POST['isvisible']),
											mysql_real_escape_string($_POST['linkurl'])
										);
			$msg = 'Record Created OK';
			break;

		case UPDATE_REC:
			$stmnt = sprintf("UPDATE regularevents
											 SET dayofweek = '%s',
                           weekofmonth = '%s',
                           startdate = '%s',
                           enddate = '%s',
                           eventtime = '%s',
                           eventname = '%s',
                           eventdesc = '%s',
                           isvisible = '%s',
                           linkurl   = '%s'
											 WHERE id=%d",
										 	 mysql_real_escape_string($_POST['dayofweek']),
											 mysql_real_escape_string($_POST['weekofmonth']),
											 mysql_real_escape_string($oDate->UkDateToMySql($_POST['startdate'])),
											 mysql_real_escape_string($oDate->UkDateToMySql($_POST['enddate'])),
											 mysql_real_escape_string($_POST['eventtime']),
											 mysql_real_escape_string($_POST['eventname']),
											 mysql_real_escape_string($_POST['eventdesc']),
											 mysql_real_escape_string($_POST['isvisible']),
											 mysql_real_escape_string($_POST['linkurl']),
											 $_POST['id']
											 );
			$msg = "Record updated OK";
			break;

		case DELETE_REC:
			$stmnt = sprintf("DELETE FROM regularevents
																WHERE id=%d",
											$_POST['id']
											);
			$msg = "Record Deleted OK";
			break;

		default:
			die("Unknown opcode in sqlregevents.php");
			break;
	}



	if (mysql_query($stmnt)) {
		touchMenuItem("whats on calendar");
		print("<p>" . $msg . "</p>\n");
	}
	else {
		print("<p>" . mysql_error() . "</p>\n");
	}



}

?>



<?php
	/*****************
	 Main Processing
	 **********************/

	$_POST['opcode'] = strtoupper($_POST['opcode']);

	if (validate())
		doSQL();
	else {
		$args = http_build_query(array('opcode' => $_POST['opcode']) + array('id' => $_POST['id']));
		print("<p>Return to Regular Event <a href=\"editregevents.php?$args\">Edit Page</a></p>\n");
	}

	$args = isset($args) ? $args: "";
	print("<p>" .
	      "Return to <a href=\"bregevent.php?" . $args . "\">Regular Events</a>" .
	      "&nbsp&nbsp<a href=\"index.php?" . $args . "\">Admin</a>" .
	      "</p>\n");

?>

<!-- ------------------ FOOTER --------------------------------------- -->
<?php
	require_once('footer.php');
?>
<!-- ---------------- END FOOTER ------------------------------------- -->

</div> <!-- End div  id="maincontainer"> -->
<!-- ========================================================================== -->
<!--                            End of CSS Layout                               -->
<!-- ========================================================================== -->

</body>
</html>

