<?php
	require_once "../globals.php";
	require_once("../mysql.php");
	require_once("../buildform.php");
	require_once("../rest-service/class.sermonstalks.php");
	require_once("../class.socialmedia.php");


	/* Connect to a MySQL server */
	$dbHandle = mysql_connect(MYSQL_SERVER, MYSQL_USERNAME, MYSQL_PASSWORD)
		 or die('Could not connect: ' . mysql_error());

	mysql_select_db(MYSQL_DATABASE)  or die('Could not select database');

	$_POST['opcode'] = strtoupper($_POST['opcode']);

	switch ($_POST['opcode']) {
		case INSERT_REC:
			$pageTitle="Insert a new Sermon/Talk";
			break;
		case UPDATE_REC:
			$pageTitle="Update this existing Sermon/Talk";
			break;
		case DELETE_REC:
			$pageTitle="Delete this Sermon/Talk";
			break;
		default:
			$pageTitle="Unexpected opcode " . $_POST['opcode'];
			break;
	}

?>
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 02/12/2004 -->
<head>
<?php
	print("<title>$pageTitle</title>\n");
?>
	<meta name="description" content="">
	<meta name="keywords" content="">
	<meta name="author" content="Chris Newey">

  <!-- CSS Includes -->
  <link rel="stylesheet" type="text/css" href="../css/layout.css" >
  <link rel="stylesheet" type="text/css" href="../css/church.css" >
  <link rel="stylesheet" type="text/css" href="../css/slideshow.css" >
  <link rel="stylesheet" type="text/css" href="../css/tooltip.css" >
  <link rel="stylesheet" type="text/css" media="print" href="../css/print.css" >
  <link rel="stylesheet" type="text/css" href="../css/cssdropdownmenu.css" />
  <!-- End CSS Includes -->

</head>

<body style="margin-left:20px; margin-top:20px;">

<!-- ========================================================================== -->
<!--                            Start of CSS Layout                             -->
<!-- ========================================================================== -->
<div id="maincontainer">

<!-- ------------------ HEADER --------------------------------------- -->
<?php

require_once('topbanner.php');

print "<H3>$pageTitle</H3>\n";
?>
<hr />
<!-- ---------------- END HEADER ------------------------------------- -->


<?php

/*********************
 Validate fields to be written to row

 ****************************************/
function validate()
{

	$oEvent = new SermonsTalks();

	$timeObj = new mysqltime;
	$dateObj = new mysqldate;
	$result = $oEvent->validate($_POST);
	// *****************************************
	// CDN 20/03/12 This validation is now done in the validate method of the
	// 						 SermonsTalks Class.
	//
	// The loop below is called unconditionally because when returning a warning alone the validate
	// method return true.
	// ********************************************
	foreach($oEvent->getErrors() as $arr)
	{
		switch ($arr[$oEvent::ERROR_TYPE])
		{
			case ($oEvent::VALIDATION_ERROR) :
				dispError($arr[$oEvent::ERROR_MSG]);
				break;

			case ($oEvent::VALIDATION_WARNING) :
				dispWarn($arr[$oEvent::ERROR_MSG]);
				break;

			default:

		}

	}

	return $result;
}




/********************
 Add/Amend/Delete SQL
 ***********************/
function doSQL($mysqli) {

	$dateObj = new mysqldate;

	// Time of 11:11 'cos time is irrelevant
	$eventdate = $dateObj->fmtDateTime($dateObj->UK_DATE, $_POST['dateperformed'], "11:11");


	switch ($_POST['opcode']) {
		case INSERT_REC:
			$stmnt = sprintf("INSERT INTO sermonstalks
							(
								dateperformed, filename, series, biblebook, bibleref,
								title, preacher, description, groupno, itemno,
								twittertext, sendtotwitter, sendtofacebook, sendtogoogleplus, senttosocialmedia,
								lastupdated
							)
							VALUES ('%s', '%s', '%s', '%s', '%s',
									'%s', '%s', '%s', '%s', '%s',
									'%s', '%s', '%s', '%s', '%s',
									'%s'
                               )",
												mysql_real_escape_string($eventdate),
												mysql_real_escape_string($_POST['filename']),
												mysql_real_escape_string($_POST['series']),
												mysql_real_escape_string($_POST['biblebook']),
												mysql_real_escape_string($_POST['bibleref']),
												mysql_real_escape_string($_POST['title']),
												mysql_real_escape_string($_POST['preacher']),
												mysql_real_escape_string($_POST['description']),
												mysql_real_escape_string($_POST['groupno']),
												mysql_real_escape_string($_POST['itemno']),
												mysql_real_escape_string($_POST['twittertext']),
												mysql_real_escape_string($_POST['sendtotwitter']),
												mysql_real_escape_string($_POST['sendtofacebook']),
												mysql_real_escape_string($_POST['sendtogoogleplus']),
												mysql_real_escape_string($_POST['senttosocialmedia']),
												date("Y-m-d h:i:00")
											);
			$msg = "New record created OK";
			break;

		case UPDATE_REC:
			$stmnt = sprintf("UPDATE sermonstalks
								SET
									dateperformed = '%s',
									filename = '%s',
									series = '%s',
									biblebook = '%s',
									bibleref = '%s',
									title = '%s',
									preacher = '%s',
									description = '%s',
									groupno = '%s',
									itemno = '%s',
									twittertext = '%s',
									sendtotwitter = '%s',
									sendtofacebook = '%s',
									sendtogoogleplus = '%s',
									senttosocialmedia = '%s',
									lastupdated = '%s'
								WHERE id=%d",
												mysql_real_escape_string($eventdate),
												mysql_real_escape_string($_POST['filename']),
												mysql_real_escape_string($_POST['series']),
												mysql_real_escape_string($_POST['biblebook']),
												mysql_real_escape_string($_POST['bibleref']),
												mysql_real_escape_string($_POST['title']),
												mysql_real_escape_string($_POST['preacher']),
												mysql_real_escape_string($_POST['description']),
												mysql_real_escape_string($_POST['groupno']),
												mysql_real_escape_string($_POST['itemno']),
												mysql_real_escape_string($_POST['twittertext']),
												mysql_real_escape_string($_POST['sendtotwitter']),
												mysql_real_escape_string($_POST['sendtofacebook']),
												mysql_real_escape_string($_POST['sendtogoogleplus']),
												mysql_real_escape_string($_POST['senttosocialmedia']),
												date("Y-m-d h:i:00"),
												$_POST['id']
											);

			$msg = "Record updated OK";
			break;

		case DELETE_REC:
			$stmnt = sprintf("DELETE FROM sermonstalks
												WHERE id=%d",
												$_POST['id']
												);
			$msg = "Record Deleted OK";
			break;

		default:
			break;
	}

	if (mysql_query($stmnt))
	{
		if ($_POST['opcode'] == INSERT_REC)
		{
			$_POST['id'] = mysql_insert_id();
		}

		setLastupdatedDate( date('d/m/Y'), date('H:i'));
		touchMenuItem("sermons and talks");

		if (isset($_POST['opcode']) &&
			( ($_POST['opcode'] == INSERT_REC) || ($_POST['opcode'] == UPDATE_REC) ) )
		{
			$oSocialMedia = new SocialMedia(
						$_POST[SocialMedia::CHKBOX_TWITTER] == "YES" ? true : false,
						$_POST[SocialMedia::CHKBOX_FACEBOOK] == "YES" ? true : false,
						$_POST[SocialMedia::CHKBOX_GOOGLEPLUS] == "YES" ? true : false );

			$cursorRow = $oSocialMedia->setMenuPrompt("sermons and talks");
			$msg = $oSocialMedia->getMenuPrompt() .
				": New MP3: " .$_POST['title'] . " " . $oSocialMedia->getShortUrl();

			$qry = "UPDATE sermonstalks SET twittertext = '" . $msg . "' WHERE id = " . $_POST['id'];
			mysql_query($qry);

			$oSocialMedia->exec($msg);
			print("<p>" . $msg . "</p>\n");
			//print_r($_POST);
		}
		else
		{
			print("<p>Social Media not sent.<br />" . print_r($_POST) . "</p>");
		}
	}
	else {
		print("<p>" . mysql_error() . "</p>\n<p>" . $stmnt . "</p>\n");
		print_r($_POST);
	}


}

?>



<?php
	/*****************
	 Main Processing
	 **********************/

	$_POST['opcode'] = strtoupper($_POST['opcode']);


	/* Connect to a MySQL server */
	$dbHandle = mysql_connect(MYSQL_SERVER, MYSQL_USERNAME, MYSQL_PASSWORD)
	   or die('Could not connect: ' . mysql_error());

	mysql_select_db(MYSQL_DATABASE)  or die('Could not select database');


	$args = "";
	if (validate()){
		doSQL($dbHandle);
	}
	else {
		$args = http_build_query(array('opcode' => $_POST['opcode']) + array('id' => $_POST['id']));
		print("<p>Return to Sermons/Talks <a href=\"editsermonstalks.php?$args\">Edit Page</a></p>\n");
	}


	print("<p>Return to <a href=\"bsermonstalks.php?$args\">Sermons/Talks</a>" .
		    "&nbsp&nbsp<a href=\"index.php?$args\">Admin</a>" .
				"</p>\n");


?>

<!-- ------------------ FOOTER --------------------------------------- -->
<?php
	require_once('footer.php');
?>
<!-- ---------------- END FOOTER ------------------------------------- -->

</div> <!-- End div  id="maincontainer"> -->
<!-- ========================================================================== -->
<!--                            End of CSS Layout                               -->
<!-- ========================================================================== -->

</body>
</html>

